// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: i18n.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocaleBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	Entries       map[string]string      `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleBundle) Reset() {
	*x = LocaleBundle{}
	mi := &file_i18n_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleBundle) ProtoMessage() {}

func (x *LocaleBundle) ProtoReflect() protoreflect.Message {
	mi := &file_i18n_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleBundle.ProtoReflect.Descriptor instead.
func (*LocaleBundle) Descriptor() ([]byte, []int) {
	return file_i18n_proto_rawDescGZIP(), []int{0}
}

func (x *LocaleBundle) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *LocaleBundle) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LocaleSet struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Bundles       map[string]*LocaleBundle `protobuf:"bytes,1,rep,name=bundles,proto3" json:"bundles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // locale code → bundle
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleSet) Reset() {
	*x = LocaleSet{}
	mi := &file_i18n_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleSet) ProtoMessage() {}

func (x *LocaleSet) ProtoReflect() protoreflect.Message {
	mi := &file_i18n_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleSet.ProtoReflect.Descriptor instead.
func (*LocaleSet) Descriptor() ([]byte, []int) {
	return file_i18n_proto_rawDescGZIP(), []int{1}
}

func (x *LocaleSet) GetBundles() map[string]*LocaleBundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

var File_i18n_proto protoreflect.FileDescriptor

const file_i18n_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"i18n.proto\x12\x0etgbase.i18n.v1\"\xa7\x01\n" +
	"\fLocaleBundle\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x12C\n" +
	"\aentries\x18\x02 \x03(\v2).tgbase.i18n.v1.LocaleBundle.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\tLocaleSet\x12@\n" +
	"\abundles\x18\x01 \x03(\v2&.tgbase.i18n.v1.LocaleSet.BundlesEntryR\abundles\x1aX\n" +
	"\fBundlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.tgbase.i18n.v1.LocaleBundleR\x05value:\x028\x01B1Z/github.com/padington/tgbase/internal/i18n/pb;pbb\x06proto3"

var (
	file_i18n_proto_rawDescOnce sync.Once
	file_i18n_proto_rawDescData []byte
)

func file_i18n_proto_rawDescGZIP() []byte {
	file_i18n_proto_rawDescOnce.Do(func() {
		file_i18n_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_i18n_proto_rawDesc), len(file_i18n_proto_rawDesc)))
	})
	return file_i18n_proto_rawDescData
}

var file_i18n_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_i18n_proto_goTypes = []any{
	(*LocaleBundle)(nil), // 0: tgbase.i18n.v1.LocaleBundle
	(*LocaleSet)(nil),    // 1: tgbase.i18n.v1.LocaleSet
	nil,                  // 2: tgbase.i18n.v1.LocaleBundle.EntriesEntry
	nil,                  // 3: tgbase.i18n.v1.LocaleSet.BundlesEntry
}
var file_i18n_proto_depIdxs = []int32{
	2, // 0: tgbase.i18n.v1.LocaleBundle.entries:type_name -> tgbase.i18n.v1.LocaleBundle.EntriesEntry
	3, // 1: tgbase.i18n.v1.LocaleSet.bundles:type_name -> tgbase.i18n.v1.LocaleSet.BundlesEntry
	0, // 2: tgbase.i18n.v1.LocaleSet.BundlesEntry.value:type_name -> tgbase.i18n.v1.LocaleBundle
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_i18n_proto_init() }
func file_i18n_proto_init() {
	if File_i18n_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_i18n_proto_rawDesc), len(file_i18n_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_i18n_proto_goTypes,
		DependencyIndexes: file_i18n_proto_depIdxs,
		MessageInfos:      file_i18n_proto_msgTypes,
	}.Build()
	File_i18n_proto = out.File
	file_i18n_proto_goTypes = nil
	file_i18n_proto_depIdxs = nil
}
