// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: state.proto

package pb

import (
	pb "github.com/padington/tgbase/internal/products/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateKind int32

const (
	StateKind_STATE_UNSPECIFIED               StateKind = 0
	StateKind_STATE_IDLE                      StateKind = 1
	StateKind_STATE_AWAITING_DEFECATION       StateKind = 2
	StateKind_STATE_AWAITING_PRODUCT_CHOICE   StateKind = 3
	StateKind_STATE_AWAITING_STAGE_CHECKIN    StateKind = 4
	StateKind_STATE_AWAITING_STAGE_CHOICE     StateKind = 5
	StateKind_STATE_AWAITING_MODE_CHOICE      StateKind = 6
	StateKind_STATE_SCR_CONSENT               StateKind = 7
	StateKind_STATE_SCR_INTRO                 StateKind = 8
	StateKind_STATE_SCR_ASRS_A                StateKind = 9
	StateKind_STATE_SCR_ASRS_A_GATE           StateKind = 10
	StateKind_STATE_SCR_ASRS_B                StateKind = 11
	StateKind_STATE_SCR_ASRS_B_GATE           StateKind = 12
	StateKind_STATE_SCR_WURS_FORM             StateKind = 13
	StateKind_STATE_SCR_WURS                  StateKind = 14
	StateKind_STATE_SCR_WURS_GATE             StateKind = 15
	StateKind_STATE_SCR_ONSET                 StateKind = 16
	StateKind_STATE_SCR_ONSET_AGE             StateKind = 17
	StateKind_STATE_SCR_DOMAINS_ADULT         StateKind = 18
	StateKind_STATE_SCR_DOMAINS_CHILD         StateKind = 19
	StateKind_STATE_SCR_REFERRAL              StateKind = 20
	StateKind_STATE_SCR_REPORT                StateKind = 21
	StateKind_STATE_SCR_DELETE_CONFIRM        StateKind = 22
	StateKind_STATE_AWAITING_PRODUCT_CATEGORY StateKind = 23
	StateKind_STATE_MOOD_CONSENT              StateKind = 24
	StateKind_STATE_MOOD_QUESTION             StateKind = 25
	StateKind_STATE_MOOD_CRISIS               StateKind = 26
	StateKind_STATE_MOOD_REPORT               StateKind = 27
	StateKind_STATE_MOOD_DELETE_CONFIRM       StateKind = 28
	StateKind_STATE_MOOD_MENU                 StateKind = 29
	StateKind_STATE_MOOD_Q10                  StateKind = 30
	StateKind_STATE_MOOD_WHO5_QUESTION        StateKind = 31
	StateKind_STATE_MOOD_OFFER_PHQ9           StateKind = 32
	StateKind_STATE_MOOD_GAD7_QUESTION        StateKind = 33
	StateKind_STATE_MOOD_OFFER_GAD7           StateKind = 34
	StateKind_STATE_EAT_CONSENT               StateKind = 35
	StateKind_STATE_EAT_MENU                  StateKind = 36
	StateKind_STATE_EAT_EDEQS_QUESTION        StateKind = 37
	StateKind_STATE_EAT_BES_QUESTION          StateKind = 38
	StateKind_STATE_EAT_NIAS_QUESTION         StateKind = 39
	StateKind_STATE_EAT_REPORT                StateKind = 40
	StateKind_STATE_EAT_DELETE_CONFIRM        StateKind = 41
	// Pushup track (pu_*). STATE_PU_REST is the first state the reminder loop
	// scans for a within-session ping; the rest are ordinary input states.
	StateKind_STATE_PU_CONSENT        StateKind = 42
	StateKind_STATE_PU_GATE           StateKind = 43
	StateKind_STATE_PU_GOAL           StateKind = 44
	StateKind_STATE_PU_VARIATION      StateKind = 45
	StateKind_STATE_PU_TEST           StateKind = 46
	StateKind_STATE_PU_MENU           StateKind = 47
	StateKind_STATE_PU_SET            StateKind = 48
	StateKind_STATE_PU_REST           StateKind = 49
	StateKind_STATE_PU_EFFORT         StateKind = 50
	StateKind_STATE_PU_WEEK_FORK      StateKind = 51
	StateKind_STATE_PU_RED_CARD       StateKind = 52
	StateKind_STATE_PU_PROGRESS       StateKind = 53
	StateKind_STATE_PU_DELETE_CONFIRM StateKind = 54
)

// Enum value maps for StateKind.
var (
	StateKind_name = map[int32]string{
		0:  "STATE_UNSPECIFIED",
		1:  "STATE_IDLE",
		2:  "STATE_AWAITING_DEFECATION",
		3:  "STATE_AWAITING_PRODUCT_CHOICE",
		4:  "STATE_AWAITING_STAGE_CHECKIN",
		5:  "STATE_AWAITING_STAGE_CHOICE",
		6:  "STATE_AWAITING_MODE_CHOICE",
		7:  "STATE_SCR_CONSENT",
		8:  "STATE_SCR_INTRO",
		9:  "STATE_SCR_ASRS_A",
		10: "STATE_SCR_ASRS_A_GATE",
		11: "STATE_SCR_ASRS_B",
		12: "STATE_SCR_ASRS_B_GATE",
		13: "STATE_SCR_WURS_FORM",
		14: "STATE_SCR_WURS",
		15: "STATE_SCR_WURS_GATE",
		16: "STATE_SCR_ONSET",
		17: "STATE_SCR_ONSET_AGE",
		18: "STATE_SCR_DOMAINS_ADULT",
		19: "STATE_SCR_DOMAINS_CHILD",
		20: "STATE_SCR_REFERRAL",
		21: "STATE_SCR_REPORT",
		22: "STATE_SCR_DELETE_CONFIRM",
		23: "STATE_AWAITING_PRODUCT_CATEGORY",
		24: "STATE_MOOD_CONSENT",
		25: "STATE_MOOD_QUESTION",
		26: "STATE_MOOD_CRISIS",
		27: "STATE_MOOD_REPORT",
		28: "STATE_MOOD_DELETE_CONFIRM",
		29: "STATE_MOOD_MENU",
		30: "STATE_MOOD_Q10",
		31: "STATE_MOOD_WHO5_QUESTION",
		32: "STATE_MOOD_OFFER_PHQ9",
		33: "STATE_MOOD_GAD7_QUESTION",
		34: "STATE_MOOD_OFFER_GAD7",
		35: "STATE_EAT_CONSENT",
		36: "STATE_EAT_MENU",
		37: "STATE_EAT_EDEQS_QUESTION",
		38: "STATE_EAT_BES_QUESTION",
		39: "STATE_EAT_NIAS_QUESTION",
		40: "STATE_EAT_REPORT",
		41: "STATE_EAT_DELETE_CONFIRM",
		42: "STATE_PU_CONSENT",
		43: "STATE_PU_GATE",
		44: "STATE_PU_GOAL",
		45: "STATE_PU_VARIATION",
		46: "STATE_PU_TEST",
		47: "STATE_PU_MENU",
		48: "STATE_PU_SET",
		49: "STATE_PU_REST",
		50: "STATE_PU_EFFORT",
		51: "STATE_PU_WEEK_FORK",
		52: "STATE_PU_RED_CARD",
		53: "STATE_PU_PROGRESS",
		54: "STATE_PU_DELETE_CONFIRM",
	}
	StateKind_value = map[string]int32{
		"STATE_UNSPECIFIED":               0,
		"STATE_IDLE":                      1,
		"STATE_AWAITING_DEFECATION":       2,
		"STATE_AWAITING_PRODUCT_CHOICE":   3,
		"STATE_AWAITING_STAGE_CHECKIN":    4,
		"STATE_AWAITING_STAGE_CHOICE":     5,
		"STATE_AWAITING_MODE_CHOICE":      6,
		"STATE_SCR_CONSENT":               7,
		"STATE_SCR_INTRO":                 8,
		"STATE_SCR_ASRS_A":                9,
		"STATE_SCR_ASRS_A_GATE":           10,
		"STATE_SCR_ASRS_B":                11,
		"STATE_SCR_ASRS_B_GATE":           12,
		"STATE_SCR_WURS_FORM":             13,
		"STATE_SCR_WURS":                  14,
		"STATE_SCR_WURS_GATE":             15,
		"STATE_SCR_ONSET":                 16,
		"STATE_SCR_ONSET_AGE":             17,
		"STATE_SCR_DOMAINS_ADULT":         18,
		"STATE_SCR_DOMAINS_CHILD":         19,
		"STATE_SCR_REFERRAL":              20,
		"STATE_SCR_REPORT":                21,
		"STATE_SCR_DELETE_CONFIRM":        22,
		"STATE_AWAITING_PRODUCT_CATEGORY": 23,
		"STATE_MOOD_CONSENT":              24,
		"STATE_MOOD_QUESTION":             25,
		"STATE_MOOD_CRISIS":               26,
		"STATE_MOOD_REPORT":               27,
		"STATE_MOOD_DELETE_CONFIRM":       28,
		"STATE_MOOD_MENU":                 29,
		"STATE_MOOD_Q10":                  30,
		"STATE_MOOD_WHO5_QUESTION":        31,
		"STATE_MOOD_OFFER_PHQ9":           32,
		"STATE_MOOD_GAD7_QUESTION":        33,
		"STATE_MOOD_OFFER_GAD7":           34,
		"STATE_EAT_CONSENT":               35,
		"STATE_EAT_MENU":                  36,
		"STATE_EAT_EDEQS_QUESTION":        37,
		"STATE_EAT_BES_QUESTION":          38,
		"STATE_EAT_NIAS_QUESTION":         39,
		"STATE_EAT_REPORT":                40,
		"STATE_EAT_DELETE_CONFIRM":        41,
		"STATE_PU_CONSENT":                42,
		"STATE_PU_GATE":                   43,
		"STATE_PU_GOAL":                   44,
		"STATE_PU_VARIATION":              45,
		"STATE_PU_TEST":                   46,
		"STATE_PU_MENU":                   47,
		"STATE_PU_SET":                    48,
		"STATE_PU_REST":                   49,
		"STATE_PU_EFFORT":                 50,
		"STATE_PU_WEEK_FORK":              51,
		"STATE_PU_RED_CARD":               52,
		"STATE_PU_PROGRESS":               53,
		"STATE_PU_DELETE_CONFIRM":         54,
	}
)

func (x StateKind) Enum() *StateKind {
	p := new(StateKind)
	*p = x
	return p
}

func (x StateKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateKind) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[0].Descriptor()
}

func (StateKind) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[0]
}

func (x StateKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateKind.Descriptor instead.
func (StateKind) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

type DefecationKind int32

const (
	DefecationKind_DEFECATION_UNSPECIFIED DefecationKind = 0
	DefecationKind_DEFECATION_FLUID       DefecationKind = 1
	DefecationKind_DEFECATION_NORMAL      DefecationKind = 2
	DefecationKind_DEFECATION_ISSUES      DefecationKind = 3
)

// Enum value maps for DefecationKind.
var (
	DefecationKind_name = map[int32]string{
		0: "DEFECATION_UNSPECIFIED",
		1: "DEFECATION_FLUID",
		2: "DEFECATION_NORMAL",
		3: "DEFECATION_ISSUES",
	}
	DefecationKind_value = map[string]int32{
		"DEFECATION_UNSPECIFIED": 0,
		"DEFECATION_FLUID":       1,
		"DEFECATION_NORMAL":      2,
		"DEFECATION_ISSUES":      3,
	}
)

func (x DefecationKind) Enum() *DefecationKind {
	p := new(DefecationKind)
	*p = x
	return p
}

func (x DefecationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefecationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[1].Descriptor()
}

func (DefecationKind) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[1]
}

func (x DefecationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefecationKind.Descriptor instead.
func (DefecationKind) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

type ProductProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastStage     pb.Stage               `protobuf:"varint,1,opt,name=last_stage,json=lastStage,proto3,enum=tgbase.products.v1.Stage" json:"last_stage,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // in_progress|completed|not_tolerated|interrupted
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductProgress) Reset() {
	*x = ProductProgress{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductProgress) ProtoMessage() {}

func (x *ProductProgress) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductProgress.ProtoReflect.Descriptor instead.
func (*ProductProgress) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *ProductProgress) GetLastStage() pb.Stage {
	if x != nil {
		return x.LastStage
	}
	return pb.Stage(0)
}

func (x *ProductProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductProgress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ScreeningProgress mirrors state.ScreeningProgress — the TRANSIENT
// unfinished ADHD-screening run (raw per-question answers live only here;
// wiped on completion / restart / abandon / delete).
type ScreeningProgress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AsrsAnswers    []int32                `protobuf:"varint,1,rep,packed,name=asrs_answers,json=asrsAnswers,proto3" json:"asrs_answers,omitempty"` // append-only, scores 0..4; index = id-1
	WursAnswers    []int32                `protobuf:"varint,2,rep,packed,name=wurs_answers,json=wursAnswers,proto3" json:"wurs_answers,omitempty"` // append-only, scores 0..4
	WursForm       string                 `protobuf:"bytes,3,opt,name=wurs_form,json=wursForm,proto3" json:"wurs_form,omitempty"`                  // "m" | "f"
	OnsetChild     *bool                  `protobuf:"varint,4,opt,name=onset_child,json=onsetChild,proto3,oneof" json:"onset_child,omitempty"`     // absent = not asked yet
	OnsetAge       int32                  `protobuf:"varint,5,opt,name=onset_age,json=onsetAge,proto3" json:"onset_age,omitempty"`                 // >0 when onset_child == false
	AdultDomains   []string               `protobuf:"bytes,6,rep,name=adult_domains,json=adultDomains,proto3" json:"adult_domains,omitempty"`      // only the ids answered "yes"
	ChildDomains   []string               `protobuf:"bytes,7,rep,name=child_domains,json=childDomains,proto3" json:"child_domains,omitempty"`      // only the ids answered "yes"
	ResumeState    StateKind              `protobuf:"varint,8,opt,name=resume_state,json=resumeState,proto3,enum=tgbase.state.v1.StateKind" json:"resume_state,omitempty"`
	ConsentAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=consent_at,json=consentAt,proto3" json:"consent_at,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	AdultDomainIdx int32                  `protobuf:"varint,11,opt,name=adult_domain_idx,json=adultDomainIdx,proto3" json:"adult_domain_idx,omitempty"` // domains answered so far (yes AND no)
	ChildDomainIdx int32                  `protobuf:"varint,12,opt,name=child_domain_idx,json=childDomainIdx,proto3" json:"child_domain_idx,omitempty"` // domains answered so far (yes AND no)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScreeningProgress) Reset() {
	*x = ScreeningProgress{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreeningProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreeningProgress) ProtoMessage() {}

func (x *ScreeningProgress) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreeningProgress.ProtoReflect.Descriptor instead.
func (*ScreeningProgress) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *ScreeningProgress) GetAsrsAnswers() []int32 {
	if x != nil {
		return x.AsrsAnswers
	}
	return nil
}

func (x *ScreeningProgress) GetWursAnswers() []int32 {
	if x != nil {
		return x.WursAnswers
	}
	return nil
}

func (x *ScreeningProgress) GetWursForm() string {
	if x != nil {
		return x.WursForm
	}
	return ""
}

func (x *ScreeningProgress) GetOnsetChild() bool {
	if x != nil && x.OnsetChild != nil {
		return *x.OnsetChild
	}
	return false
}

func (x *ScreeningProgress) GetOnsetAge() int32 {
	if x != nil {
		return x.OnsetAge
	}
	return 0
}

func (x *ScreeningProgress) GetAdultDomains() []string {
	if x != nil {
		return x.AdultDomains
	}
	return nil
}

func (x *ScreeningProgress) GetChildDomains() []string {
	if x != nil {
		return x.ChildDomains
	}
	return nil
}

func (x *ScreeningProgress) GetResumeState() StateKind {
	if x != nil {
		return x.ResumeState
	}
	return StateKind_STATE_UNSPECIFIED
}

func (x *ScreeningProgress) GetConsentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConsentAt
	}
	return nil
}

func (x *ScreeningProgress) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ScreeningProgress) GetAdultDomainIdx() int32 {
	if x != nil {
		return x.AdultDomainIdx
	}
	return 0
}

func (x *ScreeningProgress) GetChildDomainIdx() int32 {
	if x != nil {
		return x.ChildDomainIdx
	}
	return 0
}

// ScreeningResult mirrors state.ScreeningResult — the last completed run:
// scores + applied thresholds + context facts, never per-question answers.
type ScreeningResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TakenAt          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	AsrsASignificant int32                  `protobuf:"varint,2,opt,name=asrs_a_significant,json=asrsASignificant,proto3" json:"asrs_a_significant,omitempty"` // 0..6
	AsrsAThreshold   int32                  `protobuf:"varint,3,opt,name=asrs_a_threshold,json=asrsAThreshold,proto3" json:"asrs_a_threshold,omitempty"`       // applied threshold (4)
	AsrsAPositive    bool                   `protobuf:"varint,4,opt,name=asrs_a_positive,json=asrsAPositive,proto3" json:"asrs_a_positive,omitempty"`
	AsrsBSignificant int32                  `protobuf:"varint,5,opt,name=asrs_b_significant,json=asrsBSignificant,proto3" json:"asrs_b_significant,omitempty"` // 0..12, no threshold by design
	WursScore        int32                  `protobuf:"varint,6,opt,name=wurs_score,json=wursScore,proto3" json:"wurs_score,omitempty"`                        // 0..100
	WursCutoff       int32                  `protobuf:"varint,7,opt,name=wurs_cutoff,json=wursCutoff,proto3" json:"wurs_cutoff,omitempty"`                     // applied cutoff (46)
	WursPositive     bool                   `protobuf:"varint,8,opt,name=wurs_positive,json=wursPositive,proto3" json:"wurs_positive,omitempty"`
	OnsetChildhood   bool                   `protobuf:"varint,9,opt,name=onset_childhood,json=onsetChildhood,proto3" json:"onset_childhood,omitempty"`
	OnsetAge         int32                  `protobuf:"varint,10,opt,name=onset_age,json=onsetAge,proto3" json:"onset_age,omitempty"` // 0 when onset_childhood
	AdultDomains     []string               `protobuf:"bytes,11,rep,name=adult_domains,json=adultDomains,proto3" json:"adult_domains,omitempty"`
	ChildDomains     []string               `protobuf:"bytes,12,rep,name=child_domains,json=childDomains,proto3" json:"child_domains,omitempty"`
	Verdict          string                 `protobuf:"bytes,13,opt,name=verdict,proto3" json:"verdict,omitempty"`                // consistent | partial | not_consistent
	GapHint          string                 `protobuf:"bytes,14,opt,name=gap_hint,json=gapHint,proto3" json:"gap_hint,omitempty"` // gap-hint key when partial
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScreeningResult) Reset() {
	*x = ScreeningResult{}
	mi := &file_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreeningResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreeningResult) ProtoMessage() {}

func (x *ScreeningResult) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreeningResult.ProtoReflect.Descriptor instead.
func (*ScreeningResult) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

func (x *ScreeningResult) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *ScreeningResult) GetAsrsASignificant() int32 {
	if x != nil {
		return x.AsrsASignificant
	}
	return 0
}

func (x *ScreeningResult) GetAsrsAThreshold() int32 {
	if x != nil {
		return x.AsrsAThreshold
	}
	return 0
}

func (x *ScreeningResult) GetAsrsAPositive() bool {
	if x != nil {
		return x.AsrsAPositive
	}
	return false
}

func (x *ScreeningResult) GetAsrsBSignificant() int32 {
	if x != nil {
		return x.AsrsBSignificant
	}
	return 0
}

func (x *ScreeningResult) GetWursScore() int32 {
	if x != nil {
		return x.WursScore
	}
	return 0
}

func (x *ScreeningResult) GetWursCutoff() int32 {
	if x != nil {
		return x.WursCutoff
	}
	return 0
}

func (x *ScreeningResult) GetWursPositive() bool {
	if x != nil {
		return x.WursPositive
	}
	return false
}

func (x *ScreeningResult) GetOnsetChildhood() bool {
	if x != nil {
		return x.OnsetChildhood
	}
	return false
}

func (x *ScreeningResult) GetOnsetAge() int32 {
	if x != nil {
		return x.OnsetAge
	}
	return 0
}

func (x *ScreeningResult) GetAdultDomains() []string {
	if x != nil {
		return x.AdultDomains
	}
	return nil
}

func (x *ScreeningResult) GetChildDomains() []string {
	if x != nil {
		return x.ChildDomains
	}
	return nil
}

func (x *ScreeningResult) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *ScreeningResult) GetGapHint() string {
	if x != nil {
		return x.GapHint
	}
	return ""
}

// MoodProgress mirrors state.MoodProgress — the TRANSIENT unfinished run of
// one mood-module instrument (PHQ-9 in `mood`, WHO-5 in `who5`, GAD-7 in
// `gad7`; raw per-question answers live only here; wiped on completion /
// restart / abandon / delete).
type MoodProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []int32                `protobuf:"varint,1,rep,packed,name=answers,proto3" json:"answers,omitempty"`                                                    // append-only; index = id-1 (PHQ-9 index 9 = the functional item)
	ResumeState   StateKind              `protobuf:"varint,2,opt,name=resume_state,json=resumeState,proto3,enum=tgbase.state.v1.StateKind" json:"resume_state,omitempty"` // recorded escape position (PHQ-9 question/crisis/q10, WHO-5/GAD-7 question)
	ConsentAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=consent_at,json=consentAt,proto3" json:"consent_at,omitempty"`                                       // legacy (v1 per-run consent); module consent lives on UserData
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoodProgress) Reset() {
	*x = MoodProgress{}
	mi := &file_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoodProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoodProgress) ProtoMessage() {}

func (x *MoodProgress) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoodProgress.ProtoReflect.Descriptor instead.
func (*MoodProgress) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{3}
}

func (x *MoodProgress) GetAnswers() []int32 {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *MoodProgress) GetResumeState() StateKind {
	if x != nil {
		return x.ResumeState
	}
	return StateKind_STATE_UNSPECIFIED
}

func (x *MoodProgress) GetConsentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConsentAt
	}
	return nil
}

func (x *MoodProgress) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// MoodResult mirrors state.MoodResult — the last completed PHQ-9 run: total
// score + applied severity band + the item-9 flag + the answer to the
// functional (10th) item, never the per-question answers 1..9.
type MoodResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`                                // 0..27 (functional item NOT included)
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`                           // applied severity-band id
	Q9Positive    bool                   `protobuf:"varint,4,opt,name=q9_positive,json=q9Positive,proto3" json:"q9_positive,omitempty"`    // self-harm item answered > 0
	Q10Answered   bool                   `protobuf:"varint,5,opt,name=q10_answered,json=q10Answered,proto3" json:"q10_answered,omitempty"` // functional item was shown and answered
	Q10Answer     int32                  `protobuf:"varint,6,opt,name=q10_answer,json=q10Answer,proto3" json:"q10_answer,omitempty"`       // 0..3, meaningful only when q10_answered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoodResult) Reset() {
	*x = MoodResult{}
	mi := &file_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoodResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoodResult) ProtoMessage() {}

func (x *MoodResult) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoodResult.ProtoReflect.Descriptor instead.
func (*MoodResult) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{4}
}

func (x *MoodResult) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *MoodResult) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MoodResult) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *MoodResult) GetQ9Positive() bool {
	if x != nil {
		return x.Q9Positive
	}
	return false
}

func (x *MoodResult) GetQ10Answered() bool {
	if x != nil {
		return x.Q10Answered
	}
	return false
}

func (x *MoodResult) GetQ10Answer() int32 {
	if x != nil {
		return x.Q10Answer
	}
	return 0
}

// Who5Result mirrors state.Who5Result — the last completed WHO-5 quick check:
// the 0–100 score (raw 0–25 sum × 4) + the applied interpretation band.
type Who5Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"` // 0..100
	Band          string                 `protobuf:"bytes,3,opt,name=band,proto3" json:"band,omitempty"`    // ok | low | very_low
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Who5Result) Reset() {
	*x = Who5Result{}
	mi := &file_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Who5Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Who5Result) ProtoMessage() {}

func (x *Who5Result) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Who5Result.ProtoReflect.Descriptor instead.
func (*Who5Result) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{5}
}

func (x *Who5Result) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *Who5Result) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Who5Result) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

// Gad7Result mirrors state.Gad7Result — the last completed GAD-7 run: total
// score + applied severity band, never per-question answers.
type Gad7Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`      // 0..21
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // minimal | mild | moderate | severe
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gad7Result) Reset() {
	*x = Gad7Result{}
	mi := &file_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gad7Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gad7Result) ProtoMessage() {}

func (x *Gad7Result) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gad7Result.ProtoReflect.Descriptor instead.
func (*Gad7Result) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{6}
}

func (x *Gad7Result) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *Gad7Result) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Gad7Result) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

// EatingProgress mirrors state.EatingProgress — the TRANSIENT unfinished run
// of one eating-track instrument (EDE-QS in `edeqs`, BES in `bes`, NIAS in
// `nias`; raw per-question answers live only here; wiped on completion /
// restart / abandon / delete). Answers hold the picked option's score, so a
// BES answer is the weight of the chosen statement, not its position.
type EatingProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []int32                `protobuf:"varint,1,rep,packed,name=answers,proto3" json:"answers,omitempty"`                                                    // append-only; index = item id - 1
	ResumeState   StateKind              `protobuf:"varint,2,opt,name=resume_state,json=resumeState,proto3,enum=tgbase.state.v1.StateKind" json:"resume_state,omitempty"` // recorded escape position (the run's question state)
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EatingProgress) Reset() {
	*x = EatingProgress{}
	mi := &file_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EatingProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EatingProgress) ProtoMessage() {}

func (x *EatingProgress) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EatingProgress.ProtoReflect.Descriptor instead.
func (*EatingProgress) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{7}
}

func (x *EatingProgress) GetAnswers() []int32 {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *EatingProgress) GetResumeState() StateKind {
	if x != nil {
		return x.ResumeState
	}
	return StateKind_STATE_UNSPECIFIED
}

func (x *EatingProgress) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// EdeqsResult mirrors state.EdeqsResult — the last completed EDE-QS run: the
// 0–36 sum, the applied screening cutoff and the verdict it produced.
type EdeqsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`       // 0..36
	Cutoff        int32                  `protobuf:"varint,3,opt,name=cutoff,proto3" json:"cutoff,omitempty"`     // applied cutoff (15)
	Positive      bool                   `protobuf:"varint,4,opt,name=positive,proto3" json:"positive,omitempty"` // score >= cutoff
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdeqsResult) Reset() {
	*x = EdeqsResult{}
	mi := &file_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdeqsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdeqsResult) ProtoMessage() {}

func (x *EdeqsResult) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdeqsResult.ProtoReflect.Descriptor instead.
func (*EdeqsResult) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{8}
}

func (x *EdeqsResult) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *EdeqsResult) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *EdeqsResult) GetCutoff() int32 {
	if x != nil {
		return x.Cutoff
	}
	return 0
}

func (x *EdeqsResult) GetPositive() bool {
	if x != nil {
		return x.Positive
	}
	return false
}

// BesResult mirrors state.BesResult — the last completed BES run: the 0–46
// sum and the applied severity band, never the per-item statements.
type BesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"` // 0..46
	Band          string                 `protobuf:"bytes,3,opt,name=band,proto3" json:"band,omitempty"`    // low | moderate | severe
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BesResult) Reset() {
	*x = BesResult{}
	mi := &file_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BesResult) ProtoMessage() {}

func (x *BesResult) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BesResult.ProtoReflect.Descriptor instead.
func (*BesResult) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{9}
}

func (x *BesResult) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *BesResult) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BesResult) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

// NiasResult mirrors state.NiasResult — the last completed NIAS run: the
// three subscale sums with the cutoffs that were applied to them. There is
// no NIAS total by design — the instrument is read per subscale.
type NiasResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TakenAt          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Picky            int32                  `protobuf:"varint,2,opt,name=picky,proto3" json:"picky,omitempty"`                                         // 0..15
	Appetite         int32                  `protobuf:"varint,3,opt,name=appetite,proto3" json:"appetite,omitempty"`                                   // 0..15
	Fear             int32                  `protobuf:"varint,4,opt,name=fear,proto3" json:"fear,omitempty"`                                           // 0..15
	PickyCutoff      int32                  `protobuf:"varint,5,opt,name=picky_cutoff,json=pickyCutoff,proto3" json:"picky_cutoff,omitempty"`          // applied cutoff (10)
	AppetiteCutoff   int32                  `protobuf:"varint,6,opt,name=appetite_cutoff,json=appetiteCutoff,proto3" json:"appetite_cutoff,omitempty"` // applied cutoff (9)
	FearCutoff       int32                  `protobuf:"varint,7,opt,name=fear_cutoff,json=fearCutoff,proto3" json:"fear_cutoff,omitempty"`             // applied cutoff (10)
	PickyPositive    bool                   `protobuf:"varint,8,opt,name=picky_positive,json=pickyPositive,proto3" json:"picky_positive,omitempty"`
	AppetitePositive bool                   `protobuf:"varint,9,opt,name=appetite_positive,json=appetitePositive,proto3" json:"appetite_positive,omitempty"`
	FearPositive     bool                   `protobuf:"varint,10,opt,name=fear_positive,json=fearPositive,proto3" json:"fear_positive,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NiasResult) Reset() {
	*x = NiasResult{}
	mi := &file_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NiasResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NiasResult) ProtoMessage() {}

func (x *NiasResult) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NiasResult.ProtoReflect.Descriptor instead.
func (*NiasResult) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{10}
}

func (x *NiasResult) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *NiasResult) GetPicky() int32 {
	if x != nil {
		return x.Picky
	}
	return 0
}

func (x *NiasResult) GetAppetite() int32 {
	if x != nil {
		return x.Appetite
	}
	return 0
}

func (x *NiasResult) GetFear() int32 {
	if x != nil {
		return x.Fear
	}
	return 0
}

func (x *NiasResult) GetPickyCutoff() int32 {
	if x != nil {
		return x.PickyCutoff
	}
	return 0
}

func (x *NiasResult) GetAppetiteCutoff() int32 {
	if x != nil {
		return x.AppetiteCutoff
	}
	return 0
}

func (x *NiasResult) GetFearCutoff() int32 {
	if x != nil {
		return x.FearCutoff
	}
	return 0
}

func (x *NiasResult) GetPickyPositive() bool {
	if x != nil {
		return x.PickyPositive
	}
	return false
}

func (x *NiasResult) GetAppetitePositive() bool {
	if x != nil {
		return x.AppetitePositive
	}
	return false
}

func (x *NiasResult) GetFearPositive() bool {
	if x != nil {
		return x.FearPositive
	}
	return false
}

// PushupProgram mirrors state.PushupProgram — the PERSISTENT state of the
// pushup track (absent = the track was never started). `base` is the single
// variable the generator reads: every rep count the user sees is derived
// from it by internal/screening, so no table of numbers is persisted here.
// The cosmetic level (1 + base/step) is derived on display, never stored.
type PushupProgram struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Variation         string                 `protobuf:"bytes,1,opt,name=variation,proto3" json:"variation,omitempty"`                                 // ladder rung id (wall … feet_up)
	Goal              string                 `protobuf:"bytes,2,opt,name=goal,proto3" json:"goal,omitempty"`                                           // reps | strength — branches the plateau logic for life
	Base              int32                  `protobuf:"varint,3,opt,name=base,proto3" json:"base,omitempty"`                                          // B, the last max-test result; >= min_base once tested
	WeekIdx           int32                  `protobuf:"varint,4,opt,name=week_idx,json=weekIdx,proto3" json:"week_idx,omitempty"`                     // completed weeks
	SessionInWeek     int32                  `protobuf:"varint,5,opt,name=session_in_week,json=sessionInWeek,proto3" json:"session_in_week,omitempty"` // 0..sessions_per_week-1, also the generator's day index
	WeekOutcomes      []string               `protobuf:"bytes,6,rep,name=week_outcomes,json=weekOutcomes,proto3" json:"week_outcomes,omitempty"`       // over|plan|short of the CURRENT week, <= sessions_per_week
	RepeatCount       int32                  `protobuf:"varint,7,opt,name=repeat_count,json=repeatCount,proto3" json:"repeat_count,omitempty"`         // consecutive repeated weeks (fork at repeat_fork_after)
	EffortAdj         float64                `protobuf:"fixed64,8,opt,name=effort_adj,json=effortAdj,proto3" json:"effort_adj,omitempty"`              // accumulated self-report factor, clamped by the content
	RestBonusSec      int32                  `protobuf:"varint,9,opt,name=rest_bonus_sec,json=restBonusSec,proto3" json:"rest_bonus_sec,omitempty"`    // the one-off "+30 s to everything"
	SessionsDone      int32                  `protobuf:"varint,10,opt,name=sessions_done,json=sessionsDone,proto3" json:"sessions_done,omitempty"`
	SessionsSinceTest int32                  `protobuf:"varint,11,opt,name=sessions_since_test,json=sessionsSinceTest,proto3" json:"sessions_since_test,omitempty"` // retest is due at retest_every_sessions
	TotalReps         int32                  `protobuf:"varint,12,opt,name=total_reps,json=totalReps,proto3" json:"total_reps,omitempty"`                           // lifetime volume (a never-decreasing metric)
	LastSessionAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_session_at,json=lastSessionAt,proto3" json:"last_session_at,omitempty"`
	NextDueAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=next_due_at,json=nextDueAt,proto3" json:"next_due_at,omitempty"`        // data-driven scan key of the "time to train" ping
	DuePingSent       bool                   `protobuf:"varint,15,opt,name=due_ping_sent,json=duePingSent,proto3" json:"due_ping_sent,omitempty"` // at most one due ping per due date
	StreakWeeks       int32                  `protobuf:"varint,16,opt,name=streak_weeks,json=streakWeeks,proto3" json:"streak_weeks,omitempty"`
	FreezeUsedAt      *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=freeze_used_at,json=freezeUsedAt,proto3" json:"freeze_used_at,omitempty"`
	StartedAt         *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	GateIdx           int32                  `protobuf:"varint,19,opt,name=gate_idx,json=gateIdx,proto3" json:"gate_idx,omitempty"`                     // safety-gate questions answered during setup
	StartStepDown     int32                  `protobuf:"varint,20,opt,name=start_step_down,json=startStepDown,proto3" json:"start_step_down,omitempty"` // rungs the gate asked to start below the picked one
	Deload            bool                   `protobuf:"varint,21,opt,name=deload,proto3" json:"deload,omitempty"`                                      // next session runs reduced (dropped retest / long pause)
	RetestPending     bool                   `protobuf:"varint,22,opt,name=retest_pending,json=retestPending,proto3" json:"retest_pending,omitempty"`   // a retest is owed before the next ordinary session
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PushupProgram) Reset() {
	*x = PushupProgram{}
	mi := &file_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushupProgram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushupProgram) ProtoMessage() {}

func (x *PushupProgram) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushupProgram.ProtoReflect.Descriptor instead.
func (*PushupProgram) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{11}
}

func (x *PushupProgram) GetVariation() string {
	if x != nil {
		return x.Variation
	}
	return ""
}

func (x *PushupProgram) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *PushupProgram) GetBase() int32 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *PushupProgram) GetWeekIdx() int32 {
	if x != nil {
		return x.WeekIdx
	}
	return 0
}

func (x *PushupProgram) GetSessionInWeek() int32 {
	if x != nil {
		return x.SessionInWeek
	}
	return 0
}

func (x *PushupProgram) GetWeekOutcomes() []string {
	if x != nil {
		return x.WeekOutcomes
	}
	return nil
}

func (x *PushupProgram) GetRepeatCount() int32 {
	if x != nil {
		return x.RepeatCount
	}
	return 0
}

func (x *PushupProgram) GetEffortAdj() float64 {
	if x != nil {
		return x.EffortAdj
	}
	return 0
}

func (x *PushupProgram) GetRestBonusSec() int32 {
	if x != nil {
		return x.RestBonusSec
	}
	return 0
}

func (x *PushupProgram) GetSessionsDone() int32 {
	if x != nil {
		return x.SessionsDone
	}
	return 0
}

func (x *PushupProgram) GetSessionsSinceTest() int32 {
	if x != nil {
		return x.SessionsSinceTest
	}
	return 0
}

func (x *PushupProgram) GetTotalReps() int32 {
	if x != nil {
		return x.TotalReps
	}
	return 0
}

func (x *PushupProgram) GetLastSessionAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSessionAt
	}
	return nil
}

func (x *PushupProgram) GetNextDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextDueAt
	}
	return nil
}

func (x *PushupProgram) GetDuePingSent() bool {
	if x != nil {
		return x.DuePingSent
	}
	return false
}

func (x *PushupProgram) GetStreakWeeks() int32 {
	if x != nil {
		return x.StreakWeeks
	}
	return 0
}

func (x *PushupProgram) GetFreezeUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FreezeUsedAt
	}
	return nil
}

func (x *PushupProgram) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PushupProgram) GetGateIdx() int32 {
	if x != nil {
		return x.GateIdx
	}
	return 0
}

func (x *PushupProgram) GetStartStepDown() int32 {
	if x != nil {
		return x.StartStepDown
	}
	return 0
}

func (x *PushupProgram) GetDeload() bool {
	if x != nil {
		return x.Deload
	}
	return false
}

func (x *PushupProgram) GetRetestPending() bool {
	if x != nil {
		return x.RetestPending
	}
	return false
}

// PushupSession mirrors state.PushupSession — the TRANSIENT unfinished
// session (absent when none). `targets` is variable-length (4..7) because
// the set count grows with the base, and its LAST element is the floor of
// the open set, which is why there are no fixed per-set fields.
type PushupSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`                                                                   // workout | test | retest
	DayIdx        int32                  `protobuf:"varint,2,opt,name=day_idx,json=dayIdx,proto3" json:"day_idx,omitempty"`                                                // 0..sessions_per_week-1
	Targets       []int32                `protobuf:"varint,3,rep,packed,name=targets,proto3" json:"targets,omitempty"`                                                     // fixed sets + the open set's floor (last)
	OpenFloor     int32                  `protobuf:"varint,4,opt,name=open_floor,json=openFloor,proto3" json:"open_floor,omitempty"`                                       // == last element of targets, kept for readability
	Actual        []int32                `protobuf:"varint,5,rep,packed,name=actual,proto3" json:"actual,omitempty"`                                                       // append-only, index-aligned with targets
	Idx           int32                  `protobuf:"varint,6,opt,name=idx,proto3" json:"idx,omitempty"`                                                                    // cursor: the set being performed
	RestSec       int32                  `protobuf:"varint,7,opt,name=rest_sec,json=restSec,proto3" json:"rest_sec,omitempty"`                                             // rest planned between sets of THIS session
	RestUntil     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=rest_until,json=restUntil,proto3" json:"rest_until,omitempty"`                                        // scan key of the rest-over ping
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`                                        // session TTL is measured from here
	ResumeState   StateKind              `protobuf:"varint,10,opt,name=resume_state,json=resumeState,proto3,enum=tgbase.state.v1.StateKind" json:"resume_state,omitempty"` // recorded escape position (pu_set | pu_rest)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushupSession) Reset() {
	*x = PushupSession{}
	mi := &file_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushupSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushupSession) ProtoMessage() {}

func (x *PushupSession) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushupSession.ProtoReflect.Descriptor instead.
func (*PushupSession) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{12}
}

func (x *PushupSession) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PushupSession) GetDayIdx() int32 {
	if x != nil {
		return x.DayIdx
	}
	return 0
}

func (x *PushupSession) GetTargets() []int32 {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *PushupSession) GetOpenFloor() int32 {
	if x != nil {
		return x.OpenFloor
	}
	return 0
}

func (x *PushupSession) GetActual() []int32 {
	if x != nil {
		return x.Actual
	}
	return nil
}

func (x *PushupSession) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *PushupSession) GetRestSec() int32 {
	if x != nil {
		return x.RestSec
	}
	return 0
}

func (x *PushupSession) GetRestUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.RestUntil
	}
	return nil
}

func (x *PushupSession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PushupSession) GetResumeState() StateKind {
	if x != nil {
		return x.ResumeState
	}
	return StateKind_STATE_UNSPECIFIED
}

// PushupTest mirrors state.PushupTest — the last COMPLETED max test. Kept
// apart from the program exactly like ScreeningResult is kept apart from
// ScreeningProgress: the test is a reproducible measurement, the program is
// the mutable load built on top of it.
type PushupTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Variation     string                 `protobuf:"bytes,2,opt,name=variation,proto3" json:"variation,omitempty"` // the rung the test was taken on
	Reps          int32                  `protobuf:"varint,3,opt,name=reps,proto3" json:"reps,omitempty"`
	Capped        bool                   `protobuf:"varint,4,opt,name=capped,proto3" json:"capped,omitempty"` // hit the test ceiling → offer a harder rung
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`  // initial | retest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushupTest) Reset() {
	*x = PushupTest{}
	mi := &file_state_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushupTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushupTest) ProtoMessage() {}

func (x *PushupTest) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushupTest.ProtoReflect.Descriptor instead.
func (*PushupTest) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{13}
}

func (x *PushupTest) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *PushupTest) GetVariation() string {
	if x != nil {
		return x.Variation
	}
	return ""
}

func (x *PushupTest) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *PushupTest) GetCapped() bool {
	if x != nil {
		return x.Capped
	}
	return false
}

func (x *PushupTest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// PushupSessionLog mirrors state.PushupSessionLog — one finished session in
// the history ring. Numbers only, never free text; the ring is capped
// (history_cap) because this is the only track that keeps a history rather
// than just the last result.
type PushupSessionLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	DayIdx        int32                  `protobuf:"varint,2,opt,name=day_idx,json=dayIdx,proto3" json:"day_idx,omitempty"`
	Sets          []int32                `protobuf:"varint,3,rep,packed,name=sets,proto3" json:"sets,omitempty"` // what was actually done, per set
	Planned       int32                  `protobuf:"varint,4,opt,name=planned,proto3" json:"planned,omitempty"`  // planned volume (fixed sets + open floor)
	Done          int32                  `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`        // actual volume
	OpenTarget    int32                  `protobuf:"varint,6,opt,name=open_target,json=openTarget,proto3" json:"open_target,omitempty"`
	OpenActual    int32                  `protobuf:"varint,7,opt,name=open_actual,json=openActual,proto3" json:"open_actual,omitempty"`
	Outcome       string                 `protobuf:"bytes,8,opt,name=outcome,proto3" json:"outcome,omitempty"` // over | plan | short
	Effort        string                 `protobuf:"bytes,9,opt,name=effort,proto3" json:"effort,omitempty"`   // hard | ok | easy
	Base          int32                  `protobuf:"varint,10,opt,name=base,proto3" json:"base,omitempty"`     // the base this session was generated from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushupSessionLog) Reset() {
	*x = PushupSessionLog{}
	mi := &file_state_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushupSessionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushupSessionLog) ProtoMessage() {}

func (x *PushupSessionLog) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushupSessionLog.ProtoReflect.Descriptor instead.
func (*PushupSessionLog) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{14}
}

func (x *PushupSessionLog) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *PushupSessionLog) GetDayIdx() int32 {
	if x != nil {
		return x.DayIdx
	}
	return 0
}

func (x *PushupSessionLog) GetSets() []int32 {
	if x != nil {
		return x.Sets
	}
	return nil
}

func (x *PushupSessionLog) GetPlanned() int32 {
	if x != nil {
		return x.Planned
	}
	return 0
}

func (x *PushupSessionLog) GetDone() int32 {
	if x != nil {
		return x.Done
	}
	return 0
}

func (x *PushupSessionLog) GetOpenTarget() int32 {
	if x != nil {
		return x.OpenTarget
	}
	return 0
}

func (x *PushupSessionLog) GetOpenActual() int32 {
	if x != nil {
		return x.OpenActual
	}
	return 0
}

func (x *PushupSessionLog) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *PushupSessionLog) GetEffort() string {
	if x != nil {
		return x.Effort
	}
	return ""
}

func (x *PushupSessionLog) GetBase() int32 {
	if x != nil {
		return x.Base
	}
	return 0
}

type UserData struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	State           StateKind                   `protobuf:"varint,1,opt,name=state,proto3,enum=tgbase.state.v1.StateKind" json:"state,omitempty"`
	DefecationState DefecationKind              `protobuf:"varint,2,opt,name=defecation_state,json=defecationState,proto3,enum=tgbase.state.v1.DefecationKind" json:"defecation_state,omitempty"`
	CurrentProduct  string                      `protobuf:"bytes,3,opt,name=current_product,json=currentProduct,proto3" json:"current_product,omitempty"`
	CurrentStage    pb.Stage                    `protobuf:"varint,4,opt,name=current_stage,json=currentStage,proto3,enum=tgbase.products.v1.Stage" json:"current_stage,omitempty"`
	StageStartedAt  *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=stage_started_at,json=stageStartedAt,proto3" json:"stage_started_at,omitempty"`
	CheckinAsked    bool                        `protobuf:"varint,6,opt,name=checkin_asked,json=checkinAsked,proto3" json:"checkin_asked,omitempty"`
	OfferedProducts []string                    `protobuf:"bytes,7,rep,name=offered_products,json=offeredProducts,proto3" json:"offered_products,omitempty"`
	Products        map[string]*ProductProgress `protobuf:"bytes,8,rep,name=products,proto3" json:"products,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ChatId          int64                       `protobuf:"varint,9,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	EnteredAt       *timestamppb.Timestamp      `protobuf:"bytes,10,opt,name=entered_at,json=enteredAt,proto3" json:"entered_at,omitempty"`
	ReminderSent    bool                        `protobuf:"varint,11,opt,name=reminder_sent,json=reminderSent,proto3" json:"reminder_sent,omitempty"`
	Locale          string                      `protobuf:"bytes,12,opt,name=locale,proto3" json:"locale,omitempty"`
	Screening       *ScreeningProgress          `protobuf:"bytes,13,opt,name=screening,proto3" json:"screening,omitempty"`
	ScreeningResult *ScreeningResult            `protobuf:"bytes,14,opt,name=screening_result,json=screeningResult,proto3" json:"screening_result,omitempty"`
	ReturnState     StateKind                   `protobuf:"varint,15,opt,name=return_state,json=returnState,proto3,enum=tgbase.state.v1.StateKind" json:"return_state,omitempty"`
	Mood            *MoodProgress               `protobuf:"bytes,16,opt,name=mood,proto3" json:"mood,omitempty"`
	MoodResult      *MoodResult                 `protobuf:"bytes,17,opt,name=mood_result,json=moodResult,proto3" json:"mood_result,omitempty"`
	// Mood module v2: one consent for the whole module (wiped by /mood_delete),
	// per-instrument transient runs and last completed results.
	MoodConsentAt *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=mood_consent_at,json=moodConsentAt,proto3" json:"mood_consent_at,omitempty"`
	Who5          *MoodProgress          `protobuf:"bytes,19,opt,name=who5,proto3" json:"who5,omitempty"`
	Gad7          *MoodProgress          `protobuf:"bytes,20,opt,name=gad7,proto3" json:"gad7,omitempty"`
	Who5Result    *Who5Result            `protobuf:"bytes,21,opt,name=who5_result,json=who5Result,proto3" json:"who5_result,omitempty"`
	Gad7Result    *Gad7Result            `protobuf:"bytes,22,opt,name=gad7_result,json=gad7Result,proto3" json:"gad7_result,omitempty"`
	// Eating track (EDE-QS + BES + NIAS): one consent for the whole track
	// (wiped by /food_delete), per-instrument transient runs and last
	// completed results. No combined index — same rule as the other tracks.
	EatConsentAt *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=eat_consent_at,json=eatConsentAt,proto3" json:"eat_consent_at,omitempty"`
	Edeqs        *EatingProgress        `protobuf:"bytes,24,opt,name=edeqs,proto3" json:"edeqs,omitempty"`
	EdeqsResult  *EdeqsResult           `protobuf:"bytes,25,opt,name=edeqs_result,json=edeqsResult,proto3" json:"edeqs_result,omitempty"`
	Bes          *EatingProgress        `protobuf:"bytes,26,opt,name=bes,proto3" json:"bes,omitempty"`
	BesResult    *BesResult             `protobuf:"bytes,27,opt,name=bes_result,json=besResult,proto3" json:"bes_result,omitempty"`
	Nias         *EatingProgress        `protobuf:"bytes,28,opt,name=nias,proto3" json:"nias,omitempty"`
	NiasResult   *NiasResult            `protobuf:"bytes,29,opt,name=nias_result,json=niasResult,proto3" json:"nias_result,omitempty"`
	// Pushup track: one consent for the whole track (wiped by /pushups_delete),
	// the persistent program, the transient session, the last max test and the
	// capped history ring. This is the first track that persists a program and
	// a history instead of a single last result.
	PuConsentAt   *timestamppb.Timestamp `protobuf:"bytes,30,opt,name=pu_consent_at,json=puConsentAt,proto3" json:"pu_consent_at,omitempty"`
	Pushups       *PushupProgram         `protobuf:"bytes,31,opt,name=pushups,proto3" json:"pushups,omitempty"`
	PuSession     *PushupSession         `protobuf:"bytes,32,opt,name=pu_session,json=puSession,proto3" json:"pu_session,omitempty"`
	PuTest        *PushupTest            `protobuf:"bytes,33,opt,name=pu_test,json=puTest,proto3" json:"pu_test,omitempty"`
	PuHistory     []*PushupSessionLog    `protobuf:"bytes,34,rep,name=pu_history,json=puHistory,proto3" json:"pu_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_state_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{15}
}

func (x *UserData) GetState() StateKind {
	if x != nil {
		return x.State
	}
	return StateKind_STATE_UNSPECIFIED
}

func (x *UserData) GetDefecationState() DefecationKind {
	if x != nil {
		return x.DefecationState
	}
	return DefecationKind_DEFECATION_UNSPECIFIED
}

func (x *UserData) GetCurrentProduct() string {
	if x != nil {
		return x.CurrentProduct
	}
	return ""
}

func (x *UserData) GetCurrentStage() pb.Stage {
	if x != nil {
		return x.CurrentStage
	}
	return pb.Stage(0)
}

func (x *UserData) GetStageStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StageStartedAt
	}
	return nil
}

func (x *UserData) GetCheckinAsked() bool {
	if x != nil {
		return x.CheckinAsked
	}
	return false
}

func (x *UserData) GetOfferedProducts() []string {
	if x != nil {
		return x.OfferedProducts
	}
	return nil
}

func (x *UserData) GetProducts() map[string]*ProductProgress {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *UserData) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *UserData) GetEnteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnteredAt
	}
	return nil
}

func (x *UserData) GetReminderSent() bool {
	if x != nil {
		return x.ReminderSent
	}
	return false
}

func (x *UserData) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *UserData) GetScreening() *ScreeningProgress {
	if x != nil {
		return x.Screening
	}
	return nil
}

func (x *UserData) GetScreeningResult() *ScreeningResult {
	if x != nil {
		return x.ScreeningResult
	}
	return nil
}

func (x *UserData) GetReturnState() StateKind {
	if x != nil {
		return x.ReturnState
	}
	return StateKind_STATE_UNSPECIFIED
}

func (x *UserData) GetMood() *MoodProgress {
	if x != nil {
		return x.Mood
	}
	return nil
}

func (x *UserData) GetMoodResult() *MoodResult {
	if x != nil {
		return x.MoodResult
	}
	return nil
}

func (x *UserData) GetMoodConsentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MoodConsentAt
	}
	return nil
}

func (x *UserData) GetWho5() *MoodProgress {
	if x != nil {
		return x.Who5
	}
	return nil
}

func (x *UserData) GetGad7() *MoodProgress {
	if x != nil {
		return x.Gad7
	}
	return nil
}

func (x *UserData) GetWho5Result() *Who5Result {
	if x != nil {
		return x.Who5Result
	}
	return nil
}

func (x *UserData) GetGad7Result() *Gad7Result {
	if x != nil {
		return x.Gad7Result
	}
	return nil
}

func (x *UserData) GetEatConsentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EatConsentAt
	}
	return nil
}

func (x *UserData) GetEdeqs() *EatingProgress {
	if x != nil {
		return x.Edeqs
	}
	return nil
}

func (x *UserData) GetEdeqsResult() *EdeqsResult {
	if x != nil {
		return x.EdeqsResult
	}
	return nil
}

func (x *UserData) GetBes() *EatingProgress {
	if x != nil {
		return x.Bes
	}
	return nil
}

func (x *UserData) GetBesResult() *BesResult {
	if x != nil {
		return x.BesResult
	}
	return nil
}

func (x *UserData) GetNias() *EatingProgress {
	if x != nil {
		return x.Nias
	}
	return nil
}

func (x *UserData) GetNiasResult() *NiasResult {
	if x != nil {
		return x.NiasResult
	}
	return nil
}

func (x *UserData) GetPuConsentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PuConsentAt
	}
	return nil
}

func (x *UserData) GetPushups() *PushupProgram {
	if x != nil {
		return x.Pushups
	}
	return nil
}

func (x *UserData) GetPuSession() *PushupSession {
	if x != nil {
		return x.PuSession
	}
	return nil
}

func (x *UserData) GetPuTest() *PushupTest {
	if x != nil {
		return x.PuTest
	}
	return nil
}

func (x *UserData) GetPuHistory() []*PushupSessionLog {
	if x != nil {
		return x.PuHistory
	}
	return nil
}

type UserMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         map[int64]*UserData    `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMap) Reset() {
	*x = UserMap{}
	mi := &file_state_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMap) ProtoMessage() {}

func (x *UserMap) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMap.ProtoReflect.Descriptor instead.
func (*UserMap) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{16}
}

func (x *UserMap) GetUsers() map[int64]*UserData {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\x0ftgbase.state.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0eproducts.proto\"\x9e\x01\n" +
	"\x0fProductProgress\x128\n" +
	"\n" +
	"last_stage\x18\x01 \x01(\x0e2\x19.tgbase.products.v1.StageR\tlastStage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9c\x04\n" +
	"\x11ScreeningProgress\x12!\n" +
	"\fasrs_answers\x18\x01 \x03(\x05R\vasrsAnswers\x12!\n" +
	"\fwurs_answers\x18\x02 \x03(\x05R\vwursAnswers\x12\x1b\n" +
	"\twurs_form\x18\x03 \x01(\tR\bwursForm\x12$\n" +
	"\vonset_child\x18\x04 \x01(\bH\x00R\n" +
	"onsetChild\x88\x01\x01\x12\x1b\n" +
	"\tonset_age\x18\x05 \x01(\x05R\bonsetAge\x12#\n" +
	"\radult_domains\x18\x06 \x03(\tR\fadultDomains\x12#\n" +
	"\rchild_domains\x18\a \x03(\tR\fchildDomains\x12=\n" +
	"\fresume_state\x18\b \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\vresumeState\x129\n" +
	"\n" +
	"consent_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tconsentAt\x129\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12(\n" +
	"\x10adult_domain_idx\x18\v \x01(\x05R\x0eadultDomainIdx\x12(\n" +
	"\x10child_domain_idx\x18\f \x01(\x05R\x0echildDomainIdxB\x0e\n" +
	"\f_onset_child\"\xa0\x04\n" +
	"\x0fScreeningResult\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12,\n" +
	"\x12asrs_a_significant\x18\x02 \x01(\x05R\x10asrsASignificant\x12(\n" +
	"\x10asrs_a_threshold\x18\x03 \x01(\x05R\x0easrsAThreshold\x12&\n" +
	"\x0fasrs_a_positive\x18\x04 \x01(\bR\rasrsAPositive\x12,\n" +
	"\x12asrs_b_significant\x18\x05 \x01(\x05R\x10asrsBSignificant\x12\x1d\n" +
	"\n" +
	"wurs_score\x18\x06 \x01(\x05R\twursScore\x12\x1f\n" +
	"\vwurs_cutoff\x18\a \x01(\x05R\n" +
	"wursCutoff\x12#\n" +
	"\rwurs_positive\x18\b \x01(\bR\fwursPositive\x12'\n" +
	"\x0fonset_childhood\x18\t \x01(\bR\x0eonsetChildhood\x12\x1b\n" +
	"\tonset_age\x18\n" +
	" \x01(\x05R\bonsetAge\x12#\n" +
	"\radult_domains\x18\v \x03(\tR\fadultDomains\x12#\n" +
	"\rchild_domains\x18\f \x03(\tR\fchildDomains\x12\x18\n" +
	"\averdict\x18\r \x01(\tR\averdict\x12\x19\n" +
	"\bgap_hint\x18\x0e \x01(\tR\agapHint\"\xdd\x01\n" +
	"\fMoodProgress\x12\x18\n" +
	"\aanswers\x18\x01 \x03(\x05R\aanswers\x12=\n" +
	"\fresume_state\x18\x02 \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\vresumeState\x129\n" +
	"\n" +
	"consent_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tconsentAt\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xd8\x01\n" +
	"\n" +
	"MoodResult\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1f\n" +
	"\vq9_positive\x18\x04 \x01(\bR\n" +
	"q9Positive\x12!\n" +
	"\fq10_answered\x18\x05 \x01(\bR\vq10Answered\x12\x1d\n" +
	"\n" +
	"q10_answer\x18\x06 \x01(\x05R\tq10Answer\"m\n" +
	"\n" +
	"Who5Result\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x12\n" +
	"\x04band\x18\x03 \x01(\tR\x04band\"u\n" +
	"\n" +
	"Gad7Result\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\"\xa4\x01\n" +
	"\x0eEatingProgress\x12\x18\n" +
	"\aanswers\x18\x01 \x03(\x05R\aanswers\x12=\n" +
	"\fresume_state\x18\x02 \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\vresumeState\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\x8e\x01\n" +
	"\vEdeqsResult\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x16\n" +
	"\x06cutoff\x18\x03 \x01(\x05R\x06cutoff\x12\x1a\n" +
	"\bpositive\x18\x04 \x01(\bR\bpositive\"l\n" +
	"\tBesResult\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x12\n" +
	"\x04band\x18\x03 \x01(\tR\x04band\"\xef\x02\n" +
	"\n" +
	"NiasResult\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x14\n" +
	"\x05picky\x18\x02 \x01(\x05R\x05picky\x12\x1a\n" +
	"\bappetite\x18\x03 \x01(\x05R\bappetite\x12\x12\n" +
	"\x04fear\x18\x04 \x01(\x05R\x04fear\x12!\n" +
	"\fpicky_cutoff\x18\x05 \x01(\x05R\vpickyCutoff\x12'\n" +
	"\x0fappetite_cutoff\x18\x06 \x01(\x05R\x0eappetiteCutoff\x12\x1f\n" +
	"\vfear_cutoff\x18\a \x01(\x05R\n" +
	"fearCutoff\x12%\n" +
	"\x0epicky_positive\x18\b \x01(\bR\rpickyPositive\x12+\n" +
	"\x11appetite_positive\x18\t \x01(\bR\x10appetitePositive\x12#\n" +
	"\rfear_positive\x18\n" +
	" \x01(\bR\ffearPositive\"\xdf\x06\n" +
	"\rPushupProgram\x12\x1c\n" +
	"\tvariation\x18\x01 \x01(\tR\tvariation\x12\x12\n" +
	"\x04goal\x18\x02 \x01(\tR\x04goal\x12\x12\n" +
	"\x04base\x18\x03 \x01(\x05R\x04base\x12\x19\n" +
	"\bweek_idx\x18\x04 \x01(\x05R\aweekIdx\x12&\n" +
	"\x0fsession_in_week\x18\x05 \x01(\x05R\rsessionInWeek\x12#\n" +
	"\rweek_outcomes\x18\x06 \x03(\tR\fweekOutcomes\x12!\n" +
	"\frepeat_count\x18\a \x01(\x05R\vrepeatCount\x12\x1d\n" +
	"\n" +
	"effort_adj\x18\b \x01(\x01R\teffortAdj\x12$\n" +
	"\x0erest_bonus_sec\x18\t \x01(\x05R\frestBonusSec\x12#\n" +
	"\rsessions_done\x18\n" +
	" \x01(\x05R\fsessionsDone\x12.\n" +
	"\x13sessions_since_test\x18\v \x01(\x05R\x11sessionsSinceTest\x12\x1d\n" +
	"\n" +
	"total_reps\x18\f \x01(\x05R\ttotalReps\x12B\n" +
	"\x0flast_session_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\rlastSessionAt\x12:\n" +
	"\vnext_due_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tnextDueAt\x12\"\n" +
	"\rdue_ping_sent\x18\x0f \x01(\bR\vduePingSent\x12!\n" +
	"\fstreak_weeks\x18\x10 \x01(\x05R\vstreakWeeks\x12@\n" +
	"\x0efreeze_used_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\ffreezeUsedAt\x129\n" +
	"\n" +
	"started_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x19\n" +
	"\bgate_idx\x18\x13 \x01(\x05R\agateIdx\x12&\n" +
	"\x0fstart_step_down\x18\x14 \x01(\x05R\rstartStepDown\x12\x16\n" +
	"\x06deload\x18\x15 \x01(\bR\x06deload\x12%\n" +
	"\x0eretest_pending\x18\x16 \x01(\bR\rretestPending\"\xef\x02\n" +
	"\rPushupSession\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x17\n" +
	"\aday_idx\x18\x02 \x01(\x05R\x06dayIdx\x12\x18\n" +
	"\atargets\x18\x03 \x03(\x05R\atargets\x12\x1d\n" +
	"\n" +
	"open_floor\x18\x04 \x01(\x05R\topenFloor\x12\x16\n" +
	"\x06actual\x18\x05 \x03(\x05R\x06actual\x12\x10\n" +
	"\x03idx\x18\x06 \x01(\x05R\x03idx\x12\x19\n" +
	"\brest_sec\x18\a \x01(\x05R\arestSec\x129\n" +
	"\n" +
	"rest_until\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\trestUntil\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fresume_state\x18\n" +
	" \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\vresumeState\"\xa5\x01\n" +
	"\n" +
	"PushupTest\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x1c\n" +
	"\tvariation\x18\x02 \x01(\tR\tvariation\x12\x12\n" +
	"\x04reps\x18\x03 \x01(\x05R\x04reps\x12\x16\n" +
	"\x06capped\x18\x04 \x01(\bR\x06capped\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\xa5\x02\n" +
	"\x10PushupSessionLog\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x17\n" +
	"\aday_idx\x18\x02 \x01(\x05R\x06dayIdx\x12\x12\n" +
	"\x04sets\x18\x03 \x03(\x05R\x04sets\x12\x18\n" +
	"\aplanned\x18\x04 \x01(\x05R\aplanned\x12\x12\n" +
	"\x04done\x18\x05 \x01(\x05R\x04done\x12\x1f\n" +
	"\vopen_target\x18\x06 \x01(\x05R\n" +
	"openTarget\x12\x1f\n" +
	"\vopen_actual\x18\a \x01(\x05R\n" +
	"openActual\x12\x18\n" +
	"\aoutcome\x18\b \x01(\tR\aoutcome\x12\x16\n" +
	"\x06effort\x18\t \x01(\tR\x06effort\x12\x12\n" +
	"\x04base\x18\n" +
	" \x01(\x05R\x04base\"\xed\x0f\n" +
	"\bUserData\x120\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\x05state\x12J\n" +
	"\x10defecation_state\x18\x02 \x01(\x0e2\x1f.tgbase.state.v1.DefecationKindR\x0fdefecationState\x12'\n" +
	"\x0fcurrent_product\x18\x03 \x01(\tR\x0ecurrentProduct\x12>\n" +
	"\rcurrent_stage\x18\x04 \x01(\x0e2\x19.tgbase.products.v1.StageR\fcurrentStage\x12D\n" +
	"\x10stage_started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0estageStartedAt\x12#\n" +
	"\rcheckin_asked\x18\x06 \x01(\bR\fcheckinAsked\x12)\n" +
	"\x10offered_products\x18\a \x03(\tR\x0fofferedProducts\x12C\n" +
	"\bproducts\x18\b \x03(\v2'.tgbase.state.v1.UserData.ProductsEntryR\bproducts\x12\x17\n" +
	"\achat_id\x18\t \x01(\x03R\x06chatId\x129\n" +
	"\n" +
	"entered_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tenteredAt\x12#\n" +
	"\rreminder_sent\x18\v \x01(\bR\freminderSent\x12\x16\n" +
	"\x06locale\x18\f \x01(\tR\x06locale\x12@\n" +
	"\tscreening\x18\r \x01(\v2\".tgbase.state.v1.ScreeningProgressR\tscreening\x12K\n" +
	"\x10screening_result\x18\x0e \x01(\v2 .tgbase.state.v1.ScreeningResultR\x0fscreeningResult\x12=\n" +
	"\freturn_state\x18\x0f \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\vreturnState\x121\n" +
	"\x04mood\x18\x10 \x01(\v2\x1d.tgbase.state.v1.MoodProgressR\x04mood\x12<\n" +
	"\vmood_result\x18\x11 \x01(\v2\x1b.tgbase.state.v1.MoodResultR\n" +
	"moodResult\x12B\n" +
	"\x0fmood_consent_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\rmoodConsentAt\x121\n" +
	"\x04who5\x18\x13 \x01(\v2\x1d.tgbase.state.v1.MoodProgressR\x04who5\x121\n" +
	"\x04gad7\x18\x14 \x01(\v2\x1d.tgbase.state.v1.MoodProgressR\x04gad7\x12<\n" +
	"\vwho5_result\x18\x15 \x01(\v2\x1b.tgbase.state.v1.Who5ResultR\n" +
	"who5Result\x12<\n" +
	"\vgad7_result\x18\x16 \x01(\v2\x1b.tgbase.state.v1.Gad7ResultR\n" +
	"gad7Result\x12@\n" +
	"\x0eeat_consent_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\featConsentAt\x125\n" +
	"\x05edeqs\x18\x18 \x01(\v2\x1f.tgbase.state.v1.EatingProgressR\x05edeqs\x12?\n" +
	"\fedeqs_result\x18\x19 \x01(\v2\x1c.tgbase.state.v1.EdeqsResultR\vedeqsResult\x121\n" +
	"\x03bes\x18\x1a \x01(\v2\x1f.tgbase.state.v1.EatingProgressR\x03bes\x129\n" +
	"\n" +
	"bes_result\x18\x1b \x01(\v2\x1a.tgbase.state.v1.BesResultR\tbesResult\x123\n" +
	"\x04nias\x18\x1c \x01(\v2\x1f.tgbase.state.v1.EatingProgressR\x04nias\x12<\n" +
	"\vnias_result\x18\x1d \x01(\v2\x1b.tgbase.state.v1.NiasResultR\n" +
	"niasResult\x12>\n" +
	"\rpu_consent_at\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\vpuConsentAt\x128\n" +
	"\apushups\x18\x1f \x01(\v2\x1e.tgbase.state.v1.PushupProgramR\apushups\x12=\n" +
	"\n" +
	"pu_session\x18  \x01(\v2\x1e.tgbase.state.v1.PushupSessionR\tpuSession\x124\n" +
	"\apu_test\x18! \x01(\v2\x1b.tgbase.state.v1.PushupTestR\x06puTest\x12@\n" +
	"\n" +
	"pu_history\x18\" \x03(\v2!.tgbase.state.v1.PushupSessionLogR\tpuHistory\x1a]\n" +
	"\rProductsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .tgbase.state.v1.ProductProgressR\x05value:\x028\x01\"\x99\x01\n" +
	"\aUserMap\x129\n" +
	"\x05users\x18\x01 \x03(\v2#.tgbase.state.v1.UserMap.UsersEntryR\x05users\x1aS\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.tgbase.state.v1.UserDataR\x05value:\x028\x01*\xea\n" +
	"\n" +
	"\tStateKind\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_IDLE\x10\x01\x12\x1d\n" +
	"\x19STATE_AWAITING_DEFECATION\x10\x02\x12!\n" +
	"\x1dSTATE_AWAITING_PRODUCT_CHOICE\x10\x03\x12 \n" +
	"\x1cSTATE_AWAITING_STAGE_CHECKIN\x10\x04\x12\x1f\n" +
	"\x1bSTATE_AWAITING_STAGE_CHOICE\x10\x05\x12\x1e\n" +
	"\x1aSTATE_AWAITING_MODE_CHOICE\x10\x06\x12\x15\n" +
	"\x11STATE_SCR_CONSENT\x10\a\x12\x13\n" +
	"\x0fSTATE_SCR_INTRO\x10\b\x12\x14\n" +
	"\x10STATE_SCR_ASRS_A\x10\t\x12\x19\n" +
	"\x15STATE_SCR_ASRS_A_GATE\x10\n" +
	"\x12\x14\n" +
	"\x10STATE_SCR_ASRS_B\x10\v\x12\x19\n" +
	"\x15STATE_SCR_ASRS_B_GATE\x10\f\x12\x17\n" +
	"\x13STATE_SCR_WURS_FORM\x10\r\x12\x12\n" +
	"\x0eSTATE_SCR_WURS\x10\x0e\x12\x17\n" +
	"\x13STATE_SCR_WURS_GATE\x10\x0f\x12\x13\n" +
	"\x0fSTATE_SCR_ONSET\x10\x10\x12\x17\n" +
	"\x13STATE_SCR_ONSET_AGE\x10\x11\x12\x1b\n" +
	"\x17STATE_SCR_DOMAINS_ADULT\x10\x12\x12\x1b\n" +
	"\x17STATE_SCR_DOMAINS_CHILD\x10\x13\x12\x16\n" +
	"\x12STATE_SCR_REFERRAL\x10\x14\x12\x14\n" +
	"\x10STATE_SCR_REPORT\x10\x15\x12\x1c\n" +
	"\x18STATE_SCR_DELETE_CONFIRM\x10\x16\x12#\n" +
	"\x1fSTATE_AWAITING_PRODUCT_CATEGORY\x10\x17\x12\x16\n" +
	"\x12STATE_MOOD_CONSENT\x10\x18\x12\x17\n" +
	"\x13STATE_MOOD_QUESTION\x10\x19\x12\x15\n" +
	"\x11STATE_MOOD_CRISIS\x10\x1a\x12\x15\n" +
	"\x11STATE_MOOD_REPORT\x10\x1b\x12\x1d\n" +
	"\x19STATE_MOOD_DELETE_CONFIRM\x10\x1c\x12\x13\n" +
	"\x0fSTATE_MOOD_MENU\x10\x1d\x12\x12\n" +
	"\x0eSTATE_MOOD_Q10\x10\x1e\x12\x1c\n" +
	"\x18STATE_MOOD_WHO5_QUESTION\x10\x1f\x12\x19\n" +
	"\x15STATE_MOOD_OFFER_PHQ9\x10 \x12\x1c\n" +
	"\x18STATE_MOOD_GAD7_QUESTION\x10!\x12\x19\n" +
	"\x15STATE_MOOD_OFFER_GAD7\x10\"\x12\x15\n" +
	"\x11STATE_EAT_CONSENT\x10#\x12\x12\n" +
	"\x0eSTATE_EAT_MENU\x10$\x12\x1c\n" +
	"\x18STATE_EAT_EDEQS_QUESTION\x10%\x12\x1a\n" +
	"\x16STATE_EAT_BES_QUESTION\x10&\x12\x1b\n" +
	"\x17STATE_EAT_NIAS_QUESTION\x10'\x12\x14\n" +
	"\x10STATE_EAT_REPORT\x10(\x12\x1c\n" +
	"\x18STATE_EAT_DELETE_CONFIRM\x10)\x12\x14\n" +
	"\x10STATE_PU_CONSENT\x10*\x12\x11\n" +
	"\rSTATE_PU_GATE\x10+\x12\x11\n" +
	"\rSTATE_PU_GOAL\x10,\x12\x16\n" +
	"\x12STATE_PU_VARIATION\x10-\x12\x11\n" +
	"\rSTATE_PU_TEST\x10.\x12\x11\n" +
	"\rSTATE_PU_MENU\x10/\x12\x10\n" +
	"\fSTATE_PU_SET\x100\x12\x11\n" +
	"\rSTATE_PU_REST\x101\x12\x13\n" +
	"\x0fSTATE_PU_EFFORT\x102\x12\x16\n" +
	"\x12STATE_PU_WEEK_FORK\x103\x12\x15\n" +
	"\x11STATE_PU_RED_CARD\x104\x12\x15\n" +
	"\x11STATE_PU_PROGRESS\x105\x12\x1b\n" +
	"\x17STATE_PU_DELETE_CONFIRM\x106*p\n" +
	"\x0eDefecationKind\x12\x1a\n" +
	"\x16DEFECATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DEFECATION_FLUID\x10\x01\x12\x15\n" +
	"\x11DEFECATION_NORMAL\x10\x02\x12\x15\n" +
	"\x11DEFECATION_ISSUES\x10\x03B2Z0github.com/padington/tgbase/internal/state/pb;pbb\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_state_proto_goTypes = []any{
	(StateKind)(0),                // 0: tgbase.state.v1.StateKind
	(DefecationKind)(0),           // 1: tgbase.state.v1.DefecationKind
	(*ProductProgress)(nil),       // 2: tgbase.state.v1.ProductProgress
	(*ScreeningProgress)(nil),     // 3: tgbase.state.v1.ScreeningProgress
	(*ScreeningResult)(nil),       // 4: tgbase.state.v1.ScreeningResult
	(*MoodProgress)(nil),          // 5: tgbase.state.v1.MoodProgress
	(*MoodResult)(nil),            // 6: tgbase.state.v1.MoodResult
	(*Who5Result)(nil),            // 7: tgbase.state.v1.Who5Result
	(*Gad7Result)(nil),            // 8: tgbase.state.v1.Gad7Result
	(*EatingProgress)(nil),        // 9: tgbase.state.v1.EatingProgress
	(*EdeqsResult)(nil),           // 10: tgbase.state.v1.EdeqsResult
	(*BesResult)(nil),             // 11: tgbase.state.v1.BesResult
	(*NiasResult)(nil),            // 12: tgbase.state.v1.NiasResult
	(*PushupProgram)(nil),         // 13: tgbase.state.v1.PushupProgram
	(*PushupSession)(nil),         // 14: tgbase.state.v1.PushupSession
	(*PushupTest)(nil),            // 15: tgbase.state.v1.PushupTest
	(*PushupSessionLog)(nil),      // 16: tgbase.state.v1.PushupSessionLog
	(*UserData)(nil),              // 17: tgbase.state.v1.UserData
	(*UserMap)(nil),               // 18: tgbase.state.v1.UserMap
	nil,                           // 19: tgbase.state.v1.UserData.ProductsEntry
	nil,                           // 20: tgbase.state.v1.UserMap.UsersEntry
	(pb.Stage)(0),                 // 21: tgbase.products.v1.Stage
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_state_proto_depIdxs = []int32{
	21, // 0: tgbase.state.v1.ProductProgress.last_stage:type_name -> tgbase.products.v1.Stage
	22, // 1: tgbase.state.v1.ProductProgress.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: tgbase.state.v1.ScreeningProgress.resume_state:type_name -> tgbase.state.v1.StateKind
	22, // 3: tgbase.state.v1.ScreeningProgress.consent_at:type_name -> google.protobuf.Timestamp
	22, // 4: tgbase.state.v1.ScreeningProgress.started_at:type_name -> google.protobuf.Timestamp
	22, // 5: tgbase.state.v1.ScreeningResult.taken_at:type_name -> google.protobuf.Timestamp
	0,  // 6: tgbase.state.v1.MoodProgress.resume_state:type_name -> tgbase.state.v1.StateKind
	22, // 7: tgbase.state.v1.MoodProgress.consent_at:type_name -> google.protobuf.Timestamp
	22, // 8: tgbase.state.v1.MoodProgress.started_at:type_name -> google.protobuf.Timestamp
	22, // 9: tgbase.state.v1.MoodResult.taken_at:type_name -> google.protobuf.Timestamp
	22, // 10: tgbase.state.v1.Who5Result.taken_at:type_name -> google.protobuf.Timestamp
	22, // 11: tgbase.state.v1.Gad7Result.taken_at:type_name -> google.protobuf.Timestamp
	0,  // 12: tgbase.state.v1.EatingProgress.resume_state:type_name -> tgbase.state.v1.StateKind
	22, // 13: tgbase.state.v1.EatingProgress.started_at:type_name -> google.protobuf.Timestamp
	22, // 14: tgbase.state.v1.EdeqsResult.taken_at:type_name -> google.protobuf.Timestamp
	22, // 15: tgbase.state.v1.BesResult.taken_at:type_name -> google.protobuf.Timestamp
	22, // 16: tgbase.state.v1.NiasResult.taken_at:type_name -> google.protobuf.Timestamp
	22, // 17: tgbase.state.v1.PushupProgram.last_session_at:type_name -> google.protobuf.Timestamp
	22, // 18: tgbase.state.v1.PushupProgram.next_due_at:type_name -> google.protobuf.Timestamp
	22, // 19: tgbase.state.v1.PushupProgram.freeze_used_at:type_name -> google.protobuf.Timestamp
	22, // 20: tgbase.state.v1.PushupProgram.started_at:type_name -> google.protobuf.Timestamp
	22, // 21: tgbase.state.v1.PushupSession.rest_until:type_name -> google.protobuf.Timestamp
	22, // 22: tgbase.state.v1.PushupSession.started_at:type_name -> google.protobuf.Timestamp
	0,  // 23: tgbase.state.v1.PushupSession.resume_state:type_name -> tgbase.state.v1.StateKind
	22, // 24: tgbase.state.v1.PushupTest.taken_at:type_name -> google.protobuf.Timestamp
	22, // 25: tgbase.state.v1.PushupSessionLog.date:type_name -> google.protobuf.Timestamp
	0,  // 26: tgbase.state.v1.UserData.state:type_name -> tgbase.state.v1.StateKind
	1,  // 27: tgbase.state.v1.UserData.defecation_state:type_name -> tgbase.state.v1.DefecationKind
	21, // 28: tgbase.state.v1.UserData.current_stage:type_name -> tgbase.products.v1.Stage
	22, // 29: tgbase.state.v1.UserData.stage_started_at:type_name -> google.protobuf.Timestamp
	19, // 30: tgbase.state.v1.UserData.products:type_name -> tgbase.state.v1.UserData.ProductsEntry
	22, // 31: tgbase.state.v1.UserData.entered_at:type_name -> google.protobuf.Timestamp
	3,  // 32: tgbase.state.v1.UserData.screening:type_name -> tgbase.state.v1.ScreeningProgress
	4,  // 33: tgbase.state.v1.UserData.screening_result:type_name -> tgbase.state.v1.ScreeningResult
	0,  // 34: tgbase.state.v1.UserData.return_state:type_name -> tgbase.state.v1.StateKind
	5,  // 35: tgbase.state.v1.UserData.mood:type_name -> tgbase.state.v1.MoodProgress
	6,  // 36: tgbase.state.v1.UserData.mood_result:type_name -> tgbase.state.v1.MoodResult
	22, // 37: tgbase.state.v1.UserData.mood_consent_at:type_name -> google.protobuf.Timestamp
	5,  // 38: tgbase.state.v1.UserData.who5:type_name -> tgbase.state.v1.MoodProgress
	5,  // 39: tgbase.state.v1.UserData.gad7:type_name -> tgbase.state.v1.MoodProgress
	7,  // 40: tgbase.state.v1.UserData.who5_result:type_name -> tgbase.state.v1.Who5Result
	8,  // 41: tgbase.state.v1.UserData.gad7_result:type_name -> tgbase.state.v1.Gad7Result
	22, // 42: tgbase.state.v1.UserData.eat_consent_at:type_name -> google.protobuf.Timestamp
	9,  // 43: tgbase.state.v1.UserData.edeqs:type_name -> tgbase.state.v1.EatingProgress
	10, // 44: tgbase.state.v1.UserData.edeqs_result:type_name -> tgbase.state.v1.EdeqsResult
	9,  // 45: tgbase.state.v1.UserData.bes:type_name -> tgbase.state.v1.EatingProgress
	11, // 46: tgbase.state.v1.UserData.bes_result:type_name -> tgbase.state.v1.BesResult
	9,  // 47: tgbase.state.v1.UserData.nias:type_name -> tgbase.state.v1.EatingProgress
	12, // 48: tgbase.state.v1.UserData.nias_result:type_name -> tgbase.state.v1.NiasResult
	22, // 49: tgbase.state.v1.UserData.pu_consent_at:type_name -> google.protobuf.Timestamp
	13, // 50: tgbase.state.v1.UserData.pushups:type_name -> tgbase.state.v1.PushupProgram
	14, // 51: tgbase.state.v1.UserData.pu_session:type_name -> tgbase.state.v1.PushupSession
	15, // 52: tgbase.state.v1.UserData.pu_test:type_name -> tgbase.state.v1.PushupTest
	16, // 53: tgbase.state.v1.UserData.pu_history:type_name -> tgbase.state.v1.PushupSessionLog
	20, // 54: tgbase.state.v1.UserMap.users:type_name -> tgbase.state.v1.UserMap.UsersEntry
	2,  // 55: tgbase.state.v1.UserData.ProductsEntry.value:type_name -> tgbase.state.v1.ProductProgress
	17, // 56: tgbase.state.v1.UserMap.UsersEntry.value:type_name -> tgbase.state.v1.UserData
	57, // [57:57] is the sub-list for method output_type
	57, // [57:57] is the sub-list for method input_type
	57, // [57:57] is the sub-list for extension type_name
	57, // [57:57] is the sub-list for extension extendee
	0,  // [0:57] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	file_state_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		EnumInfos:         file_state_proto_enumTypes,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
