// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: state.proto

package pb

import (
	pb "github.com/padington/tgbase/internal/products/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateKind int32

const (
	StateKind_STATE_UNSPECIFIED               StateKind = 0
	StateKind_STATE_IDLE                      StateKind = 1
	StateKind_STATE_AWAITING_DEFECATION       StateKind = 2
	StateKind_STATE_AWAITING_PRODUCT_CHOICE   StateKind = 3
	StateKind_STATE_AWAITING_STAGE_CHECKIN    StateKind = 4
	StateKind_STATE_AWAITING_STAGE_CHOICE     StateKind = 5
	StateKind_STATE_AWAITING_MODE_CHOICE      StateKind = 6
	StateKind_STATE_SCR_CONSENT               StateKind = 7
	StateKind_STATE_SCR_INTRO                 StateKind = 8
	StateKind_STATE_SCR_ASRS_A                StateKind = 9
	StateKind_STATE_SCR_ASRS_A_GATE           StateKind = 10
	StateKind_STATE_SCR_ASRS_B                StateKind = 11
	StateKind_STATE_SCR_ASRS_B_GATE           StateKind = 12
	StateKind_STATE_SCR_WURS_FORM             StateKind = 13
	StateKind_STATE_SCR_WURS                  StateKind = 14
	StateKind_STATE_SCR_WURS_GATE             StateKind = 15
	StateKind_STATE_SCR_ONSET                 StateKind = 16
	StateKind_STATE_SCR_ONSET_AGE             StateKind = 17
	StateKind_STATE_SCR_DOMAINS_ADULT         StateKind = 18
	StateKind_STATE_SCR_DOMAINS_CHILD         StateKind = 19
	StateKind_STATE_SCR_REFERRAL              StateKind = 20
	StateKind_STATE_SCR_REPORT                StateKind = 21
	StateKind_STATE_SCR_DELETE_CONFIRM        StateKind = 22
	StateKind_STATE_AWAITING_PRODUCT_CATEGORY StateKind = 23
	StateKind_STATE_MOOD_CONSENT              StateKind = 24
	StateKind_STATE_MOOD_QUESTION             StateKind = 25
	StateKind_STATE_MOOD_CRISIS               StateKind = 26
	StateKind_STATE_MOOD_REPORT               StateKind = 27
	StateKind_STATE_MOOD_DELETE_CONFIRM       StateKind = 28
	StateKind_STATE_MOOD_MENU                 StateKind = 29
	StateKind_STATE_MOOD_Q10                  StateKind = 30
	StateKind_STATE_MOOD_WHO5_QUESTION        StateKind = 31
	StateKind_STATE_MOOD_OFFER_PHQ9           StateKind = 32
	StateKind_STATE_MOOD_GAD7_QUESTION        StateKind = 33
	StateKind_STATE_MOOD_OFFER_GAD7           StateKind = 34
)

// Enum value maps for StateKind.
var (
	StateKind_name = map[int32]string{
		0:  "STATE_UNSPECIFIED",
		1:  "STATE_IDLE",
		2:  "STATE_AWAITING_DEFECATION",
		3:  "STATE_AWAITING_PRODUCT_CHOICE",
		4:  "STATE_AWAITING_STAGE_CHECKIN",
		5:  "STATE_AWAITING_STAGE_CHOICE",
		6:  "STATE_AWAITING_MODE_CHOICE",
		7:  "STATE_SCR_CONSENT",
		8:  "STATE_SCR_INTRO",
		9:  "STATE_SCR_ASRS_A",
		10: "STATE_SCR_ASRS_A_GATE",
		11: "STATE_SCR_ASRS_B",
		12: "STATE_SCR_ASRS_B_GATE",
		13: "STATE_SCR_WURS_FORM",
		14: "STATE_SCR_WURS",
		15: "STATE_SCR_WURS_GATE",
		16: "STATE_SCR_ONSET",
		17: "STATE_SCR_ONSET_AGE",
		18: "STATE_SCR_DOMAINS_ADULT",
		19: "STATE_SCR_DOMAINS_CHILD",
		20: "STATE_SCR_REFERRAL",
		21: "STATE_SCR_REPORT",
		22: "STATE_SCR_DELETE_CONFIRM",
		23: "STATE_AWAITING_PRODUCT_CATEGORY",
		24: "STATE_MOOD_CONSENT",
		25: "STATE_MOOD_QUESTION",
		26: "STATE_MOOD_CRISIS",
		27: "STATE_MOOD_REPORT",
		28: "STATE_MOOD_DELETE_CONFIRM",
		29: "STATE_MOOD_MENU",
		30: "STATE_MOOD_Q10",
		31: "STATE_MOOD_WHO5_QUESTION",
		32: "STATE_MOOD_OFFER_PHQ9",
		33: "STATE_MOOD_GAD7_QUESTION",
		34: "STATE_MOOD_OFFER_GAD7",
	}
	StateKind_value = map[string]int32{
		"STATE_UNSPECIFIED":               0,
		"STATE_IDLE":                      1,
		"STATE_AWAITING_DEFECATION":       2,
		"STATE_AWAITING_PRODUCT_CHOICE":   3,
		"STATE_AWAITING_STAGE_CHECKIN":    4,
		"STATE_AWAITING_STAGE_CHOICE":     5,
		"STATE_AWAITING_MODE_CHOICE":      6,
		"STATE_SCR_CONSENT":               7,
		"STATE_SCR_INTRO":                 8,
		"STATE_SCR_ASRS_A":                9,
		"STATE_SCR_ASRS_A_GATE":           10,
		"STATE_SCR_ASRS_B":                11,
		"STATE_SCR_ASRS_B_GATE":           12,
		"STATE_SCR_WURS_FORM":             13,
		"STATE_SCR_WURS":                  14,
		"STATE_SCR_WURS_GATE":             15,
		"STATE_SCR_ONSET":                 16,
		"STATE_SCR_ONSET_AGE":             17,
		"STATE_SCR_DOMAINS_ADULT":         18,
		"STATE_SCR_DOMAINS_CHILD":         19,
		"STATE_SCR_REFERRAL":              20,
		"STATE_SCR_REPORT":                21,
		"STATE_SCR_DELETE_CONFIRM":        22,
		"STATE_AWAITING_PRODUCT_CATEGORY": 23,
		"STATE_MOOD_CONSENT":              24,
		"STATE_MOOD_QUESTION":             25,
		"STATE_MOOD_CRISIS":               26,
		"STATE_MOOD_REPORT":               27,
		"STATE_MOOD_DELETE_CONFIRM":       28,
		"STATE_MOOD_MENU":                 29,
		"STATE_MOOD_Q10":                  30,
		"STATE_MOOD_WHO5_QUESTION":        31,
		"STATE_MOOD_OFFER_PHQ9":           32,
		"STATE_MOOD_GAD7_QUESTION":        33,
		"STATE_MOOD_OFFER_GAD7":           34,
	}
)

func (x StateKind) Enum() *StateKind {
	p := new(StateKind)
	*p = x
	return p
}

func (x StateKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateKind) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[0].Descriptor()
}

func (StateKind) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[0]
}

func (x StateKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateKind.Descriptor instead.
func (StateKind) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

type DefecationKind int32

const (
	DefecationKind_DEFECATION_UNSPECIFIED DefecationKind = 0
	DefecationKind_DEFECATION_FLUID       DefecationKind = 1
	DefecationKind_DEFECATION_NORMAL      DefecationKind = 2
	DefecationKind_DEFECATION_ISSUES      DefecationKind = 3
)

// Enum value maps for DefecationKind.
var (
	DefecationKind_name = map[int32]string{
		0: "DEFECATION_UNSPECIFIED",
		1: "DEFECATION_FLUID",
		2: "DEFECATION_NORMAL",
		3: "DEFECATION_ISSUES",
	}
	DefecationKind_value = map[string]int32{
		"DEFECATION_UNSPECIFIED": 0,
		"DEFECATION_FLUID":       1,
		"DEFECATION_NORMAL":      2,
		"DEFECATION_ISSUES":      3,
	}
)

func (x DefecationKind) Enum() *DefecationKind {
	p := new(DefecationKind)
	*p = x
	return p
}

func (x DefecationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefecationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[1].Descriptor()
}

func (DefecationKind) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[1]
}

func (x DefecationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefecationKind.Descriptor instead.
func (DefecationKind) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

type ProductProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastStage     pb.Stage               `protobuf:"varint,1,opt,name=last_stage,json=lastStage,proto3,enum=tgbase.products.v1.Stage" json:"last_stage,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // in_progress|completed|not_tolerated|interrupted
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductProgress) Reset() {
	*x = ProductProgress{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductProgress) ProtoMessage() {}

func (x *ProductProgress) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductProgress.ProtoReflect.Descriptor instead.
func (*ProductProgress) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *ProductProgress) GetLastStage() pb.Stage {
	if x != nil {
		return x.LastStage
	}
	return pb.Stage(0)
}

func (x *ProductProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductProgress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ScreeningProgress mirrors state.ScreeningProgress — the TRANSIENT
// unfinished ADHD-screening run (raw per-question answers live only here;
// wiped on completion / restart / abandon / delete).
type ScreeningProgress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AsrsAnswers    []int32                `protobuf:"varint,1,rep,packed,name=asrs_answers,json=asrsAnswers,proto3" json:"asrs_answers,omitempty"` // append-only, scores 0..4; index = id-1
	WursAnswers    []int32                `protobuf:"varint,2,rep,packed,name=wurs_answers,json=wursAnswers,proto3" json:"wurs_answers,omitempty"` // append-only, scores 0..4
	WursForm       string                 `protobuf:"bytes,3,opt,name=wurs_form,json=wursForm,proto3" json:"wurs_form,omitempty"`                  // "m" | "f"
	OnsetChild     *bool                  `protobuf:"varint,4,opt,name=onset_child,json=onsetChild,proto3,oneof" json:"onset_child,omitempty"`     // absent = not asked yet
	OnsetAge       int32                  `protobuf:"varint,5,opt,name=onset_age,json=onsetAge,proto3" json:"onset_age,omitempty"`                 // >0 when onset_child == false
	AdultDomains   []string               `protobuf:"bytes,6,rep,name=adult_domains,json=adultDomains,proto3" json:"adult_domains,omitempty"`      // only the ids answered "yes"
	ChildDomains   []string               `protobuf:"bytes,7,rep,name=child_domains,json=childDomains,proto3" json:"child_domains,omitempty"`      // only the ids answered "yes"
	ResumeState    StateKind              `protobuf:"varint,8,opt,name=resume_state,json=resumeState,proto3,enum=tgbase.state.v1.StateKind" json:"resume_state,omitempty"`
	ConsentAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=consent_at,json=consentAt,proto3" json:"consent_at,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	AdultDomainIdx int32                  `protobuf:"varint,11,opt,name=adult_domain_idx,json=adultDomainIdx,proto3" json:"adult_domain_idx,omitempty"` // domains answered so far (yes AND no)
	ChildDomainIdx int32                  `protobuf:"varint,12,opt,name=child_domain_idx,json=childDomainIdx,proto3" json:"child_domain_idx,omitempty"` // domains answered so far (yes AND no)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScreeningProgress) Reset() {
	*x = ScreeningProgress{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreeningProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreeningProgress) ProtoMessage() {}

func (x *ScreeningProgress) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreeningProgress.ProtoReflect.Descriptor instead.
func (*ScreeningProgress) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *ScreeningProgress) GetAsrsAnswers() []int32 {
	if x != nil {
		return x.AsrsAnswers
	}
	return nil
}

func (x *ScreeningProgress) GetWursAnswers() []int32 {
	if x != nil {
		return x.WursAnswers
	}
	return nil
}

func (x *ScreeningProgress) GetWursForm() string {
	if x != nil {
		return x.WursForm
	}
	return ""
}

func (x *ScreeningProgress) GetOnsetChild() bool {
	if x != nil && x.OnsetChild != nil {
		return *x.OnsetChild
	}
	return false
}

func (x *ScreeningProgress) GetOnsetAge() int32 {
	if x != nil {
		return x.OnsetAge
	}
	return 0
}

func (x *ScreeningProgress) GetAdultDomains() []string {
	if x != nil {
		return x.AdultDomains
	}
	return nil
}

func (x *ScreeningProgress) GetChildDomains() []string {
	if x != nil {
		return x.ChildDomains
	}
	return nil
}

func (x *ScreeningProgress) GetResumeState() StateKind {
	if x != nil {
		return x.ResumeState
	}
	return StateKind_STATE_UNSPECIFIED
}

func (x *ScreeningProgress) GetConsentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConsentAt
	}
	return nil
}

func (x *ScreeningProgress) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ScreeningProgress) GetAdultDomainIdx() int32 {
	if x != nil {
		return x.AdultDomainIdx
	}
	return 0
}

func (x *ScreeningProgress) GetChildDomainIdx() int32 {
	if x != nil {
		return x.ChildDomainIdx
	}
	return 0
}

// ScreeningResult mirrors state.ScreeningResult — the last completed run:
// scores + applied thresholds + context facts, never per-question answers.
type ScreeningResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TakenAt          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	AsrsASignificant int32                  `protobuf:"varint,2,opt,name=asrs_a_significant,json=asrsASignificant,proto3" json:"asrs_a_significant,omitempty"` // 0..6
	AsrsAThreshold   int32                  `protobuf:"varint,3,opt,name=asrs_a_threshold,json=asrsAThreshold,proto3" json:"asrs_a_threshold,omitempty"`       // applied threshold (4)
	AsrsAPositive    bool                   `protobuf:"varint,4,opt,name=asrs_a_positive,json=asrsAPositive,proto3" json:"asrs_a_positive,omitempty"`
	AsrsBSignificant int32                  `protobuf:"varint,5,opt,name=asrs_b_significant,json=asrsBSignificant,proto3" json:"asrs_b_significant,omitempty"` // 0..12, no threshold by design
	WursScore        int32                  `protobuf:"varint,6,opt,name=wurs_score,json=wursScore,proto3" json:"wurs_score,omitempty"`                        // 0..100
	WursCutoff       int32                  `protobuf:"varint,7,opt,name=wurs_cutoff,json=wursCutoff,proto3" json:"wurs_cutoff,omitempty"`                     // applied cutoff (46)
	WursPositive     bool                   `protobuf:"varint,8,opt,name=wurs_positive,json=wursPositive,proto3" json:"wurs_positive,omitempty"`
	OnsetChildhood   bool                   `protobuf:"varint,9,opt,name=onset_childhood,json=onsetChildhood,proto3" json:"onset_childhood,omitempty"`
	OnsetAge         int32                  `protobuf:"varint,10,opt,name=onset_age,json=onsetAge,proto3" json:"onset_age,omitempty"` // 0 when onset_childhood
	AdultDomains     []string               `protobuf:"bytes,11,rep,name=adult_domains,json=adultDomains,proto3" json:"adult_domains,omitempty"`
	ChildDomains     []string               `protobuf:"bytes,12,rep,name=child_domains,json=childDomains,proto3" json:"child_domains,omitempty"`
	Verdict          string                 `protobuf:"bytes,13,opt,name=verdict,proto3" json:"verdict,omitempty"`                // consistent | partial | not_consistent
	GapHint          string                 `protobuf:"bytes,14,opt,name=gap_hint,json=gapHint,proto3" json:"gap_hint,omitempty"` // gap-hint key when partial
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScreeningResult) Reset() {
	*x = ScreeningResult{}
	mi := &file_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreeningResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreeningResult) ProtoMessage() {}

func (x *ScreeningResult) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreeningResult.ProtoReflect.Descriptor instead.
func (*ScreeningResult) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

func (x *ScreeningResult) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *ScreeningResult) GetAsrsASignificant() int32 {
	if x != nil {
		return x.AsrsASignificant
	}
	return 0
}

func (x *ScreeningResult) GetAsrsAThreshold() int32 {
	if x != nil {
		return x.AsrsAThreshold
	}
	return 0
}

func (x *ScreeningResult) GetAsrsAPositive() bool {
	if x != nil {
		return x.AsrsAPositive
	}
	return false
}

func (x *ScreeningResult) GetAsrsBSignificant() int32 {
	if x != nil {
		return x.AsrsBSignificant
	}
	return 0
}

func (x *ScreeningResult) GetWursScore() int32 {
	if x != nil {
		return x.WursScore
	}
	return 0
}

func (x *ScreeningResult) GetWursCutoff() int32 {
	if x != nil {
		return x.WursCutoff
	}
	return 0
}

func (x *ScreeningResult) GetWursPositive() bool {
	if x != nil {
		return x.WursPositive
	}
	return false
}

func (x *ScreeningResult) GetOnsetChildhood() bool {
	if x != nil {
		return x.OnsetChildhood
	}
	return false
}

func (x *ScreeningResult) GetOnsetAge() int32 {
	if x != nil {
		return x.OnsetAge
	}
	return 0
}

func (x *ScreeningResult) GetAdultDomains() []string {
	if x != nil {
		return x.AdultDomains
	}
	return nil
}

func (x *ScreeningResult) GetChildDomains() []string {
	if x != nil {
		return x.ChildDomains
	}
	return nil
}

func (x *ScreeningResult) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *ScreeningResult) GetGapHint() string {
	if x != nil {
		return x.GapHint
	}
	return ""
}

// MoodProgress mirrors state.MoodProgress — the TRANSIENT unfinished run of
// one mood-module instrument (PHQ-9 in `mood`, WHO-5 in `who5`, GAD-7 in
// `gad7`; raw per-question answers live only here; wiped on completion /
// restart / abandon / delete).
type MoodProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []int32                `protobuf:"varint,1,rep,packed,name=answers,proto3" json:"answers,omitempty"`                                                    // append-only; index = id-1 (PHQ-9 index 9 = the functional item)
	ResumeState   StateKind              `protobuf:"varint,2,opt,name=resume_state,json=resumeState,proto3,enum=tgbase.state.v1.StateKind" json:"resume_state,omitempty"` // recorded escape position (PHQ-9 question/crisis/q10, WHO-5/GAD-7 question)
	ConsentAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=consent_at,json=consentAt,proto3" json:"consent_at,omitempty"`                                       // legacy (v1 per-run consent); module consent lives on UserData
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoodProgress) Reset() {
	*x = MoodProgress{}
	mi := &file_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoodProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoodProgress) ProtoMessage() {}

func (x *MoodProgress) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoodProgress.ProtoReflect.Descriptor instead.
func (*MoodProgress) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{3}
}

func (x *MoodProgress) GetAnswers() []int32 {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *MoodProgress) GetResumeState() StateKind {
	if x != nil {
		return x.ResumeState
	}
	return StateKind_STATE_UNSPECIFIED
}

func (x *MoodProgress) GetConsentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConsentAt
	}
	return nil
}

func (x *MoodProgress) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// MoodResult mirrors state.MoodResult — the last completed PHQ-9 run: total
// score + applied severity band + the item-9 flag + the answer to the
// functional (10th) item, never the per-question answers 1..9.
type MoodResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`                                // 0..27 (functional item NOT included)
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`                           // applied severity-band id
	Q9Positive    bool                   `protobuf:"varint,4,opt,name=q9_positive,json=q9Positive,proto3" json:"q9_positive,omitempty"`    // self-harm item answered > 0
	Q10Answered   bool                   `protobuf:"varint,5,opt,name=q10_answered,json=q10Answered,proto3" json:"q10_answered,omitempty"` // functional item was shown and answered
	Q10Answer     int32                  `protobuf:"varint,6,opt,name=q10_answer,json=q10Answer,proto3" json:"q10_answer,omitempty"`       // 0..3, meaningful only when q10_answered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoodResult) Reset() {
	*x = MoodResult{}
	mi := &file_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoodResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoodResult) ProtoMessage() {}

func (x *MoodResult) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoodResult.ProtoReflect.Descriptor instead.
func (*MoodResult) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{4}
}

func (x *MoodResult) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *MoodResult) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MoodResult) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *MoodResult) GetQ9Positive() bool {
	if x != nil {
		return x.Q9Positive
	}
	return false
}

func (x *MoodResult) GetQ10Answered() bool {
	if x != nil {
		return x.Q10Answered
	}
	return false
}

func (x *MoodResult) GetQ10Answer() int32 {
	if x != nil {
		return x.Q10Answer
	}
	return 0
}

// Who5Result mirrors state.Who5Result — the last completed WHO-5 quick check:
// the 0–100 score (raw 0–25 sum × 4) + the applied interpretation band.
type Who5Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"` // 0..100
	Band          string                 `protobuf:"bytes,3,opt,name=band,proto3" json:"band,omitempty"`    // ok | low | very_low
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Who5Result) Reset() {
	*x = Who5Result{}
	mi := &file_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Who5Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Who5Result) ProtoMessage() {}

func (x *Who5Result) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Who5Result.ProtoReflect.Descriptor instead.
func (*Who5Result) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{5}
}

func (x *Who5Result) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *Who5Result) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Who5Result) GetBand() string {
	if x != nil {
		return x.Band
	}
	return ""
}

// Gad7Result mirrors state.Gad7Result — the last completed GAD-7 run: total
// score + applied severity band, never per-question answers.
type Gad7Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TakenAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=taken_at,json=takenAt,proto3" json:"taken_at,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`      // 0..21
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // minimal | mild | moderate | severe
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gad7Result) Reset() {
	*x = Gad7Result{}
	mi := &file_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gad7Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gad7Result) ProtoMessage() {}

func (x *Gad7Result) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gad7Result.ProtoReflect.Descriptor instead.
func (*Gad7Result) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{6}
}

func (x *Gad7Result) GetTakenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TakenAt
	}
	return nil
}

func (x *Gad7Result) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Gad7Result) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type UserData struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	State           StateKind                   `protobuf:"varint,1,opt,name=state,proto3,enum=tgbase.state.v1.StateKind" json:"state,omitempty"`
	DefecationState DefecationKind              `protobuf:"varint,2,opt,name=defecation_state,json=defecationState,proto3,enum=tgbase.state.v1.DefecationKind" json:"defecation_state,omitempty"`
	CurrentProduct  string                      `protobuf:"bytes,3,opt,name=current_product,json=currentProduct,proto3" json:"current_product,omitempty"`
	CurrentStage    pb.Stage                    `protobuf:"varint,4,opt,name=current_stage,json=currentStage,proto3,enum=tgbase.products.v1.Stage" json:"current_stage,omitempty"`
	StageStartedAt  *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=stage_started_at,json=stageStartedAt,proto3" json:"stage_started_at,omitempty"`
	CheckinAsked    bool                        `protobuf:"varint,6,opt,name=checkin_asked,json=checkinAsked,proto3" json:"checkin_asked,omitempty"`
	OfferedProducts []string                    `protobuf:"bytes,7,rep,name=offered_products,json=offeredProducts,proto3" json:"offered_products,omitempty"`
	Products        map[string]*ProductProgress `protobuf:"bytes,8,rep,name=products,proto3" json:"products,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ChatId          int64                       `protobuf:"varint,9,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	EnteredAt       *timestamppb.Timestamp      `protobuf:"bytes,10,opt,name=entered_at,json=enteredAt,proto3" json:"entered_at,omitempty"`
	ReminderSent    bool                        `protobuf:"varint,11,opt,name=reminder_sent,json=reminderSent,proto3" json:"reminder_sent,omitempty"`
	Locale          string                      `protobuf:"bytes,12,opt,name=locale,proto3" json:"locale,omitempty"`
	Screening       *ScreeningProgress          `protobuf:"bytes,13,opt,name=screening,proto3" json:"screening,omitempty"`
	ScreeningResult *ScreeningResult            `protobuf:"bytes,14,opt,name=screening_result,json=screeningResult,proto3" json:"screening_result,omitempty"`
	ReturnState     StateKind                   `protobuf:"varint,15,opt,name=return_state,json=returnState,proto3,enum=tgbase.state.v1.StateKind" json:"return_state,omitempty"`
	Mood            *MoodProgress               `protobuf:"bytes,16,opt,name=mood,proto3" json:"mood,omitempty"`
	MoodResult      *MoodResult                 `protobuf:"bytes,17,opt,name=mood_result,json=moodResult,proto3" json:"mood_result,omitempty"`
	// Mood module v2: one consent for the whole module (wiped by /mood_delete),
	// per-instrument transient runs and last completed results.
	MoodConsentAt *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=mood_consent_at,json=moodConsentAt,proto3" json:"mood_consent_at,omitempty"`
	Who5          *MoodProgress          `protobuf:"bytes,19,opt,name=who5,proto3" json:"who5,omitempty"`
	Gad7          *MoodProgress          `protobuf:"bytes,20,opt,name=gad7,proto3" json:"gad7,omitempty"`
	Who5Result    *Who5Result            `protobuf:"bytes,21,opt,name=who5_result,json=who5Result,proto3" json:"who5_result,omitempty"`
	Gad7Result    *Gad7Result            `protobuf:"bytes,22,opt,name=gad7_result,json=gad7Result,proto3" json:"gad7_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{7}
}

func (x *UserData) GetState() StateKind {
	if x != nil {
		return x.State
	}
	return StateKind_STATE_UNSPECIFIED
}

func (x *UserData) GetDefecationState() DefecationKind {
	if x != nil {
		return x.DefecationState
	}
	return DefecationKind_DEFECATION_UNSPECIFIED
}

func (x *UserData) GetCurrentProduct() string {
	if x != nil {
		return x.CurrentProduct
	}
	return ""
}

func (x *UserData) GetCurrentStage() pb.Stage {
	if x != nil {
		return x.CurrentStage
	}
	return pb.Stage(0)
}

func (x *UserData) GetStageStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StageStartedAt
	}
	return nil
}

func (x *UserData) GetCheckinAsked() bool {
	if x != nil {
		return x.CheckinAsked
	}
	return false
}

func (x *UserData) GetOfferedProducts() []string {
	if x != nil {
		return x.OfferedProducts
	}
	return nil
}

func (x *UserData) GetProducts() map[string]*ProductProgress {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *UserData) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *UserData) GetEnteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnteredAt
	}
	return nil
}

func (x *UserData) GetReminderSent() bool {
	if x != nil {
		return x.ReminderSent
	}
	return false
}

func (x *UserData) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *UserData) GetScreening() *ScreeningProgress {
	if x != nil {
		return x.Screening
	}
	return nil
}

func (x *UserData) GetScreeningResult() *ScreeningResult {
	if x != nil {
		return x.ScreeningResult
	}
	return nil
}

func (x *UserData) GetReturnState() StateKind {
	if x != nil {
		return x.ReturnState
	}
	return StateKind_STATE_UNSPECIFIED
}

func (x *UserData) GetMood() *MoodProgress {
	if x != nil {
		return x.Mood
	}
	return nil
}

func (x *UserData) GetMoodResult() *MoodResult {
	if x != nil {
		return x.MoodResult
	}
	return nil
}

func (x *UserData) GetMoodConsentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MoodConsentAt
	}
	return nil
}

func (x *UserData) GetWho5() *MoodProgress {
	if x != nil {
		return x.Who5
	}
	return nil
}

func (x *UserData) GetGad7() *MoodProgress {
	if x != nil {
		return x.Gad7
	}
	return nil
}

func (x *UserData) GetWho5Result() *Who5Result {
	if x != nil {
		return x.Who5Result
	}
	return nil
}

func (x *UserData) GetGad7Result() *Gad7Result {
	if x != nil {
		return x.Gad7Result
	}
	return nil
}

type UserMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         map[int64]*UserData    `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMap) Reset() {
	*x = UserMap{}
	mi := &file_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMap) ProtoMessage() {}

func (x *UserMap) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMap.ProtoReflect.Descriptor instead.
func (*UserMap) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{8}
}

func (x *UserMap) GetUsers() map[int64]*UserData {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\x0ftgbase.state.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0eproducts.proto\"\x9e\x01\n" +
	"\x0fProductProgress\x128\n" +
	"\n" +
	"last_stage\x18\x01 \x01(\x0e2\x19.tgbase.products.v1.StageR\tlastStage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9c\x04\n" +
	"\x11ScreeningProgress\x12!\n" +
	"\fasrs_answers\x18\x01 \x03(\x05R\vasrsAnswers\x12!\n" +
	"\fwurs_answers\x18\x02 \x03(\x05R\vwursAnswers\x12\x1b\n" +
	"\twurs_form\x18\x03 \x01(\tR\bwursForm\x12$\n" +
	"\vonset_child\x18\x04 \x01(\bH\x00R\n" +
	"onsetChild\x88\x01\x01\x12\x1b\n" +
	"\tonset_age\x18\x05 \x01(\x05R\bonsetAge\x12#\n" +
	"\radult_domains\x18\x06 \x03(\tR\fadultDomains\x12#\n" +
	"\rchild_domains\x18\a \x03(\tR\fchildDomains\x12=\n" +
	"\fresume_state\x18\b \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\vresumeState\x129\n" +
	"\n" +
	"consent_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tconsentAt\x129\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12(\n" +
	"\x10adult_domain_idx\x18\v \x01(\x05R\x0eadultDomainIdx\x12(\n" +
	"\x10child_domain_idx\x18\f \x01(\x05R\x0echildDomainIdxB\x0e\n" +
	"\f_onset_child\"\xa0\x04\n" +
	"\x0fScreeningResult\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12,\n" +
	"\x12asrs_a_significant\x18\x02 \x01(\x05R\x10asrsASignificant\x12(\n" +
	"\x10asrs_a_threshold\x18\x03 \x01(\x05R\x0easrsAThreshold\x12&\n" +
	"\x0fasrs_a_positive\x18\x04 \x01(\bR\rasrsAPositive\x12,\n" +
	"\x12asrs_b_significant\x18\x05 \x01(\x05R\x10asrsBSignificant\x12\x1d\n" +
	"\n" +
	"wurs_score\x18\x06 \x01(\x05R\twursScore\x12\x1f\n" +
	"\vwurs_cutoff\x18\a \x01(\x05R\n" +
	"wursCutoff\x12#\n" +
	"\rwurs_positive\x18\b \x01(\bR\fwursPositive\x12'\n" +
	"\x0fonset_childhood\x18\t \x01(\bR\x0eonsetChildhood\x12\x1b\n" +
	"\tonset_age\x18\n" +
	" \x01(\x05R\bonsetAge\x12#\n" +
	"\radult_domains\x18\v \x03(\tR\fadultDomains\x12#\n" +
	"\rchild_domains\x18\f \x03(\tR\fchildDomains\x12\x18\n" +
	"\averdict\x18\r \x01(\tR\averdict\x12\x19\n" +
	"\bgap_hint\x18\x0e \x01(\tR\agapHint\"\xdd\x01\n" +
	"\fMoodProgress\x12\x18\n" +
	"\aanswers\x18\x01 \x03(\x05R\aanswers\x12=\n" +
	"\fresume_state\x18\x02 \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\vresumeState\x129\n" +
	"\n" +
	"consent_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tconsentAt\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xd8\x01\n" +
	"\n" +
	"MoodResult\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1f\n" +
	"\vq9_positive\x18\x04 \x01(\bR\n" +
	"q9Positive\x12!\n" +
	"\fq10_answered\x18\x05 \x01(\bR\vq10Answered\x12\x1d\n" +
	"\n" +
	"q10_answer\x18\x06 \x01(\x05R\tq10Answer\"m\n" +
	"\n" +
	"Who5Result\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x12\n" +
	"\x04band\x18\x03 \x01(\tR\x04band\"u\n" +
	"\n" +
	"Gad7Result\x125\n" +
	"\btaken_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\atakenAt\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\"\xa1\n" +
	"\n" +
	"\bUserData\x120\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\x05state\x12J\n" +
	"\x10defecation_state\x18\x02 \x01(\x0e2\x1f.tgbase.state.v1.DefecationKindR\x0fdefecationState\x12'\n" +
	"\x0fcurrent_product\x18\x03 \x01(\tR\x0ecurrentProduct\x12>\n" +
	"\rcurrent_stage\x18\x04 \x01(\x0e2\x19.tgbase.products.v1.StageR\fcurrentStage\x12D\n" +
	"\x10stage_started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0estageStartedAt\x12#\n" +
	"\rcheckin_asked\x18\x06 \x01(\bR\fcheckinAsked\x12)\n" +
	"\x10offered_products\x18\a \x03(\tR\x0fofferedProducts\x12C\n" +
	"\bproducts\x18\b \x03(\v2'.tgbase.state.v1.UserData.ProductsEntryR\bproducts\x12\x17\n" +
	"\achat_id\x18\t \x01(\x03R\x06chatId\x129\n" +
	"\n" +
	"entered_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tenteredAt\x12#\n" +
	"\rreminder_sent\x18\v \x01(\bR\freminderSent\x12\x16\n" +
	"\x06locale\x18\f \x01(\tR\x06locale\x12@\n" +
	"\tscreening\x18\r \x01(\v2\".tgbase.state.v1.ScreeningProgressR\tscreening\x12K\n" +
	"\x10screening_result\x18\x0e \x01(\v2 .tgbase.state.v1.ScreeningResultR\x0fscreeningResult\x12=\n" +
	"\freturn_state\x18\x0f \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\vreturnState\x121\n" +
	"\x04mood\x18\x10 \x01(\v2\x1d.tgbase.state.v1.MoodProgressR\x04mood\x12<\n" +
	"\vmood_result\x18\x11 \x01(\v2\x1b.tgbase.state.v1.MoodResultR\n" +
	"moodResult\x12B\n" +
	"\x0fmood_consent_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\rmoodConsentAt\x121\n" +
	"\x04who5\x18\x13 \x01(\v2\x1d.tgbase.state.v1.MoodProgressR\x04who5\x121\n" +
	"\x04gad7\x18\x14 \x01(\v2\x1d.tgbase.state.v1.MoodProgressR\x04gad7\x12<\n" +
	"\vwho5_result\x18\x15 \x01(\v2\x1b.tgbase.state.v1.Who5ResultR\n" +
	"who5Result\x12<\n" +
	"\vgad7_result\x18\x16 \x01(\v2\x1b.tgbase.state.v1.Gad7ResultR\n" +
	"gad7Result\x1a]\n" +
	"\rProductsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .tgbase.state.v1.ProductProgressR\x05value:\x028\x01\"\x99\x01\n" +
	"\aUserMap\x129\n" +
	"\x05users\x18\x01 \x03(\v2#.tgbase.state.v1.UserMap.UsersEntryR\x05users\x1aS\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.tgbase.state.v1.UserDataR\x05value:\x028\x01*\x9d\a\n" +
	"\tStateKind\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_IDLE\x10\x01\x12\x1d\n" +
	"\x19STATE_AWAITING_DEFECATION\x10\x02\x12!\n" +
	"\x1dSTATE_AWAITING_PRODUCT_CHOICE\x10\x03\x12 \n" +
	"\x1cSTATE_AWAITING_STAGE_CHECKIN\x10\x04\x12\x1f\n" +
	"\x1bSTATE_AWAITING_STAGE_CHOICE\x10\x05\x12\x1e\n" +
	"\x1aSTATE_AWAITING_MODE_CHOICE\x10\x06\x12\x15\n" +
	"\x11STATE_SCR_CONSENT\x10\a\x12\x13\n" +
	"\x0fSTATE_SCR_INTRO\x10\b\x12\x14\n" +
	"\x10STATE_SCR_ASRS_A\x10\t\x12\x19\n" +
	"\x15STATE_SCR_ASRS_A_GATE\x10\n" +
	"\x12\x14\n" +
	"\x10STATE_SCR_ASRS_B\x10\v\x12\x19\n" +
	"\x15STATE_SCR_ASRS_B_GATE\x10\f\x12\x17\n" +
	"\x13STATE_SCR_WURS_FORM\x10\r\x12\x12\n" +
	"\x0eSTATE_SCR_WURS\x10\x0e\x12\x17\n" +
	"\x13STATE_SCR_WURS_GATE\x10\x0f\x12\x13\n" +
	"\x0fSTATE_SCR_ONSET\x10\x10\x12\x17\n" +
	"\x13STATE_SCR_ONSET_AGE\x10\x11\x12\x1b\n" +
	"\x17STATE_SCR_DOMAINS_ADULT\x10\x12\x12\x1b\n" +
	"\x17STATE_SCR_DOMAINS_CHILD\x10\x13\x12\x16\n" +
	"\x12STATE_SCR_REFERRAL\x10\x14\x12\x14\n" +
	"\x10STATE_SCR_REPORT\x10\x15\x12\x1c\n" +
	"\x18STATE_SCR_DELETE_CONFIRM\x10\x16\x12#\n" +
	"\x1fSTATE_AWAITING_PRODUCT_CATEGORY\x10\x17\x12\x16\n" +
	"\x12STATE_MOOD_CONSENT\x10\x18\x12\x17\n" +
	"\x13STATE_MOOD_QUESTION\x10\x19\x12\x15\n" +
	"\x11STATE_MOOD_CRISIS\x10\x1a\x12\x15\n" +
	"\x11STATE_MOOD_REPORT\x10\x1b\x12\x1d\n" +
	"\x19STATE_MOOD_DELETE_CONFIRM\x10\x1c\x12\x13\n" +
	"\x0fSTATE_MOOD_MENU\x10\x1d\x12\x12\n" +
	"\x0eSTATE_MOOD_Q10\x10\x1e\x12\x1c\n" +
	"\x18STATE_MOOD_WHO5_QUESTION\x10\x1f\x12\x19\n" +
	"\x15STATE_MOOD_OFFER_PHQ9\x10 \x12\x1c\n" +
	"\x18STATE_MOOD_GAD7_QUESTION\x10!\x12\x19\n" +
	"\x15STATE_MOOD_OFFER_GAD7\x10\"*p\n" +
	"\x0eDefecationKind\x12\x1a\n" +
	"\x16DEFECATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DEFECATION_FLUID\x10\x01\x12\x15\n" +
	"\x11DEFECATION_NORMAL\x10\x02\x12\x15\n" +
	"\x11DEFECATION_ISSUES\x10\x03B2Z0github.com/padington/tgbase/internal/state/pb;pbb\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_state_proto_goTypes = []any{
	(StateKind)(0),                // 0: tgbase.state.v1.StateKind
	(DefecationKind)(0),           // 1: tgbase.state.v1.DefecationKind
	(*ProductProgress)(nil),       // 2: tgbase.state.v1.ProductProgress
	(*ScreeningProgress)(nil),     // 3: tgbase.state.v1.ScreeningProgress
	(*ScreeningResult)(nil),       // 4: tgbase.state.v1.ScreeningResult
	(*MoodProgress)(nil),          // 5: tgbase.state.v1.MoodProgress
	(*MoodResult)(nil),            // 6: tgbase.state.v1.MoodResult
	(*Who5Result)(nil),            // 7: tgbase.state.v1.Who5Result
	(*Gad7Result)(nil),            // 8: tgbase.state.v1.Gad7Result
	(*UserData)(nil),              // 9: tgbase.state.v1.UserData
	(*UserMap)(nil),               // 10: tgbase.state.v1.UserMap
	nil,                           // 11: tgbase.state.v1.UserData.ProductsEntry
	nil,                           // 12: tgbase.state.v1.UserMap.UsersEntry
	(pb.Stage)(0),                 // 13: tgbase.products.v1.Stage
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_state_proto_depIdxs = []int32{
	13, // 0: tgbase.state.v1.ProductProgress.last_stage:type_name -> tgbase.products.v1.Stage
	14, // 1: tgbase.state.v1.ProductProgress.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: tgbase.state.v1.ScreeningProgress.resume_state:type_name -> tgbase.state.v1.StateKind
	14, // 3: tgbase.state.v1.ScreeningProgress.consent_at:type_name -> google.protobuf.Timestamp
	14, // 4: tgbase.state.v1.ScreeningProgress.started_at:type_name -> google.protobuf.Timestamp
	14, // 5: tgbase.state.v1.ScreeningResult.taken_at:type_name -> google.protobuf.Timestamp
	0,  // 6: tgbase.state.v1.MoodProgress.resume_state:type_name -> tgbase.state.v1.StateKind
	14, // 7: tgbase.state.v1.MoodProgress.consent_at:type_name -> google.protobuf.Timestamp
	14, // 8: tgbase.state.v1.MoodProgress.started_at:type_name -> google.protobuf.Timestamp
	14, // 9: tgbase.state.v1.MoodResult.taken_at:type_name -> google.protobuf.Timestamp
	14, // 10: tgbase.state.v1.Who5Result.taken_at:type_name -> google.protobuf.Timestamp
	14, // 11: tgbase.state.v1.Gad7Result.taken_at:type_name -> google.protobuf.Timestamp
	0,  // 12: tgbase.state.v1.UserData.state:type_name -> tgbase.state.v1.StateKind
	1,  // 13: tgbase.state.v1.UserData.defecation_state:type_name -> tgbase.state.v1.DefecationKind
	13, // 14: tgbase.state.v1.UserData.current_stage:type_name -> tgbase.products.v1.Stage
	14, // 15: tgbase.state.v1.UserData.stage_started_at:type_name -> google.protobuf.Timestamp
	11, // 16: tgbase.state.v1.UserData.products:type_name -> tgbase.state.v1.UserData.ProductsEntry
	14, // 17: tgbase.state.v1.UserData.entered_at:type_name -> google.protobuf.Timestamp
	3,  // 18: tgbase.state.v1.UserData.screening:type_name -> tgbase.state.v1.ScreeningProgress
	4,  // 19: tgbase.state.v1.UserData.screening_result:type_name -> tgbase.state.v1.ScreeningResult
	0,  // 20: tgbase.state.v1.UserData.return_state:type_name -> tgbase.state.v1.StateKind
	5,  // 21: tgbase.state.v1.UserData.mood:type_name -> tgbase.state.v1.MoodProgress
	6,  // 22: tgbase.state.v1.UserData.mood_result:type_name -> tgbase.state.v1.MoodResult
	14, // 23: tgbase.state.v1.UserData.mood_consent_at:type_name -> google.protobuf.Timestamp
	5,  // 24: tgbase.state.v1.UserData.who5:type_name -> tgbase.state.v1.MoodProgress
	5,  // 25: tgbase.state.v1.UserData.gad7:type_name -> tgbase.state.v1.MoodProgress
	7,  // 26: tgbase.state.v1.UserData.who5_result:type_name -> tgbase.state.v1.Who5Result
	8,  // 27: tgbase.state.v1.UserData.gad7_result:type_name -> tgbase.state.v1.Gad7Result
	12, // 28: tgbase.state.v1.UserMap.users:type_name -> tgbase.state.v1.UserMap.UsersEntry
	2,  // 29: tgbase.state.v1.UserData.ProductsEntry.value:type_name -> tgbase.state.v1.ProductProgress
	9,  // 30: tgbase.state.v1.UserMap.UsersEntry.value:type_name -> tgbase.state.v1.UserData
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	file_state_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		EnumInfos:         file_state_proto_enumTypes,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
