// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: state.proto

package pb

import (
	pb "github.com/padington/tgbase/internal/products/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateKind int32

const (
	StateKind_STATE_UNSPECIFIED             StateKind = 0
	StateKind_STATE_IDLE                    StateKind = 1
	StateKind_STATE_AWAITING_DEFECATION     StateKind = 2
	StateKind_STATE_AWAITING_PRODUCT_CHOICE StateKind = 3
	StateKind_STATE_AWAITING_STAGE_CHECKIN  StateKind = 4
)

// Enum value maps for StateKind.
var (
	StateKind_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_IDLE",
		2: "STATE_AWAITING_DEFECATION",
		3: "STATE_AWAITING_PRODUCT_CHOICE",
		4: "STATE_AWAITING_STAGE_CHECKIN",
	}
	StateKind_value = map[string]int32{
		"STATE_UNSPECIFIED":             0,
		"STATE_IDLE":                    1,
		"STATE_AWAITING_DEFECATION":     2,
		"STATE_AWAITING_PRODUCT_CHOICE": 3,
		"STATE_AWAITING_STAGE_CHECKIN":  4,
	}
)

func (x StateKind) Enum() *StateKind {
	p := new(StateKind)
	*p = x
	return p
}

func (x StateKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateKind) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[0].Descriptor()
}

func (StateKind) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[0]
}

func (x StateKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateKind.Descriptor instead.
func (StateKind) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

type DefecationKind int32

const (
	DefecationKind_DEFECATION_UNSPECIFIED DefecationKind = 0
	DefecationKind_DEFECATION_FLUID       DefecationKind = 1
	DefecationKind_DEFECATION_NORMAL      DefecationKind = 2
	DefecationKind_DEFECATION_ISSUES      DefecationKind = 3
)

// Enum value maps for DefecationKind.
var (
	DefecationKind_name = map[int32]string{
		0: "DEFECATION_UNSPECIFIED",
		1: "DEFECATION_FLUID",
		2: "DEFECATION_NORMAL",
		3: "DEFECATION_ISSUES",
	}
	DefecationKind_value = map[string]int32{
		"DEFECATION_UNSPECIFIED": 0,
		"DEFECATION_FLUID":       1,
		"DEFECATION_NORMAL":      2,
		"DEFECATION_ISSUES":      3,
	}
)

func (x DefecationKind) Enum() *DefecationKind {
	p := new(DefecationKind)
	*p = x
	return p
}

func (x DefecationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefecationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_state_proto_enumTypes[1].Descriptor()
}

func (DefecationKind) Type() protoreflect.EnumType {
	return &file_state_proto_enumTypes[1]
}

func (x DefecationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefecationKind.Descriptor instead.
func (DefecationKind) EnumDescriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

type ProductProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastStage     pb.Stage               `protobuf:"varint,1,opt,name=last_stage,json=lastStage,proto3,enum=tgbase.products.v1.Stage" json:"last_stage,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // in_progress|completed|not_tolerated|interrupted
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductProgress) Reset() {
	*x = ProductProgress{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductProgress) ProtoMessage() {}

func (x *ProductProgress) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductProgress.ProtoReflect.Descriptor instead.
func (*ProductProgress) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *ProductProgress) GetLastStage() pb.Stage {
	if x != nil {
		return x.LastStage
	}
	return pb.Stage(0)
}

func (x *ProductProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductProgress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserData struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	State           StateKind                   `protobuf:"varint,1,opt,name=state,proto3,enum=tgbase.state.v1.StateKind" json:"state,omitempty"`
	DefecationState DefecationKind              `protobuf:"varint,2,opt,name=defecation_state,json=defecationState,proto3,enum=tgbase.state.v1.DefecationKind" json:"defecation_state,omitempty"`
	CurrentProduct  string                      `protobuf:"bytes,3,opt,name=current_product,json=currentProduct,proto3" json:"current_product,omitempty"`
	CurrentStage    pb.Stage                    `protobuf:"varint,4,opt,name=current_stage,json=currentStage,proto3,enum=tgbase.products.v1.Stage" json:"current_stage,omitempty"`
	StageStartedAt  *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=stage_started_at,json=stageStartedAt,proto3" json:"stage_started_at,omitempty"`
	CheckinAsked    bool                        `protobuf:"varint,6,opt,name=checkin_asked,json=checkinAsked,proto3" json:"checkin_asked,omitempty"`
	OfferedProducts []string                    `protobuf:"bytes,7,rep,name=offered_products,json=offeredProducts,proto3" json:"offered_products,omitempty"`
	Products        map[string]*ProductProgress `protobuf:"bytes,8,rep,name=products,proto3" json:"products,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ChatId          int64                       `protobuf:"varint,9,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	EnteredAt       *timestamppb.Timestamp      `protobuf:"bytes,10,opt,name=entered_at,json=enteredAt,proto3" json:"entered_at,omitempty"`
	ReminderSent    bool                        `protobuf:"varint,11,opt,name=reminder_sent,json=reminderSent,proto3" json:"reminder_sent,omitempty"`
	Locale          string                      `protobuf:"bytes,12,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *UserData) GetState() StateKind {
	if x != nil {
		return x.State
	}
	return StateKind_STATE_UNSPECIFIED
}

func (x *UserData) GetDefecationState() DefecationKind {
	if x != nil {
		return x.DefecationState
	}
	return DefecationKind_DEFECATION_UNSPECIFIED
}

func (x *UserData) GetCurrentProduct() string {
	if x != nil {
		return x.CurrentProduct
	}
	return ""
}

func (x *UserData) GetCurrentStage() pb.Stage {
	if x != nil {
		return x.CurrentStage
	}
	return pb.Stage(0)
}

func (x *UserData) GetStageStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StageStartedAt
	}
	return nil
}

func (x *UserData) GetCheckinAsked() bool {
	if x != nil {
		return x.CheckinAsked
	}
	return false
}

func (x *UserData) GetOfferedProducts() []string {
	if x != nil {
		return x.OfferedProducts
	}
	return nil
}

func (x *UserData) GetProducts() map[string]*ProductProgress {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *UserData) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *UserData) GetEnteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnteredAt
	}
	return nil
}

func (x *UserData) GetReminderSent() bool {
	if x != nil {
		return x.ReminderSent
	}
	return false
}

func (x *UserData) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type UserMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         map[int64]*UserData    `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMap) Reset() {
	*x = UserMap{}
	mi := &file_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMap) ProtoMessage() {}

func (x *UserMap) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMap.ProtoReflect.Descriptor instead.
func (*UserMap) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

func (x *UserMap) GetUsers() map[int64]*UserData {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\x0ftgbase.state.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0eproducts.proto\"\x9e\x01\n" +
	"\x0fProductProgress\x128\n" +
	"\n" +
	"last_stage\x18\x01 \x01(\x0e2\x19.tgbase.products.v1.StageR\tlastStage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbc\x05\n" +
	"\bUserData\x120\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1a.tgbase.state.v1.StateKindR\x05state\x12J\n" +
	"\x10defecation_state\x18\x02 \x01(\x0e2\x1f.tgbase.state.v1.DefecationKindR\x0fdefecationState\x12'\n" +
	"\x0fcurrent_product\x18\x03 \x01(\tR\x0ecurrentProduct\x12>\n" +
	"\rcurrent_stage\x18\x04 \x01(\x0e2\x19.tgbase.products.v1.StageR\fcurrentStage\x12D\n" +
	"\x10stage_started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0estageStartedAt\x12#\n" +
	"\rcheckin_asked\x18\x06 \x01(\bR\fcheckinAsked\x12)\n" +
	"\x10offered_products\x18\a \x03(\tR\x0fofferedProducts\x12C\n" +
	"\bproducts\x18\b \x03(\v2'.tgbase.state.v1.UserData.ProductsEntryR\bproducts\x12\x17\n" +
	"\achat_id\x18\t \x01(\x03R\x06chatId\x129\n" +
	"\n" +
	"entered_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tenteredAt\x12#\n" +
	"\rreminder_sent\x18\v \x01(\bR\freminderSent\x12\x16\n" +
	"\x06locale\x18\f \x01(\tR\x06locale\x1a]\n" +
	"\rProductsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .tgbase.state.v1.ProductProgressR\x05value:\x028\x01\"\x99\x01\n" +
	"\aUserMap\x129\n" +
	"\x05users\x18\x01 \x03(\v2#.tgbase.state.v1.UserMap.UsersEntryR\x05users\x1aS\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.tgbase.state.v1.UserDataR\x05value:\x028\x01*\x96\x01\n" +
	"\tStateKind\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_IDLE\x10\x01\x12\x1d\n" +
	"\x19STATE_AWAITING_DEFECATION\x10\x02\x12!\n" +
	"\x1dSTATE_AWAITING_PRODUCT_CHOICE\x10\x03\x12 \n" +
	"\x1cSTATE_AWAITING_STAGE_CHECKIN\x10\x04*p\n" +
	"\x0eDefecationKind\x12\x1a\n" +
	"\x16DEFECATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DEFECATION_FLUID\x10\x01\x12\x15\n" +
	"\x11DEFECATION_NORMAL\x10\x02\x12\x15\n" +
	"\x11DEFECATION_ISSUES\x10\x03B2Z0github.com/padington/tgbase/internal/state/pb;pbb\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_state_proto_goTypes = []any{
	(StateKind)(0),                // 0: tgbase.state.v1.StateKind
	(DefecationKind)(0),           // 1: tgbase.state.v1.DefecationKind
	(*ProductProgress)(nil),       // 2: tgbase.state.v1.ProductProgress
	(*UserData)(nil),              // 3: tgbase.state.v1.UserData
	(*UserMap)(nil),               // 4: tgbase.state.v1.UserMap
	nil,                           // 5: tgbase.state.v1.UserData.ProductsEntry
	nil,                           // 6: tgbase.state.v1.UserMap.UsersEntry
	(pb.Stage)(0),                 // 7: tgbase.products.v1.Stage
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_state_proto_depIdxs = []int32{
	7,  // 0: tgbase.state.v1.ProductProgress.last_stage:type_name -> tgbase.products.v1.Stage
	8,  // 1: tgbase.state.v1.ProductProgress.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: tgbase.state.v1.UserData.state:type_name -> tgbase.state.v1.StateKind
	1,  // 3: tgbase.state.v1.UserData.defecation_state:type_name -> tgbase.state.v1.DefecationKind
	7,  // 4: tgbase.state.v1.UserData.current_stage:type_name -> tgbase.products.v1.Stage
	8,  // 5: tgbase.state.v1.UserData.stage_started_at:type_name -> google.protobuf.Timestamp
	5,  // 6: tgbase.state.v1.UserData.products:type_name -> tgbase.state.v1.UserData.ProductsEntry
	8,  // 7: tgbase.state.v1.UserData.entered_at:type_name -> google.protobuf.Timestamp
	6,  // 8: tgbase.state.v1.UserMap.users:type_name -> tgbase.state.v1.UserMap.UsersEntry
	2,  // 9: tgbase.state.v1.UserData.ProductsEntry.value:type_name -> tgbase.state.v1.ProductProgress
	3,  // 10: tgbase.state.v1.UserMap.UsersEntry.value:type_name -> tgbase.state.v1.UserData
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		EnumInfos:         file_state_proto_enumTypes,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
