package screening

// Pushup-track content and program engine: the bundle type, its loader and
// validator, plus the pure functions that turn ONE number — the base B, i.e.
// the last max-test result — into a session plan, an outcome and a weekly
// base change.
//
// Two things make this bundle different from the screening bundles next
// door. First, it carries no third-party instrument: the whole scheme is our
// own implementation of the widely known "max test → individual load →
// several sets with an open last one → retest" pattern, and every number the
// user sees is GENERATED by the formulas below from the parameters in
// pushups_ru.yaml. No table is copied from anywhere — see the yaml header.
// Second, the numbers are load, not score, so the code carries a volume
// ceiling the user never sees (an untrained person doing a naive "as many as
// you can" challenge is the documented overload risk).
//
// Everything here is pure: no clock, no persistence, no Telegram. The state
// (base, week index, effort adjustment) lives in internal/state and is
// passed in.

import (
	"fmt"
	"math"
	"path/filepath"
	"strings"
)

// pushupsFile is the file name LoadPushups expects inside its content dir.
const pushupsFile = "pushups_ru.yaml"

// Session outcomes. A short session is still a completed session — the track
// never blocks progress on it, it only counts toward the weekly rule.
const (
	PushupOutcomeOver  = "over"  // every fixed set done and the open set beat its floor by over_margin
	PushupOutcomePlan  = "plan"  // every fixed set done and the open set reached its floor
	PushupOutcomeShort = "short" // a fixed set missed, or the open set below its floor
)

// Week progression kinds (what ProgressWeek did to the base).
const (
	PushupWeekStrong = "strong" // two or more "over" and no "short"
	PushupWeekSteady = "steady" // no "short"
	PushupWeekHold   = "hold"   // exactly one "short" — base unchanged, week NOT repeated
	PushupWeekRepeat = "repeat" // two or more "short" — base lowered, week repeated
)

// Track goals. The goal branches the plateau logic for the whole life of the
// track, so it is asked once, before the first test.
const (
	PushupGoalReps     = "reps"
	PushupGoalStrength = "strength"
)

// Effort answers of the single post-session question.
const (
	PushupEffortHard = "hard"
	PushupEffortOK   = "ok"
	PushupEffortEasy = "easy"
)

// Gate actions — what a "yes" to a gate question does.
const (
	PushupGateStop       = "stop"        // track does not start at all
	PushupGateEasier     = "easier"      // start joint_pain_step_down steps down the ladder
	PushupGateDoctorNote = "doctor_note" // "check with your doctor" + the easiest offered variation
)

// PushupVariation is one rung of the difficulty ladder. Offered marks the
// rungs the user may pick from in v1; the rest exist so a step down (pain,
// three repeated weeks) or a step up is gradual.
type PushupVariation struct {
	ID      string `yaml:"id"`
	Name    string `yaml:"name"`
	Hint    string `yaml:"hint"`
	Offered bool   `yaml:"offered"`
}

// PushupGateQuestion is one yes/no safety question.
type PushupGateQuestion struct {
	ID    string `yaml:"id"`
	Text  string `yaml:"text"`
	OnYes string `yaml:"on_yes"`
}

// PushupEffortParams are the three steps of the post-session self-report and
// the clamp they accumulate inside.
type PushupEffortParams struct {
	Hard float64 `yaml:"hard"`
	OK   float64 `yaml:"ok"`
	Easy float64 `yaml:"easy"`
	Min  float64 `yaml:"min"`
	Max  float64 `yaml:"max"`
}

// PushupProgressionParams are the weekly rule's numbers.
type PushupProgressionParams struct {
	OverMargin       int     `yaml:"over_margin"`
	StrongOverCount  int     `yaml:"strong_over_count"`
	RepeatShortCount int     `yaml:"repeat_short_count"`
	StrongShare      float64 `yaml:"strong_share"`
	StrongMin        int     `yaml:"strong_min"`
	SteadyShare      float64 `yaml:"steady_share"`
	SteadyMin        int     `yaml:"steady_min"`
	DropShare        float64 `yaml:"drop_share"`
	DropMin          int     `yaml:"drop_min"`
	RepeatForkAfter  int     `yaml:"repeat_fork_after"`
}

// PushupParams is the whole generator as data. Editing it changes the whole
// program without touching the logic — that is the point of keeping it in
// the yaml.
type PushupParams struct {
	MinBase      int `yaml:"min_base"`
	TooLowReps   int `yaml:"too_low_reps"`
	TestCap      int `yaml:"test_cap"`
	MaxRepsInput int `yaml:"max_reps_input"`
	SmallBaseMax int `yaml:"small_base_max"`

	DayFactors          []float64     `yaml:"day_factors"`
	WorkShare           float64       `yaml:"work_share"`
	OpenShare           float64       `yaml:"open_share"`
	SmallBaseOpenShare  float64       `yaml:"small_base_open_share"`
	SetCountThresholds  []int         `yaml:"set_count_thresholds"`
	SetCounts           []int         `yaml:"set_counts"`
	SetOffsets          map[int][]int `yaml:"set_offsets"`
	MinSetReps          int           `yaml:"min_set_reps"`
	SmallBaseMinSetReps int           `yaml:"small_base_min_set_reps"`
	OpenGap             int           `yaml:"open_gap"`
	SmallBaseOpenGap    int           `yaml:"small_base_open_gap"`

	RestSeconds      []int `yaml:"rest_seconds"`
	RestFloorSeconds int   `yaml:"rest_floor_seconds"`
	RestCutSeconds   int   `yaml:"rest_cut_seconds"`
	RestCutBase      int   `yaml:"rest_cut_base"`
	RestBonusStep    int   `yaml:"rest_bonus_step"`

	VolumeCapEarly    float64 `yaml:"volume_cap_early"`
	VolumeCap         float64 `yaml:"volume_cap"`
	EarlySessions     int     `yaml:"early_sessions"`
	DeloadFactor      float64 `yaml:"deload_factor"`
	RetestDeloadShare float64 `yaml:"retest_deload_share"`

	EffortAdj   PushupEffortParams      `yaml:"effort_adj"`
	Progression PushupProgressionParams `yaml:"progression"`

	SessionsPerWeek     int `yaml:"sessions_per_week"`
	RetestEverySessions int `yaml:"retest_every_sessions"`
	JointPainStepDown   int `yaml:"joint_pain_step_down"`
	MinHoursBetween     int `yaml:"min_hours_between"`
	AdvisedHoursBetween int `yaml:"advised_hours_between"`
	PauseRetestDays     int `yaml:"pause_retest_days"`
	PauseDeloadDays     int `yaml:"pause_deload_days"`
	SessionTTLHours     int `yaml:"session_ttl_hours"`
	HistoryCap          int `yaml:"history_cap"`
	LevelStep           int `yaml:"level_step"`
	LevelMax            int `yaml:"level_max"`
	SecondsPerRep       int `yaml:"seconds_per_rep"`
}

// PushupContent mirrors pushups_ru.yaml: every user-visible string of the
// track plus the generator parameters. All texts are the bot's own.
type PushupContent struct {
	Meta struct {
		Module     string `yaml:"module"`
		Version    int    `yaml:"version"`
		Language   string `yaml:"language"`
		Title      string `yaml:"title"`
		Disclaimer string `yaml:"disclaimer"` // the ONLY caveat users see
	} `yaml:"meta"`
	Consent struct {
		Title       string `yaml:"title"`
		Body        string `yaml:"body"`
		AgreeButton string `yaml:"agree_button"`
		LaterButton string `yaml:"later_button"`
		Declined    string `yaml:"declined"`
	} `yaml:"consent"`
	Gate struct {
		YesButton  string               `yaml:"yes_button"`
		NoButton   string               `yaml:"no_button"`
		Questions  []PushupGateQuestion `yaml:"questions"`
		StopScreen string               `yaml:"stop_screen"`
		EasierNote string               `yaml:"easier_note"`
		DoctorNote string               `yaml:"doctor_note"`
	} `yaml:"gate"`
	Goal struct {
		Prompt         string `yaml:"prompt"`
		RepsButton     string `yaml:"reps_button"`
		StrengthButton string `yaml:"strength_button"`
		RepsNote       string `yaml:"reps_note"`
		StrengthNote   string `yaml:"strength_note"`
	} `yaml:"goal"`
	Variations struct {
		Prompt    string            `yaml:"prompt"`
		Hint      string            `yaml:"hint"`
		DefaultID string            `yaml:"default_id"`
		Ladder    []PushupVariation `yaml:"ladder"`
	} `yaml:"variations"`
	Test struct {
		Intro       string   `yaml:"intro"`
		RepRules    []string `yaml:"rep_rules"`
		StopRules   []string `yaml:"stop_rules"`
		Prompt      string   `yaml:"prompt"`
		BadInput    string   `yaml:"bad_input"`
		ResultLine  string   `yaml:"result_line"` // "{reps} {base} {level}"
		PlanLine    string   `yaml:"plan_line"`   // "{sets} {minutes}"
		Capped      string   `yaml:"capped"`
		TooLow      string   `yaml:"too_low"`
		FloorNote   string   `yaml:"floor_note"`
		RetestIntro string   `yaml:"retest_intro"`
		CompareUp   string   `yaml:"compare_up"`
		CompareSame string   `yaml:"compare_same"`
		CompareDown string   `yaml:"compare_down"`
	} `yaml:"test"`
	Session struct {
		SetPrompt         string `yaml:"set_prompt"`
		OpenPrompt        string `yaml:"open_prompt"`
		Recorded          string `yaml:"recorded"`
		RestOver          string `yaml:"rest_over"`
		ReadyButton       string `yaml:"ready_button"`
		PauseButton       string `yaml:"pause_button"`
		StartButton       string `yaml:"start_button"`
		LaterButton       string `yaml:"later_button"`
		BadInput          string `yaml:"bad_input"`
		SummaryOver       string `yaml:"summary_over"`
		SummaryPlan       string `yaml:"summary_plan"`
		SummaryShort      string `yaml:"summary_short"`
		EffortPrompt      string `yaml:"effort_prompt"`
		EffortHardButton  string `yaml:"effort_hard_button"`
		EffortOKButton    string `yaml:"effort_ok_button"`
		EffortEasyButton  string `yaml:"effort_easy_button"`
		EffortHardReply   string `yaml:"effort_hard_reply"`
		EffortOKReply     string `yaml:"effort_ok_reply"`
		EffortEasyReply   string `yaml:"effort_easy_reply"`
		NextDue           string `yaml:"next_due"`
		RestDay           string `yaml:"rest_day"`
		TooSoon           string `yaml:"too_soon"`
		TrainAnywayButton string `yaml:"train_anyway_button"`
		Expired           string `yaml:"expired"`
	} `yaml:"session"`
	Week struct {
		ClosedSteady     string `yaml:"closed_steady"`
		ClosedStrong     string `yaml:"closed_strong"`
		ClosedHold       string `yaml:"closed_hold"`
		Repeat           string `yaml:"repeat"`
		ForkPrompt       string `yaml:"fork_prompt"`
		ForkEasierButton string `yaml:"fork_easier_button"`
		ForkRestButton   string `yaml:"fork_rest_button"`
		ForkEasierReply  string `yaml:"fork_easier_reply"`
		ForkRestReply    string `yaml:"fork_rest_reply"`
		RetestDue        string `yaml:"retest_due"`
	} `yaml:"week"`
	RedCard struct {
		Prompt          string   `yaml:"prompt"`
		Signs           []string `yaml:"signs"`
		YesButton       string   `yaml:"yes_button"`
		NoButton        string   `yaml:"no_button"`
		Body            string   `yaml:"body"`
		JointPainPrompt string   `yaml:"joint_pain_prompt"`
		JointPainReply  string   `yaml:"joint_pain_reply"`
	} `yaml:"red_card"`
	UI struct {
		ModeButton          string `yaml:"mode_button"`
		MenuPrompt          string `yaml:"menu_prompt"`
		TrainButton         string `yaml:"train_button"`
		ResumeButton        string `yaml:"resume_button"`
		ProgressButton      string `yaml:"progress_button"`
		RetestButton        string `yaml:"retest_button"`
		ProgressBase        string `yaml:"progress_base"`
		ProgressWeek        string `yaml:"progress_week"`
		ProgressTest        string `yaml:"progress_test"`
		ProgressOpen        string `yaml:"progress_open"`
		ProgressVolume      string `yaml:"progress_volume"`
		ProgressStreak      string `yaml:"progress_streak"`
		ReportLine          string `yaml:"report_line"`
		AbandonConfirmed    string `yaml:"abandon_confirmed"`
		DeleteConfirmPrompt string `yaml:"delete_confirm_prompt"`
		DeleteConfirmButton string `yaml:"delete_confirm_button"`
		DeleteCancelButton  string `yaml:"delete_cancel_button"`
		DeleteDone          string `yaml:"delete_done"`
		DeleteNothing       string `yaml:"delete_nothing"`
		DuePing             string `yaml:"due_ping"`
		OverduePing         string `yaml:"overdue_ping"`
	} `yaml:"ui"`
	Params PushupParams `yaml:"params"`
}

// LoadPushups reads the track's single content file from dir and validates
// it. Any structural deviation is an error — the bot must fail fast at
// startup rather than run with a broken generator.
func LoadPushups(dir string) (*PushupContent, error) {
	var c PushupContent
	if err := loadYAML(filepath.Join(dir, pushupsFile), &c); err != nil {
		return nil, err
	}
	if err := c.Validate(); err != nil {
		return nil, err
	}
	return &c, nil
}

// ─────────────────────────────────────────────────────────────────────────
// Program engine — pure functions over the base B.
// ─────────────────────────────────────────────────────────────────────────

// PlanInput is everything the generator needs. Only Base is required; the
// zero value of EffortAdj is read as "no adjustment yet" (1.0).
//
// SessionsDone selects the volume ceiling (the first EarlySessions sessions
// run under the strict one), and Deload marks the reduced week after a
// dropped retest or a long pause.
type PlanInput struct {
	Base         int
	DayIdx       int     // 0..len(day_factors)-1: easy / medium / hard day
	EffortAdj    float64 // accumulated self-report factor, clamped to [min,max]
	Goal         string  // PushupGoal*
	SessionsDone int
	Deload       bool
	RestBonusSec int // the one-off "+30 s to everything" the user may switch on
}

// PushupPlan is one generated session. Targets holds 4..7 numbers and the
// LAST one is the floor of the open set ("F+", do at least this many), which
// is why the slice is variable-length rather than five fields.
type PushupPlan struct {
	Targets []int
	RestSec int
	Work    int // W, the working number the fixed sets are built from
	Cap     int // the volume ceiling that was applied (reps per session)
}

// SetCount is the number of sets, fixed ones plus the open one.
func (p PushupPlan) SetCount() int { return len(p.Targets) }

// Fixed returns the fixed sets — everything but the open one.
func (p PushupPlan) Fixed() []int {
	if len(p.Targets) == 0 {
		return nil
	}
	return p.Targets[:len(p.Targets)-1]
}

// OpenFloor is the minimum of the open last set (0 for an empty plan).
func (p PushupPlan) OpenFloor() int {
	if len(p.Targets) == 0 {
		return 0
	}
	return p.Targets[len(p.Targets)-1]
}

// PlannedTotal is the session's planned volume: every fixed set plus the
// open set's floor. The actual total is at least this.
func (p PushupPlan) PlannedTotal() int {
	total := 0
	for _, n := range p.Targets {
		total += n
	}
	return total
}

// Plan generates the session for a base. It is deterministic and free of
// side effects: same input, same slice of numbers.
//
//	k = day_factors[d] × effort (× deload_factor on a reduced week)
//	W = max(min_set_reps, round(work_share × B × k))
//	F = max(W + open_gap, round(open_share × B × k))
//
// The fixed sets are W plus the offsets of set_offsets[n]; the open set's
// floor is F.
//
// The SHAPE of the session — how many sets it has — comes from the volume
// ceiling (see cappedOffsets) and depends on the base alone; k then scales
// the numbers inside that shape. That order matters: the ceiling is a safety
// limit the user never sees, and a limit that removed whole sets from the
// heavy day only would make the heavy day the lightest one of the week.
func (c *PushupContent) Plan(in PlanInput) PushupPlan {
	p := &c.Params

	base := in.Base
	if base < p.MinBase {
		base = p.MinBase
	}
	day := puClampInt(in.DayIdx, 0, len(p.DayFactors)-1)

	effort := in.EffortAdj
	if effort == 0 {
		effort = 1
	}
	effort = puClampFloat(effort, p.EffortAdj.Min, p.EffortAdj.Max)

	k := p.DayFactors[day] * effort
	if in.Deload {
		k *= p.DeloadFactor
	}

	capReps := c.volumeCap(base, in.SessionsDone)
	targets, work := c.buildSets(base, k, c.cappedOffsets(base, capReps))

	return PushupPlan{
		Targets: targets,
		RestSec: c.RestSeconds(base, day, in.Goal, in.RestBonusSec),
		Work:    work,
		Cap:     capReps,
	}
}

// buildSets renders the numbers of one session at intensity k: the fixed sets
// (the working number W plus each offset, never below the floor) and, last,
// the floor of the open set.
func (c *PushupContent) buildSets(base int, k float64, offsets []int) ([]int, int) {
	p := &c.Params

	minSet, openShare, gap := p.MinSetReps, p.OpenShare, p.OpenGap
	if base <= p.SmallBaseMax {
		minSet, openShare, gap = p.SmallBaseMinSetReps, p.SmallBaseOpenShare, p.SmallBaseOpenGap
	}

	work := puMaxInt(minSet, puRound(p.WorkShare*float64(base)*k))
	open := puMaxInt(work+gap, puRound(openShare*float64(base)*k))

	targets := make([]int, 0, len(offsets)+1)
	for _, off := range offsets {
		targets = append(targets, puMaxInt(minSet, work+off))
	}
	return append(targets, open), work
}

// volumeCap is the ceiling of one session — volume_cap(_early) × B, in reps.
// The early regime (the first early_sessions sessions) is the tighter one:
// that is the ramp-in an untrained person needs, and the documented overload
// risk of this exercise is exactly a big session done by someone detrained.
func (c *PushupContent) volumeCap(base, sessionsDone int) int {
	share := c.Params.VolumeCap
	if sessionsDone < c.Params.EarlySessions {
		share = c.Params.VolumeCapEarly
	}
	return puRound(share * float64(base))
}

// cappedOffsets is the session's shape: the set template the base earns,
// minus the sets the volume ceiling cannot afford. It drops the
// second-to-last FIXED set while the plan is over the ceiling, down to the
// smallest set count — dropping from the tail of the fixed block removes the
// lightest work first and always keeps the open set, the session's progress
// sensor.
//
// The decision is taken on the NEUTRAL session (k = 1) and therefore depends
// on the base and the ceiling alone. This is deliberate. Measuring the day's
// own plan against a ceiling that does not move with it inverts the week: at
// base 25 in the first six sessions, the fixed ceiling used to cut two sets
// off the hard day and none off the easy one, so the week ran 56 / 63 / 52
// reps — the "hard" day the lightest of the three. The self-report had the
// same cliff under it: "легко" raised k, the plan crossed the ceiling, a set
// was dropped and the NEXT session came out lighter, while the text promised
// it would be denser. With the shape fixed per base, k only scales numbers,
// so heavier input always means a heavier session.
//
// The ceiling thus bounds an average-intensity session at volume_cap × B;
// the hard day of a maximal self-report is heavier by its own factor
// (day_factors[last] × effort_adj.max ≈ 1.32 of it), which is the shape of a
// week rather than an escape from the limit.
//
// A plan may still exceed the ceiling once it is down to the minimum set
// count: at that point the load is already the base's own honest minimum and
// cutting further would leave nothing to train.
func (c *PushupContent) cappedOffsets(base, capReps int) []int {
	offsets := c.Params.SetOffsets[c.setCount(base)]
	minOffsets := c.Params.SetCounts[0] - 1 // the open set is not an offset
	for len(offsets) > minOffsets {
		neutral, _ := c.buildSets(base, 1, offsets)
		total := 0
		for _, n := range neutral {
			total += n
		}
		if total <= capReps {
			break
		}
		drop := len(offsets) - 2 // the second-to-last fixed set
		trimmed := make([]int, 0, len(offsets)-1)
		trimmed = append(trimmed, offsets[:drop]...)
		trimmed = append(trimmed, offsets[drop+1:]...)
		offsets = trimmed
	}
	return offsets
}

// setCount picks the number of sets for a base from the thresholds.
func (c *PushupContent) setCount(base int) int {
	p := &c.Params
	n := p.SetCounts[0]
	for i, threshold := range p.SetCountThresholds {
		if base >= threshold && i+1 < len(p.SetCounts) {
			n = p.SetCounts[i+1]
		}
	}
	return n
}

// RestSeconds is the rest between sets for a day. Goal "more reps" with a
// high base shortens it (but never below the floor); the user's one-off
// bonus is added on top. Resting LONGER is never a miss — the track only
// pings, it does not punish.
func (c *PushupContent) RestSeconds(base, dayIdx int, goal string, bonusSec int) int {
	p := &c.Params
	day := puClampInt(dayIdx, 0, len(p.RestSeconds)-1)
	rest := p.RestSeconds[day]
	if goal == PushupGoalReps && base >= p.RestCutBase {
		rest = puMaxInt(p.RestFloorSeconds, rest-p.RestCutSeconds)
	}
	if bonusSec > 0 {
		rest += bonusSec
	}
	return rest
}

// EstimateMinutes is the rough duration of a plan (working time plus rests),
// rounded up — the "≈ N minutes" of the session texts.
func (c *PushupContent) EstimateMinutes(plan PushupPlan) int {
	if plan.SetCount() == 0 {
		return 0
	}
	seconds := plan.PlannedTotal()*c.Params.SecondsPerRep + (plan.SetCount()-1)*plan.RestSec
	return int(math.Ceil(float64(seconds) / 60))
}

// Level is the cosmetic level shown next to the base: 1 + base/level_step,
// capped at level_max. It is derived, never stored.
func (c *PushupContent) Level(base int) int {
	if base < 0 {
		base = 0
	}
	return puClampInt(1+base/c.Params.LevelStep, 1, c.Params.LevelMax)
}

// ClassifySession maps a plan and what actually happened onto one of the
// three outcomes. actual is index-aligned with targets; missing entries
// count as zero, so an abandoned session classifies as PushupOutcomeShort
// instead of panicking.
//
//	every fixed set done AND open ≥ floor + over_margin → over
//	every fixed set done AND open ≥ floor               → plan
//	otherwise                                           → short
func (c *PushupContent) ClassifySession(targets, actual []int) string {
	if len(targets) == 0 {
		return PushupOutcomeShort
	}
	openIdx := len(targets) - 1
	for i := 0; i < openIdx; i++ {
		if answerAt(actual, i) < targets[i] {
			return PushupOutcomeShort
		}
	}
	got, floor := answerAt(actual, openIdx), targets[openIdx]
	switch {
	case got >= floor+c.Params.Progression.OverMargin:
		return PushupOutcomeOver
	case got >= floor:
		return PushupOutcomePlan
	default:
		return PushupOutcomeShort
	}
}

// PushupWeek is the verdict on a finished week: what happens to the base and
// whether the week is repeated. A repeat is ALWAYS announced out loud — a
// silent rollback reads as a bug.
type PushupWeek struct {
	Kind        string // PushupWeek*
	NewBase     int
	Delta       int // NewBase - base, may be negative
	Repeat      bool
	StreakGrows bool
}

// ProgressWeek applies the weekly rule to the week's outcomes. Progression
// follows the RESULT, not the calendar — the base is the only state, so
// there are no coverage holes between "columns" by construction.
//
//	≥ strong_over_count "over" and no "short" → +max(strong_min, strong_share × B)
//	no "short"                                → +max(steady_min, steady_share × B)
//	exactly one "short"                       → base unchanged, week NOT repeated
//	≥ repeat_short_count "short"              → −max(drop_min, drop_share × B), repeat
func (c *PushupContent) ProgressWeek(base int, outcomes []string) PushupWeek {
	pr := &c.Params.Progression
	if base < c.Params.MinBase {
		base = c.Params.MinBase
	}

	over, short := 0, 0
	for _, o := range outcomes {
		switch o {
		case PushupOutcomeOver:
			over++
		case PushupOutcomeShort:
			short++
		}
	}

	switch {
	case short >= pr.RepeatShortCount:
		drop := puMaxInt(pr.DropMin, puRound(pr.DropShare*float64(base)))
		newBase := puMaxInt(c.Params.MinBase, base-drop)
		return PushupWeek{
			Kind:    PushupWeekRepeat,
			NewBase: newBase,
			Delta:   newBase - base,
			Repeat:  true,
		}
	case short > 0:
		// One bad session is not a reason to redo the week.
		return PushupWeek{Kind: PushupWeekHold, NewBase: base, StreakGrows: true}
	case over >= pr.StrongOverCount:
		gain := puMaxInt(pr.StrongMin, puRound(pr.StrongShare*float64(base)))
		return PushupWeek{
			Kind: PushupWeekStrong, NewBase: base + gain, Delta: gain, StreakGrows: true,
		}
	default:
		gain := puMaxInt(pr.SteadyMin, puRound(pr.SteadyShare*float64(base)))
		return PushupWeek{
			Kind: PushupWeekSteady, NewBase: base + gain, Delta: gain, StreakGrows: true,
		}
	}
}

// PushupTestVerdict is what a max test means for the program.
type PushupTestVerdict struct {
	Base     int  // the new base
	Capped   bool // hit the test ceiling → offer a harder variation and retest
	TooLow   bool // at or below too_low_reps → the variation is too hard
	StepDown bool // TooLow and there is a lighter rung to step onto
}

// ClassifyTest turns a raw test result into the new base. Reps above the
// ceiling are capped (and the user is offered a harder variation instead of
// a longer set); a result at or below too_low_reps means the variation is
// too hard — step down the ladder and retest at once, or, when already on
// the easiest rung, just floor the base.
func (c *PushupContent) ClassifyTest(reps int, canStepDown bool) PushupTestVerdict {
	p := &c.Params
	v := PushupTestVerdict{}
	if reps >= p.TestCap {
		reps = p.TestCap
		v.Capped = true
	}
	if reps <= p.TooLowReps {
		v.TooLow = true
		v.StepDown = canStepDown
	}
	v.Base = puMaxInt(p.MinBase, reps)
	return v
}

// RetestNeedsDeload reports whether a retest dropped far enough below the
// old base to run one reduced week (instead of "rolling back to week N",
// which this track has no notion of).
func (c *PushupContent) RetestNeedsDeload(oldBase, newBase int) bool {
	if oldBase <= 0 {
		return false
	}
	return float64(newBase) < c.Params.RetestDeloadShare*float64(oldBase)
}

// NextEffortAdj accumulates the post-session self-report onto the current
// adjustment and clamps it. An unknown answer leaves the value untouched.
func (c *PushupContent) NextEffortAdj(current float64, answer string) float64 {
	e := &c.Params.EffortAdj
	if current == 0 {
		current = 1
	}
	step := 0.0
	switch answer {
	case PushupEffortHard:
		step = e.Hard
	case PushupEffortOK:
		step = e.OK
	case PushupEffortEasy:
		step = e.Easy
	}
	return puClampFloat(current+step, e.Min, e.Max)
}

// ─────────────────────────────────────────────────────────────────────────
// Ladder helpers (content-driven, pure).
// ─────────────────────────────────────────────────────────────────────────

// VariationIndex is the rung's position on the ladder, or -1 when unknown.
func (c *PushupContent) VariationIndex(id string) int {
	for i, v := range c.Variations.Ladder {
		if v.ID == id {
			return i
		}
	}
	return -1
}

// Variation returns the rung by id, or nil.
func (c *PushupContent) Variation(id string) *PushupVariation {
	if i := c.VariationIndex(id); i >= 0 {
		return &c.Variations.Ladder[i]
	}
	return nil
}

// ShiftVariation moves steps rungs along the ladder (negative = easier) and
// clamps at both ends. An unknown id returns the default rung.
func (c *PushupContent) ShiftVariation(id string, steps int) string {
	i := c.VariationIndex(id)
	if i < 0 {
		return c.Variations.DefaultID
	}
	return c.Variations.Ladder[puClampInt(i+steps, 0, len(c.Variations.Ladder)-1)].ID
}

// OfferedVariations are the rungs the user may pick from.
func (c *PushupContent) OfferedVariations() []PushupVariation {
	out := make([]PushupVariation, 0, len(c.Variations.Ladder))
	for _, v := range c.Variations.Ladder {
		if v.Offered {
			out = append(out, v)
		}
	}
	return out
}

// ─────────────────────────────────────────────────────────────────────────
// Validation
// ─────────────────────────────────────────────────────────────────────────

// canonicalPushupGate pins the three gate questions: their ids, their order
// and what a "yes" does. A file with a different gate is not the content
// this code was written for.
var canonicalPushupGate = []PushupGateQuestion{
	{ID: "health", OnYes: PushupGateStop},
	{ID: "joint_pain", OnYes: PushupGateEasier},
	{ID: "pregnancy", OnYes: PushupGateDoctorNote},
}

// Validate checks the bundle against the canonical shape and pins the
// generator's invariants. An error means "refuse to start".
func (c *PushupContent) Validate() error {
	if err := c.validatePushupTexts(); err != nil {
		return fmt.Errorf("screening: pushups: %w", err)
	}
	if err := c.validatePushupLadder(); err != nil {
		return fmt.Errorf("screening: pushups: ladder: %w", err)
	}
	if err := c.validatePushupParams(); err != nil {
		return fmt.Errorf("screening: pushups: params: %w", err)
	}
	if err := c.validatePushupBranding(); err != nil {
		return fmt.Errorf("screening: pushups: %w", err)
	}
	return nil
}

func (c *PushupContent) validatePushupTexts() error {
	for name, s := range c.userTexts() {
		if strings.TrimSpace(s) == "" {
			return fmt.Errorf("empty %s", name)
		}
	}
	if len(c.Test.RepRules) < 4 {
		return fmt.Errorf("want at least 4 rep rules, got %d", len(c.Test.RepRules))
	}
	if len(c.Test.StopRules) < 2 {
		return fmt.Errorf("want at least 2 stop rules, got %d", len(c.Test.StopRules))
	}
	if len(c.RedCard.Signs) < 4 {
		return fmt.Errorf("want at least 4 red-flag signs, got %d", len(c.RedCard.Signs))
	}
	if len(c.Gate.Questions) != len(canonicalPushupGate) {
		return fmt.Errorf("want %d gate questions, got %d", len(canonicalPushupGate), len(c.Gate.Questions))
	}
	for i, want := range canonicalPushupGate {
		got := c.Gate.Questions[i]
		if got.ID != want.ID || got.OnYes != want.OnYes {
			return fmt.Errorf("gate question %d is %s/%s, want %s/%s",
				i+1, got.ID, got.OnYes, want.ID, want.OnYes)
		}
	}
	return nil
}

func (c *PushupContent) validatePushupLadder() error {
	ladder := c.Variations.Ladder
	if len(ladder) < 4 {
		return fmt.Errorf("want at least 4 rungs, got %d", len(ladder))
	}
	seen := map[string]bool{}
	offered := 0
	for i, v := range ladder {
		if strings.TrimSpace(v.ID) == "" || strings.TrimSpace(v.Name) == "" {
			return fmt.Errorf("rung %d has an empty id or name", i+1)
		}
		if seen[v.ID] {
			return fmt.Errorf("duplicate rung %q", v.ID)
		}
		seen[v.ID] = true
		if v.Offered {
			offered++
		}
	}
	if offered < 2 {
		return fmt.Errorf("want at least 2 offered rungs, got %d", offered)
	}
	if c.VariationIndex(c.Variations.DefaultID) < 0 {
		return fmt.Errorf("default_id %q is not on the ladder", c.Variations.DefaultID)
	}
	return nil
}

func (c *PushupContent) validatePushupParams() error {
	p := &c.Params

	if p.MinBase < 1 {
		return fmt.Errorf("min_base must be >= 1, got %d", p.MinBase)
	}
	if p.TooLowReps < 0 || p.TooLowReps >= p.TestCap {
		return fmt.Errorf("too_low_reps %d is not below test_cap %d", p.TooLowReps, p.TestCap)
	}
	if p.TestCap < 20 || p.TestCap > p.MaxRepsInput {
		return fmt.Errorf("test_cap %d out of range (20..%d)", p.TestCap, p.MaxRepsInput)
	}
	if p.SmallBaseMax < p.MinBase {
		return fmt.Errorf("small_base_max %d below min_base %d", p.SmallBaseMax, p.MinBase)
	}

	if len(p.DayFactors) != p.SessionsPerWeek {
		return fmt.Errorf("want %d day factors, got %d", p.SessionsPerWeek, len(p.DayFactors))
	}
	for i, f := range p.DayFactors {
		if f <= 0 {
			return fmt.Errorf("day factor %d is %v", i, f)
		}
		if i > 0 && f <= p.DayFactors[i-1] {
			return fmt.Errorf("day factors must ascend: %v", p.DayFactors)
		}
	}
	if len(p.RestSeconds) != p.SessionsPerWeek {
		return fmt.Errorf("want %d rest values, got %d", p.SessionsPerWeek, len(p.RestSeconds))
	}
	for i, r := range p.RestSeconds {
		if r < p.RestFloorSeconds {
			return fmt.Errorf("rest %d (%ds) below the floor %ds", i, r, p.RestFloorSeconds)
		}
	}
	if p.RestFloorSeconds <= 0 || p.RestCutSeconds < 0 || p.RestBonusStep <= 0 {
		return fmt.Errorf("rest parameters must be positive")
	}

	if p.WorkShare <= 0 || p.WorkShare >= 1 {
		return fmt.Errorf("work_share %v out of range (0,1)", p.WorkShare)
	}
	if p.OpenShare <= p.WorkShare || p.OpenShare >= 1 {
		return fmt.Errorf("open_share %v must be above work_share and below 1", p.OpenShare)
	}
	if p.SmallBaseOpenShare < p.OpenShare {
		return fmt.Errorf("small_base_open_share %v below open_share %v", p.SmallBaseOpenShare, p.OpenShare)
	}
	if p.MinSetReps < 1 || p.SmallBaseMinSetReps < 1 || p.SmallBaseMinSetReps > p.MinSetReps {
		return fmt.Errorf("set-rep floors are inconsistent: %d / %d", p.MinSetReps, p.SmallBaseMinSetReps)
	}
	if p.OpenGap < 1 || p.SmallBaseOpenGap < 1 || p.SmallBaseOpenGap > p.OpenGap {
		return fmt.Errorf("open gaps are inconsistent: %d / %d", p.OpenGap, p.SmallBaseOpenGap)
	}

	if len(p.SetCounts) < 2 || len(p.SetCountThresholds) != len(p.SetCounts)-1 {
		return fmt.Errorf("want %d thresholds for %d set counts, got %d",
			len(p.SetCounts)-1, len(p.SetCounts), len(p.SetCountThresholds))
	}
	for i, n := range p.SetCounts {
		if n < 3 {
			return fmt.Errorf("set count %d is %d", i, n)
		}
		if i > 0 && n <= p.SetCounts[i-1] {
			return fmt.Errorf("set counts must ascend: %v", p.SetCounts)
		}
		offsets, ok := p.SetOffsets[n]
		if !ok {
			return fmt.Errorf("no set_offsets for %d sets", n)
		}
		if len(offsets) != n-1 {
			return fmt.Errorf("set_offsets[%d] has %d entries, want %d", n, len(offsets), n-1)
		}
		for j, off := range offsets {
			if off < -2 || off > 2 {
				return fmt.Errorf("set_offsets[%d][%d] = %d is out of range [-2,2]", n, j, off)
			}
		}
	}
	for i, t := range p.SetCountThresholds {
		if t <= 0 {
			return fmt.Errorf("threshold %d is %d", i, t)
		}
		if i > 0 && t <= p.SetCountThresholds[i-1] {
			return fmt.Errorf("thresholds must ascend: %v", p.SetCountThresholds)
		}
	}
	if len(p.SetOffsets) != len(p.SetCounts) {
		return fmt.Errorf("set_offsets has %d entries, want %d", len(p.SetOffsets), len(p.SetCounts))
	}

	if p.VolumeCapEarly <= 0 || p.VolumeCap <= p.VolumeCapEarly {
		return fmt.Errorf("volume ceilings are inconsistent: %v / %v", p.VolumeCapEarly, p.VolumeCap)
	}
	if p.EarlySessions <= 0 {
		return fmt.Errorf("early_sessions must be positive, got %d", p.EarlySessions)
	}
	if p.DeloadFactor <= 0 || p.DeloadFactor >= 1 {
		return fmt.Errorf("deload_factor %v out of range (0,1)", p.DeloadFactor)
	}
	if p.RetestDeloadShare <= 0 || p.RetestDeloadShare >= 1 {
		return fmt.Errorf("retest_deload_share %v out of range (0,1)", p.RetestDeloadShare)
	}

	e := &p.EffortAdj
	if e.Hard >= 0 || e.Easy <= 0 || e.OK != 0 {
		return fmt.Errorf("effort steps must be −/0/+, got %v/%v/%v", e.Hard, e.OK, e.Easy)
	}
	if e.Min >= 1 || e.Max <= 1 {
		return fmt.Errorf("effort clamp %v..%v must contain 1", e.Min, e.Max)
	}

	pr := &p.Progression
	if pr.OverMargin < 1 || pr.StrongOverCount < 1 || pr.RepeatShortCount < 2 {
		return fmt.Errorf("progression counters are inconsistent: %+v", *pr)
	}
	if pr.StrongShare <= pr.SteadyShare || pr.SteadyShare <= 0 {
		return fmt.Errorf("progression shares are inconsistent: %v / %v", pr.StrongShare, pr.SteadyShare)
	}
	if pr.StrongMin < pr.SteadyMin || pr.SteadyMin < 1 || pr.DropMin < 1 || pr.DropShare <= 0 {
		return fmt.Errorf("progression minimums are inconsistent: %+v", *pr)
	}
	if pr.RepeatForkAfter < 2 {
		return fmt.Errorf("repeat_fork_after must be >= 2, got %d", pr.RepeatForkAfter)
	}

	if p.RetestEverySessions < p.SessionsPerWeek {
		return fmt.Errorf("retest_every_sessions %d below a week", p.RetestEverySessions)
	}
	if p.JointPainStepDown < 1 {
		return fmt.Errorf("joint_pain_step_down must be >= 1, got %d", p.JointPainStepDown)
	}
	if p.MinHoursBetween < 1 || p.AdvisedHoursBetween < p.MinHoursBetween {
		return fmt.Errorf("recovery hours are inconsistent: %d / %d", p.MinHoursBetween, p.AdvisedHoursBetween)
	}
	if p.PauseRetestDays < 1 || p.PauseDeloadDays <= p.PauseRetestDays {
		return fmt.Errorf("pause thresholds are inconsistent: %d / %d", p.PauseRetestDays, p.PauseDeloadDays)
	}
	if p.SessionTTLHours < 1 || p.HistoryCap < 1 || p.LevelStep < 1 || p.LevelMax < 1 || p.SecondsPerRep < 1 {
		return fmt.Errorf("storage/level parameters must be positive")
	}
	return nil
}

// pushupSourceBranding is the branding of the commercial program this track
// deliberately does NOT copy. Assembled from bytes so this file itself never
// spells it out — same trick as forbiddenBranding in content.go.
var pushupSourceBranding = []string{
	string([]byte{'h', 'u', 'n', 'd', 'r', 'e', 'd', 'p', 'u', 's', 'h', 'u', 'p', 's'}),
	string([]byte{'s', 'p', 'e', 'i', 'r', 's'}),
	string([]byte{'o', 'n', 'e', ' ', 'h', 'u', 'n', 'd', 'r', 'e', 'd', ' ', 'p', 'u', 's', 'h'}),
}

// validatePushupBranding refuses content mentioning either the copyrighted
// third-party interview instrument (the repository-wide guard) or the
// commercial pushup program whose tables this track must never reproduce.
func (c *PushupContent) validatePushupBranding() error {
	for where, s := range c.userTexts() {
		low := strings.ToLower(s)
		if strings.Contains(low, forbiddenBranding) {
			return fmt.Errorf("%s contains forbidden instrument branding", where)
		}
		for _, needle := range pushupSourceBranding {
			if strings.Contains(low, needle) {
				return fmt.Errorf("%s names the commercial source program", where)
			}
		}
	}
	return nil
}

// userTexts is every user-visible string of the track, keyed by its place in
// the yaml. Validation, the canary tests and future guards all walk it, so a
// new text must be added here to be covered.
func (c *PushupContent) userTexts() map[string]string {
	out := map[string]string{
		"meta.title":                 c.Meta.Title,
		"meta.disclaimer":            c.Meta.Disclaimer,
		"consent.title":              c.Consent.Title,
		"consent.body":               c.Consent.Body,
		"consent.agree_button":       c.Consent.AgreeButton,
		"consent.later_button":       c.Consent.LaterButton,
		"consent.declined":           c.Consent.Declined,
		"gate.yes_button":            c.Gate.YesButton,
		"gate.no_button":             c.Gate.NoButton,
		"gate.stop_screen":           c.Gate.StopScreen,
		"gate.easier_note":           c.Gate.EasierNote,
		"gate.doctor_note":           c.Gate.DoctorNote,
		"goal.prompt":                c.Goal.Prompt,
		"goal.reps_button":           c.Goal.RepsButton,
		"goal.strength_button":       c.Goal.StrengthButton,
		"goal.reps_note":             c.Goal.RepsNote,
		"goal.strength_note":         c.Goal.StrengthNote,
		"variations.prompt":          c.Variations.Prompt,
		"variations.hint":            c.Variations.Hint,
		"test.intro":                 c.Test.Intro,
		"test.prompt":                c.Test.Prompt,
		"test.bad_input":             c.Test.BadInput,
		"test.result_line":           c.Test.ResultLine,
		"test.plan_line":             c.Test.PlanLine,
		"test.capped":                c.Test.Capped,
		"test.too_low":               c.Test.TooLow,
		"test.floor_note":            c.Test.FloorNote,
		"test.retest_intro":          c.Test.RetestIntro,
		"test.compare_up":            c.Test.CompareUp,
		"test.compare_same":          c.Test.CompareSame,
		"test.compare_down":          c.Test.CompareDown,
		"session.set_prompt":         c.Session.SetPrompt,
		"session.open_prompt":        c.Session.OpenPrompt,
		"session.recorded":           c.Session.Recorded,
		"session.rest_over":          c.Session.RestOver,
		"session.ready_button":       c.Session.ReadyButton,
		"session.pause_button":       c.Session.PauseButton,
		"session.start_button":       c.Session.StartButton,
		"session.later_button":       c.Session.LaterButton,
		"session.bad_input":          c.Session.BadInput,
		"session.summary_over":       c.Session.SummaryOver,
		"session.summary_plan":       c.Session.SummaryPlan,
		"session.summary_short":      c.Session.SummaryShort,
		"session.effort_prompt":      c.Session.EffortPrompt,
		"session.effort_hard_button": c.Session.EffortHardButton,
		"session.effort_ok_button":   c.Session.EffortOKButton,
		"session.effort_easy_button": c.Session.EffortEasyButton,
		"session.effort_hard_reply":  c.Session.EffortHardReply,
		"session.effort_ok_reply":    c.Session.EffortOKReply,
		"session.effort_easy_reply":  c.Session.EffortEasyReply,
		"session.next_due":           c.Session.NextDue,
		"session.rest_day":           c.Session.RestDay,
		"session.too_soon":           c.Session.TooSoon,
		"session.train_anyway":       c.Session.TrainAnywayButton,
		"session.expired":            c.Session.Expired,
		"week.closed_steady":         c.Week.ClosedSteady,
		"week.closed_strong":         c.Week.ClosedStrong,
		"week.closed_hold":           c.Week.ClosedHold,
		"week.repeat":                c.Week.Repeat,
		"week.fork_prompt":           c.Week.ForkPrompt,
		"week.fork_easier_button":    c.Week.ForkEasierButton,
		"week.fork_rest_button":      c.Week.ForkRestButton,
		"week.fork_easier_reply":     c.Week.ForkEasierReply,
		"week.fork_rest_reply":       c.Week.ForkRestReply,
		"week.retest_due":            c.Week.RetestDue,
		"red_card.prompt":            c.RedCard.Prompt,
		"red_card.yes_button":        c.RedCard.YesButton,
		"red_card.no_button":         c.RedCard.NoButton,
		"red_card.body":              c.RedCard.Body,
		"red_card.joint_pain_prompt": c.RedCard.JointPainPrompt,
		"red_card.joint_pain_reply":  c.RedCard.JointPainReply,
		"ui.mode_button":             c.UI.ModeButton,
		"ui.menu_prompt":             c.UI.MenuPrompt,
		"ui.train_button":            c.UI.TrainButton,
		"ui.resume_button":           c.UI.ResumeButton,
		"ui.progress_button":         c.UI.ProgressButton,
		"ui.retest_button":           c.UI.RetestButton,
		"ui.progress_base":           c.UI.ProgressBase,
		"ui.progress_week":           c.UI.ProgressWeek,
		"ui.progress_test":           c.UI.ProgressTest,
		"ui.progress_open":           c.UI.ProgressOpen,
		"ui.progress_volume":         c.UI.ProgressVolume,
		"ui.progress_streak":         c.UI.ProgressStreak,
		"ui.report_line":             c.UI.ReportLine,
		"ui.abandon_confirmed":       c.UI.AbandonConfirmed,
		"ui.delete_confirm_prompt":   c.UI.DeleteConfirmPrompt,
		"ui.delete_confirm_button":   c.UI.DeleteConfirmButton,
		"ui.delete_cancel_button":    c.UI.DeleteCancelButton,
		"ui.delete_done":             c.UI.DeleteDone,
		"ui.delete_nothing":          c.UI.DeleteNothing,
		"ui.due_ping":                c.UI.DuePing,
		"ui.overdue_ping":            c.UI.OverduePing,
	}
	for i, q := range c.Gate.Questions {
		out[fmt.Sprintf("gate.questions.%d", i+1)] = q.Text
	}
	for _, v := range c.Variations.Ladder {
		out[fmt.Sprintf("variations.ladder.%s.name", v.ID)] = v.Name
		out[fmt.Sprintf("variations.ladder.%s.hint", v.ID)] = v.Hint
	}
	for i, s := range c.Test.RepRules {
		out[fmt.Sprintf("test.rep_rules.%d", i+1)] = s
	}
	for i, s := range c.Test.StopRules {
		out[fmt.Sprintf("test.stop_rules.%d", i+1)] = s
	}
	for i, s := range c.RedCard.Signs {
		out[fmt.Sprintf("red_card.signs.%d", i+1)] = s
	}
	return out
}

// ─────────────────────────────────────────────────────────────────────────
// Small numeric helpers (package-private, pushup-scoped names).
// ─────────────────────────────────────────────────────────────────────────

func puRound(f float64) int { return int(math.Round(f)) }

func puMaxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func puClampInt(v, lo, hi int) int {
	if hi < lo {
		return lo
	}
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}

func puClampFloat(v, lo, hi float64) float64 {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}
