package screening

// Engine tests for the pushup track: the generator's properties over every
// base the program can reach, the session classifier, the weekly rule and
// the validator. The content is loaded from the bundled yaml (there is one
// file and it IS the parameter set — a synthetic bundle would only test a
// copy of it), and validator tests break exactly one field of the loaded
// struct.

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

func loadPushups(t *testing.T) *PushupContent {
	t.Helper()
	c, err := LoadPushups(canonicalDir)
	if err != nil {
		t.Fatalf("LoadPushups(%s): %v", canonicalDir, err)
	}
	return c
}

// planGrid walks every combination the program can produce: base 3..100
// (the whole reachable range — the track has no discrete columns, so there
// must be no gap), all three days, the whole effort clamp, both goals and
// both volume-ceiling regimes.
func planGrid(t *testing.T, c *PushupContent, visit func(in PlanInput, p PushupPlan)) {
	t.Helper()
	for _, sessions := range []int{0, 5, 6, 40} {
		for _, goal := range []string{PushupGoalReps, PushupGoalStrength} {
			for day := 0; day < len(c.Params.DayFactors); day++ {
				for _, effort := range []float64{0.85, 0.9, 1.0, 1.1, 1.15} {
					for _, deload := range []bool{false, true} {
						for base := 3; base <= 100; base++ {
							in := PlanInput{
								Base: base, DayIdx: day, EffortAdj: effort,
								Goal: goal, SessionsDone: sessions, Deload: deload,
							}
							visit(in, c.Plan(in))
						}
					}
				}
			}
		}
	}
}

// TestPushupPlan_DocumentedSession pins the shape of a mid-range session:
// four to seven sets, the second one heaviest among the fixed ones, the last
// one open. These numbers are GENERATED by the formulas from base 20 — they
// are not copied from anywhere, and the test exists so a change of the
// generator is a conscious act.
func TestPushupPlan_DocumentedSession(t *testing.T) {
	c := loadPushups(t)

	want := [][]int{
		{7, 8, 6, 6, 9},   // easy day
		{8, 9, 7, 7, 11},  // medium day
		{9, 10, 8, 8, 13}, // hard day
	}
	for day, sets := range want {
		p := c.Plan(PlanInput{Base: 20, DayIdx: day, EffortAdj: 1, Goal: PushupGoalStrength})
		if !reflect.DeepEqual(p.Targets, sets) {
			t.Errorf("day %d: plan for base 20 is %v, want %v", day, p.Targets, sets)
		}
		if got, want := p.RestSec, c.Params.RestSeconds[day]; got != want {
			t.Errorf("day %d: rest %ds, want %ds", day, got, want)
		}
	}
	// The whole week stays far below the volumes that make a beginner's
	// week a health risk: three sessions ≈ 6 × base, not 10–15 × base.
	week := 0
	for day := 0; day < 3; day++ {
		week += c.Plan(PlanInput{Base: 20, DayIdx: day, EffortAdj: 1}).PlannedTotal()
	}
	if week > 7*20 {
		t.Errorf("weekly volume for base 20 is %d reps (> 7 × base)", week)
	}
}

// TestPushupPlan_ShapeHoldsForEveryBase is the "no coverage holes" property:
// EVERY base from 3 to 100 produces a well-formed session — a set count from
// the content, every fixed set at or above its floor, and an open set whose
// floor keeps the documented distance from the working number. The original
// column-based schemes cannot say this; a single continuous base can.
func TestPushupPlan_ShapeHoldsForEveryBase(t *testing.T) {
	c := loadPushups(t)
	p := &c.Params

	planGrid(t, c, func(in PlanInput, plan PushupPlan) {
		n := plan.SetCount()
		if n < p.SetCounts[0] || n > p.SetCounts[len(p.SetCounts)-1] {
			t.Fatalf("base %d: %d sets, outside %v", in.Base, n, p.SetCounts)
		}
		if natural := c.setCount(in.Base); n > natural {
			t.Fatalf("base %d: %d sets, more than the %d the base earns", in.Base, n, natural)
		}

		minSet, gap := p.MinSetReps, p.OpenGap
		if in.Base <= p.SmallBaseMax {
			minSet, gap = p.SmallBaseMinSetReps, p.SmallBaseOpenGap
		}
		for i, reps := range plan.Fixed() {
			if reps < minSet {
				t.Fatalf("base %d: fixed set %d is %d reps, below the floor %d",
					in.Base, i+1, reps, minSet)
			}
		}
		if plan.OpenFloor() < plan.Work+gap {
			t.Fatalf("base %d: open floor %d is closer than %d to the working number %d",
				in.Base, plan.OpenFloor(), gap, plan.Work)
		}
		if plan.RestSec < p.RestFloorSeconds {
			t.Fatalf("base %d: rest %ds below the floor", in.Base, plan.RestSec)
		}
	})
}

// TestPushupPlan_VolumeCeiling is the overload guard: the planned volume
// never exceeds the ceiling of its regime — 2.5 × base for the first
// sessions, 3.5 × base afterwards. The one exception is a plan already down
// to the smallest set count, where there is nothing left to cut; that only
// happens on a small base, where the absolute numbers are tiny anyway.
func TestPushupPlan_VolumeCeiling(t *testing.T) {
	c := loadPushups(t)
	p := &c.Params

	planGrid(t, c, func(in PlanInput, plan PushupPlan) {
		wantCap := puRound(p.VolumeCap * float64(in.Base))
		if in.SessionsDone < p.EarlySessions {
			wantCap = puRound(p.VolumeCapEarly * float64(in.Base))
		}
		if plan.Cap != wantCap {
			t.Fatalf("base %d after %d sessions: ceiling %d, want %d",
				in.Base, in.SessionsDone, plan.Cap, wantCap)
		}
		if plan.PlannedTotal() <= plan.Cap {
			return
		}
		if plan.SetCount() != p.SetCounts[0] {
			t.Fatalf("base %d: %d reps over the ceiling %d with %d sets still to cut",
				in.Base, plan.PlannedTotal(), plan.Cap, plan.SetCount())
		}
		if in.Base > p.SmallBaseMax {
			t.Fatalf("base %d: ceiling %d broken (%d reps) outside the small-base corner",
				in.Base, plan.Cap, plan.PlannedTotal())
		}
	})

	// The early ceiling is the tighter of the two, for the same input.
	for base := 10; base <= 100; base += 10 {
		early := c.Plan(PlanInput{Base: base, DayIdx: 2, EffortAdj: 1.15, SessionsDone: 0})
		later := c.Plan(PlanInput{Base: base, DayIdx: 2, EffortAdj: 1.15, SessionsDone: p.EarlySessions})
		if early.PlannedTotal() > later.PlannedTotal() {
			t.Errorf("base %d: early session (%d reps) heavier than a later one (%d reps)",
				base, early.PlannedTotal(), later.PlannedTotal())
		}
	}
}

// TestPushupPlan_MonotonicInBase: a bigger base never means smaller numbers.
// The working number and the open set's floor rise with the base, and so
// does the planned volume whenever the set count stays put. The volume may
// step DOWN when the set count changes — that is the ceiling doing its job:
// heavier sets, fewer of them.
func TestPushupPlan_MonotonicInBase(t *testing.T) {
	c := loadPushups(t)

	for _, sessions := range []int{0, 40} {
		for day := 0; day < len(c.Params.DayFactors); day++ {
			for _, effort := range []float64{0.85, 1.0, 1.15} {
				var prev PushupPlan
				for base := 3; base <= 100; base++ {
					in := PlanInput{Base: base, DayIdx: day, EffortAdj: effort, SessionsDone: sessions}
					plan := c.Plan(in)
					if base > 3 {
						if plan.Work < prev.Work {
							t.Fatalf("base %d (day %d, effort %.2f): working number dropped %d → %d",
								base, day, effort, prev.Work, plan.Work)
						}
						if plan.OpenFloor() < prev.OpenFloor() {
							t.Fatalf("base %d (day %d, effort %.2f): open floor dropped %d → %d",
								base, day, effort, prev.OpenFloor(), plan.OpenFloor())
						}
						if plan.SetCount() == prev.SetCount() && plan.PlannedTotal() < prev.PlannedTotal() {
							t.Fatalf("base %d (day %d, effort %.2f): volume dropped %v → %v at the same set count",
								base, day, effort, prev.Targets, plan.Targets)
						}
					}
					prev = plan
				}
			}
		}
	}

	// The days of a week are ordered easy → medium → hard.
	for base := 5; base <= 60; base += 5 {
		var prev int
		for day := 0; day < 3; day++ {
			total := c.Plan(PlanInput{Base: base, DayIdx: day, EffortAdj: 1, SessionsDone: 40}).PlannedTotal()
			if day > 0 && total < prev {
				t.Errorf("base %d: day %d (%d reps) lighter than day %d (%d reps)", base, day, total, day-1, prev)
			}
			prev = total
		}
	}
}

// TestPushupPlan_Deterministic: same input, same plan — and the caller may
// keep the returned slice, since every call allocates its own.
func TestPushupPlan_Deterministic(t *testing.T) {
	c := loadPushups(t)
	in := PlanInput{Base: 23, DayIdx: 1, EffortAdj: 1.05, Goal: PushupGoalReps, SessionsDone: 9}

	first := c.Plan(in)
	second := c.Plan(in)
	if !reflect.DeepEqual(first, second) {
		t.Fatalf("two calls differ: %+v vs %+v", first, second)
	}

	first.Targets[0] = 999
	third := c.Plan(in)
	if third.Targets[0] == 999 {
		t.Error("the plan shares its backing array with the previous call")
	}
	if !reflect.DeepEqual(second, third) {
		t.Errorf("mutating a returned plan changed the next one: %+v vs %+v", second, third)
	}
}

// TestPushupPlan_EffortAndDeloadScale: the self-report moves the next
// session, and a deload week is lighter than the same week without it.
func TestPushupPlan_EffortAndDeloadScale(t *testing.T) {
	c := loadPushups(t)
	base := PlanInput{Base: 30, DayIdx: 1, EffortAdj: 1, SessionsDone: 40}

	hard := base
	hard.EffortAdj = c.Params.EffortAdj.Min
	easy := base
	easy.EffortAdj = c.Params.EffortAdj.Max
	deload := base
	deload.Deload = true

	normalTotal := c.Plan(base).PlannedTotal()
	if got := c.Plan(hard).PlannedTotal(); got >= normalTotal {
		t.Errorf("after a hard session the next one is %d reps, not below %d", got, normalTotal)
	}
	if got := c.Plan(easy).PlannedTotal(); got <= normalTotal {
		t.Errorf("after an easy session the next one is %d reps, not above %d", got, normalTotal)
	}
	if got := c.Plan(deload).PlannedTotal(); got >= normalTotal {
		t.Errorf("a deload session is %d reps, not below %d", got, normalTotal)
	}

	// A zero adjustment means "no self-report yet", not "zero load".
	unset := base
	unset.EffortAdj = 0
	if !reflect.DeepEqual(c.Plan(unset).Targets, c.Plan(base).Targets) {
		t.Error("an unset effort adjustment must behave like 1.0")
	}
	// Out-of-range values are clamped, not applied.
	wild := base
	wild.EffortAdj = 5
	if !reflect.DeepEqual(c.Plan(wild).Targets, c.Plan(easy).Targets) {
		t.Error("effort adjustment is not clamped to the content's range")
	}
}

func TestPushupRestSeconds(t *testing.T) {
	c := loadPushups(t)
	p := &c.Params

	for day, want := range p.RestSeconds {
		if got := c.RestSeconds(20, day, PushupGoalStrength, 0); got != want {
			t.Errorf("day %d: rest %ds, want %ds", day, got, want)
		}
	}
	// Goal "more reps" shortens the rest once the base is high — but never
	// below the floor, and only for that goal.
	high := p.RestCutBase
	for day := range p.RestSeconds {
		got := c.RestSeconds(high, day, PushupGoalReps, 0)
		want := puMaxInt(p.RestFloorSeconds, p.RestSeconds[day]-p.RestCutSeconds)
		if got != want {
			t.Errorf("day %d: reps-goal rest %ds, want %ds", day, got, want)
		}
		if got < p.RestFloorSeconds {
			t.Errorf("day %d: rest %ds below the floor %ds", day, got, p.RestFloorSeconds)
		}
		if strength := c.RestSeconds(high, day, PushupGoalStrength, 0); strength != p.RestSeconds[day] {
			t.Errorf("day %d: the strength goal must not shorten rest (%ds)", day, strength)
		}
	}
	if got := c.RestSeconds(high-1, 0, PushupGoalReps, 0); got != p.RestSeconds[0] {
		t.Errorf("below the cut base the rest must stay %ds, got %ds", p.RestSeconds[0], got)
	}
	// The one-off bonus is added on top of everything.
	if got, want := c.RestSeconds(20, 2, PushupGoalStrength, 30), p.RestSeconds[2]+30; got != want {
		t.Errorf("rest with a +30s bonus is %ds, want %ds", got, want)
	}
}

// TestPushupClassifySession is the outcome table. A short session is still a
// completed session — the third state exists explicitly and never blocks the
// program.
func TestPushupClassifySession(t *testing.T) {
	c := loadPushups(t)
	targets := []int{7, 8, 6, 6, 9} // the open set's floor is 9

	for _, tc := range []struct {
		name   string
		actual []int
		want   string
	}{
		{"open set two above the floor", []int{7, 8, 6, 6, 11}, PushupOutcomeOver},
		{"open set far above", []int{7, 8, 6, 6, 20}, PushupOutcomeOver},
		{"open set exactly at the floor", []int{7, 8, 6, 6, 9}, PushupOutcomePlan},
		{"open set one above", []int{7, 8, 6, 6, 10}, PushupOutcomePlan},
		{"extra reps in the fixed sets", []int{9, 9, 9, 9, 10}, PushupOutcomePlan},
		{"open set below the floor", []int{7, 8, 6, 6, 8}, PushupOutcomeShort},
		{"one fixed set missed", []int{7, 7, 6, 6, 20}, PushupOutcomeShort},
		{"last fixed set missed", []int{7, 8, 6, 5, 20}, PushupOutcomeShort},
		{"nothing done", []int{}, PushupOutcomeShort},
		{"abandoned mid-session", []int{7, 8}, PushupOutcomeShort},
		{"zero is an answer, not an error", []int{0, 0, 0, 0, 0}, PushupOutcomeShort},
	} {
		if got := c.ClassifySession(targets, tc.actual); got != tc.want {
			t.Errorf("%s: %q, want %q", tc.name, got, tc.want)
		}
	}

	if got := c.ClassifySession(nil, []int{10, 10}); got != PushupOutcomeShort {
		t.Errorf("an empty plan classifies as %q, want %q", got, PushupOutcomeShort)
	}
	// The margin comes from the content, not from a constant here.
	floorOnly := []int{5, 5 + c.Params.Progression.OverMargin}
	if got := c.ClassifySession([]int{5, 5}, floorOnly); got != PushupOutcomeOver {
		t.Errorf("floor + over_margin classifies as %q, want %q", got, PushupOutcomeOver)
	}
}

// TestPushupProgressWeek walks the weekly rule: two good sessions push the
// base, one bad session does NOT repeat the week, two do — and a repeat
// always lowers the base so the repeated week is genuinely easier.
func TestPushupProgressWeek(t *testing.T) {
	c := loadPushups(t)
	over, plan, short := PushupOutcomeOver, PushupOutcomePlan, PushupOutcomeShort

	for _, tc := range []struct {
		name        string
		base        int
		outcomes    []string
		wantKind    string
		wantBase    int
		wantRepeat  bool
		wantsStreak bool
	}{
		{"two over, none short", 25, []string{over, over, plan}, PushupWeekStrong, 27, false, true},
		{"three over", 50, []string{over, over, over}, PushupWeekStrong, 54, false, true},
		{"strong step has a floor of two", 10, []string{over, over, plan}, PushupWeekStrong, 12, false, true},
		{"one over is not enough", 25, []string{over, plan, plan}, PushupWeekSteady, 26, false, true},
		{"all on plan", 50, []string{plan, plan, plan}, PushupWeekSteady, 52, false, true},
		{"steady step has a floor of one", 5, []string{plan, plan, plan}, PushupWeekSteady, 6, false, true},
		{"one short holds the base", 25, []string{over, over, short}, PushupWeekHold, 25, false, true},
		{"one short after a plain week", 25, []string{plan, plan, short}, PushupWeekHold, 25, false, true},
		{"two short repeat the week", 25, []string{plan, short, short}, PushupWeekRepeat, 23, true, false},
		{"three short repeat the week", 50, []string{short, short, short}, PushupWeekRepeat, 46, true, false},
		{"a repeat never falls below the floor", 3, []string{short, short, short}, PushupWeekRepeat, 3, true, false},
		{"an empty week is a steady week", 20, nil, PushupWeekSteady, 21, false, true},
	} {
		got := c.ProgressWeek(tc.base, tc.outcomes)
		if got.Kind != tc.wantKind {
			t.Errorf("%s: kind %q, want %q", tc.name, got.Kind, tc.wantKind)
		}
		if got.NewBase != tc.wantBase {
			t.Errorf("%s: base %d → %d, want %d", tc.name, tc.base, got.NewBase, tc.wantBase)
		}
		if got.Delta != got.NewBase-tc.base {
			t.Errorf("%s: delta %d does not match %d → %d", tc.name, got.Delta, tc.base, got.NewBase)
		}
		if got.Repeat != tc.wantRepeat {
			t.Errorf("%s: repeat %v, want %v", tc.name, got.Repeat, tc.wantRepeat)
		}
		if got.StreakGrows != tc.wantsStreak {
			t.Errorf("%s: streak grows %v, want %v", tc.name, got.StreakGrows, tc.wantsStreak)
		}
	}

	// Across the whole reachable range: a repeat always lowers the base (or
	// sits on the floor) and a good week always raises it.
	for base := c.Params.MinBase; base <= 100; base++ {
		repeat := c.ProgressWeek(base, []string{short, short, plan})
		if repeat.NewBase >= base && base > c.Params.MinBase {
			t.Fatalf("base %d: a repeated week did not get easier (%d)", base, repeat.NewBase)
		}
		if repeat.NewBase < c.Params.MinBase {
			t.Fatalf("base %d: a repeat fell below the floor (%d)", base, repeat.NewBase)
		}
		if strong := c.ProgressWeek(base, []string{over, over, plan}); strong.NewBase <= base {
			t.Fatalf("base %d: a strong week did not raise the base (%d)", base, strong.NewBase)
		}
		if steady := c.ProgressWeek(base, []string{plan, plan, plan}); steady.NewBase <= base {
			t.Fatalf("base %d: a steady week did not raise the base (%d)", base, steady.NewBase)
		}
	}
	// A base below the floor is lifted onto it rather than trusted.
	if got := c.ProgressWeek(0, []string{plan, plan, plan}); got.NewBase <= c.Params.MinBase {
		t.Errorf("a broken base must be lifted onto the floor first, got %d", got.NewBase)
	}
}

func TestPushupLevel(t *testing.T) {
	c := loadPushups(t)
	step := c.Params.LevelStep

	for _, tc := range []struct{ base, want int }{
		{0, 1}, {1, 1}, {step - 1, 1}, {step, 2}, {2*step - 1, 2}, {2 * step, 3},
	} {
		if got := c.Level(tc.base); got != tc.want {
			t.Errorf("Level(%d) = %d, want %d", tc.base, got, tc.want)
		}
	}
	if got := c.Level(10000); got != c.Params.LevelMax {
		t.Errorf("Level is not capped: %d, want %d", got, c.Params.LevelMax)
	}
	prev := 0
	for base := 0; base <= 200; base++ {
		if got := c.Level(base); got < prev {
			t.Fatalf("Level(%d) = %d dropped below %d", base, got, prev)
		} else {
			prev = got
		}
	}
}

func TestPushupClassifyTest(t *testing.T) {
	c := loadPushups(t)
	p := &c.Params

	normal := c.ClassifyTest(17, true)
	if normal.Base != 17 || normal.Capped || normal.TooLow {
		t.Errorf("a plain result of 17 became %+v", normal)
	}

	capped := c.ClassifyTest(p.TestCap+40, true)
	if !capped.Capped || capped.Base != p.TestCap {
		t.Errorf("a result above the ceiling became %+v, want capped at %d", capped, p.TestCap)
	}
	if edge := c.ClassifyTest(p.TestCap-1, true); edge.Capped {
		t.Errorf("%d reps must not be capped", p.TestCap-1)
	}

	tooLow := c.ClassifyTest(p.TooLowReps, true)
	if !tooLow.TooLow || !tooLow.StepDown {
		t.Errorf("%d reps must step down the ladder, got %+v", p.TooLowReps, tooLow)
	}
	if tooLow.Base != p.MinBase {
		t.Errorf("a too-low result must floor the base at %d, got %d", p.MinBase, tooLow.Base)
	}
	if onEasiest := c.ClassifyTest(0, false); onEasiest.StepDown || onEasiest.Base != p.MinBase {
		t.Errorf("on the easiest rung there is nowhere to step down: %+v", onEasiest)
	}
	if ok := c.ClassifyTest(p.TooLowReps+1, true); ok.TooLow {
		t.Errorf("%d reps is a valid base, not a too-low result", p.TooLowReps+1)
	}
}

func TestPushupRetestNeedsDeload(t *testing.T) {
	c := loadPushups(t)
	for _, tc := range []struct {
		old, now int
		want     bool
	}{
		{20, 20, false},
		{20, 16, false}, // exactly the share — not below it
		{20, 15, true},
		{20, 25, false},
		{0, 3, false},
	} {
		if got := c.RetestNeedsDeload(tc.old, tc.now); got != tc.want {
			t.Errorf("RetestNeedsDeload(%d, %d) = %v, want %v", tc.old, tc.now, got, tc.want)
		}
	}
}

func TestPushupNextEffortAdj(t *testing.T) {
	c := loadPushups(t)
	e := &c.Params.EffortAdj

	if got := c.NextEffortAdj(1, PushupEffortHard); got != 1+e.Hard {
		t.Errorf("hard: %v, want %v", got, 1+e.Hard)
	}
	if got := c.NextEffortAdj(1, PushupEffortOK); got != 1 {
		t.Errorf("ok: %v, want 1", got)
	}
	if got := c.NextEffortAdj(1, PushupEffortEasy); got != 1+e.Easy {
		t.Errorf("easy: %v, want %v", got, 1+e.Easy)
	}
	if got := c.NextEffortAdj(0, PushupEffortOK); got != 1 {
		t.Errorf("an unset adjustment must start from 1, got %v", got)
	}
	if got := c.NextEffortAdj(1, "shrug"); got != 1 {
		t.Errorf("an unknown answer must not move the adjustment: %v", got)
	}

	// Accumulates, but stays inside the clamp however many times it is asked.
	v := 1.0
	for i := 0; i < 20; i++ {
		v = c.NextEffortAdj(v, PushupEffortEasy)
	}
	if v != e.Max {
		t.Errorf("twenty easy sessions gave %v, want the clamp %v", v, e.Max)
	}
	for i := 0; i < 20; i++ {
		v = c.NextEffortAdj(v, PushupEffortHard)
	}
	if v != e.Min {
		t.Errorf("twenty hard sessions gave %v, want the clamp %v", v, e.Min)
	}
}

func TestPushupVariationLadder(t *testing.T) {
	c := loadPushups(t)
	ladder := c.Variations.Ladder
	easiest, hardest := ladder[0].ID, ladder[len(ladder)-1].ID

	if c.VariationIndex("nope") != -1 {
		t.Error("an unknown rung must report -1")
	}
	if c.Variation("nope") != nil {
		t.Error("an unknown rung must resolve to nil")
	}
	if got := c.ShiftVariation("nope", -1); got != c.Variations.DefaultID {
		t.Errorf("an unknown rung must fall back to the default, got %q", got)
	}
	if got := c.ShiftVariation(easiest, -3); got != easiest {
		t.Errorf("stepping below the easiest rung gave %q", got)
	}
	if got := c.ShiftVariation(hardest, +3); got != hardest {
		t.Errorf("stepping above the hardest rung gave %q", got)
	}

	mid := c.Variations.DefaultID
	down := c.ShiftVariation(mid, -c.Params.JointPainStepDown)
	if c.VariationIndex(down) != c.VariationIndex(mid)-c.Params.JointPainStepDown {
		t.Errorf("a pain step down landed on %q", down)
	}
	if up := c.ShiftVariation(mid, +1); c.VariationIndex(up) != c.VariationIndex(mid)+1 {
		t.Errorf("a step up landed on %q", up)
	}

	offered := c.OfferedVariations()
	if len(offered) < 2 || len(offered) >= len(ladder) {
		t.Errorf("the pick list has %d of %d rungs", len(offered), len(ladder))
	}
	for _, v := range offered {
		if !v.Offered {
			t.Errorf("rung %q is in the pick list but not marked offered", v.ID)
		}
	}
}

func TestPushupEstimateMinutes(t *testing.T) {
	c := loadPushups(t)
	plan := c.Plan(PlanInput{Base: 20, DayIdx: 1, EffortAdj: 1})
	got := c.EstimateMinutes(plan)
	if got < 5 || got > 20 {
		t.Errorf("a base-20 session estimates at %d minutes", got)
	}
	if c.EstimateMinutes(PushupPlan{}) != 0 {
		t.Error("an empty plan must estimate at zero minutes")
	}
	heavier := c.EstimateMinutes(c.Plan(PlanInput{Base: 40, DayIdx: 2, EffortAdj: 1.15, SessionsDone: 40}))
	if heavier <= got {
		t.Errorf("a heavier session estimates at %d minutes, not above %d", heavier, got)
	}
}

// TestLoadPushups_RefusesBrokenContent breaks exactly one thing at a time in
// a loaded bundle and asserts the validator refuses it. The bot must fail at
// startup rather than generate load from a broken parameter set.
func TestLoadPushups_RefusesBrokenContent(t *testing.T) {
	for name, breakIt := range map[string]func(c *PushupContent){
		"missing text":          func(c *PushupContent) { c.Session.OpenPrompt = "  " },
		"missing disclaimer":    func(c *PushupContent) { c.Meta.Disclaimer = "" },
		"too few rep rules":     func(c *PushupContent) { c.Test.RepRules = c.Test.RepRules[:2] },
		"too few stop rules":    func(c *PushupContent) { c.Test.StopRules = nil },
		"too few red flags":     func(c *PushupContent) { c.RedCard.Signs = c.RedCard.Signs[:1] },
		"gate question dropped": func(c *PushupContent) { c.Gate.Questions = c.Gate.Questions[:2] },
		"gate question reordered": func(c *PushupContent) {
			c.Gate.Questions[0], c.Gate.Questions[2] = c.Gate.Questions[2], c.Gate.Questions[0]
		},
		"gate action softened":    func(c *PushupContent) { c.Gate.Questions[0].OnYes = PushupGateEasier },
		"duplicate rung":          func(c *PushupContent) { c.Variations.Ladder[1].ID = c.Variations.Ladder[0].ID },
		"unnamed rung":            func(c *PushupContent) { c.Variations.Ladder[2].Name = "" },
		"default off the ladder":  func(c *PushupContent) { c.Variations.DefaultID = "handstand" },
		"nothing to pick from":    func(c *PushupContent) { c.Variations.Ladder = c.Variations.Ladder[:1] },
		"open share below work":   func(c *PushupContent) { c.Params.OpenShare = c.Params.WorkShare / 2 },
		"work share above one":    func(c *PushupContent) { c.Params.WorkShare = 1.5 },
		"day factors unordered":   func(c *PushupContent) { c.Params.DayFactors = []float64{1.15, 1.0, 0.85} },
		"day factor missing":      func(c *PushupContent) { c.Params.DayFactors = c.Params.DayFactors[:2] },
		"rest below its floor":    func(c *PushupContent) { c.Params.RestSeconds[0] = 10 },
		"offsets out of range":    func(c *PushupContent) { c.Params.SetOffsets[5][1] = 7 },
		"offsets missing":         func(c *PushupContent) { delete(c.Params.SetOffsets, 7) },
		"offsets wrong length":    func(c *PushupContent) { c.Params.SetOffsets[5] = []int{0, 1} },
		"set counts unordered":    func(c *PushupContent) { c.Params.SetCounts = []int{7, 6, 5, 4} },
		"thresholds unordered":    func(c *PushupContent) { c.Params.SetCountThresholds = []int{45, 25, 7} },
		"ceilings inverted":       func(c *PushupContent) { c.Params.VolumeCap = c.Params.VolumeCapEarly / 2 },
		"ceiling removed":         func(c *PushupContent) { c.Params.VolumeCapEarly = 0 },
		"deload above one":        func(c *PushupContent) { c.Params.DeloadFactor = 1.4 },
		"effort steps flipped":    func(c *PushupContent) { c.Params.EffortAdj.Hard = 0.1 },
		"effort clamp excludes 1": func(c *PushupContent) { c.Params.EffortAdj.Max = 0.9 },
		"repeat after one short":  func(c *PushupContent) { c.Params.Progression.RepeatShortCount = 1 },
		"steady above strong":     func(c *PushupContent) { c.Params.Progression.SteadyShare = 0.5 },
		"recovery window gone":    func(c *PushupContent) { c.Params.MinHoursBetween = 0 },
		"pause thresholds cross":  func(c *PushupContent) { c.Params.PauseDeloadDays = 1 },
		"level step removed":      func(c *PushupContent) { c.Params.LevelStep = 0 },
		"test ceiling removed":    func(c *PushupContent) { c.Params.TestCap = 0 },
		"source branding leaked": func(c *PushupContent) {
			c.Consent.Body = "Программа " + pushupSourceBranding[0] + " для всех."
		},
		"forbidden branding leaked": func(c *PushupContent) {
			c.UI.MenuPrompt = "Опросник " + forbiddenBranding
		},
	} {
		t.Run(name, func(t *testing.T) {
			c := loadPushups(t)
			breakIt(c)
			if err := c.Validate(); err == nil {
				t.Fatal("Validate accepted broken content")
			}
		})
	}
}

func TestLoadPushups_MissingFile(t *testing.T) {
	dir := t.TempDir()
	if _, err := LoadPushups(dir); err == nil {
		t.Fatal("LoadPushups accepted an empty directory")
	}
}

func TestLoadPushups_RefusesUnparsableFile(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, pushupsFile), []byte("meta: [broken\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := LoadPushups(dir); err == nil {
		t.Fatal("LoadPushups accepted a broken yaml")
	}
}
