// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: settings.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Settings struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DefecationReminderAfter *durationpb.Duration   `protobuf:"bytes,1,opt,name=defecation_reminder_after,json=defecationReminderAfter,proto3" json:"defecation_reminder_after,omitempty"`
	CheckinInterval         *durationpb.Duration   `protobuf:"bytes,2,opt,name=checkin_interval,json=checkinInterval,proto3" json:"checkin_interval,omitempty"`
	ScanInterval            *durationpb.Duration   `protobuf:"bytes,3,opt,name=scan_interval,json=scanInterval,proto3" json:"scan_interval,omitempty"`
	DefaultLocale           string                 `protobuf:"bytes,4,opt,name=default_locale,json=defaultLocale,proto3" json:"default_locale,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{0}
}

func (x *Settings) GetDefecationReminderAfter() *durationpb.Duration {
	if x != nil {
		return x.DefecationReminderAfter
	}
	return nil
}

func (x *Settings) GetCheckinInterval() *durationpb.Duration {
	if x != nil {
		return x.CheckinInterval
	}
	return nil
}

func (x *Settings) GetScanInterval() *durationpb.Duration {
	if x != nil {
		return x.ScanInterval
	}
	return nil
}

func (x *Settings) GetDefaultLocale() string {
	if x != nil {
		return x.DefaultLocale
	}
	return ""
}

var File_settings_proto protoreflect.FileDescriptor

const file_settings_proto_rawDesc = "" +
	"\n" +
	"\x0esettings.proto\x12\x12tgbase.settings.v1\x1a\x1egoogle/protobuf/duration.proto\"\x8e\x02\n" +
	"\bSettings\x12U\n" +
	"\x19defecation_reminder_after\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x17defecationReminderAfter\x12D\n" +
	"\x10checkin_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0fcheckinInterval\x12>\n" +
	"\rscan_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\fscanInterval\x12%\n" +
	"\x0edefault_locale\x18\x04 \x01(\tR\rdefaultLocaleB5Z3github.com/padington/tgbase/internal/settings/pb;pbb\x06proto3"

var (
	file_settings_proto_rawDescOnce sync.Once
	file_settings_proto_rawDescData []byte
)

func file_settings_proto_rawDescGZIP() []byte {
	file_settings_proto_rawDescOnce.Do(func() {
		file_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)))
	})
	return file_settings_proto_rawDescData
}

var file_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_settings_proto_goTypes = []any{
	(*Settings)(nil),            // 0: tgbase.settings.v1.Settings
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
}
var file_settings_proto_depIdxs = []int32{
	1, // 0: tgbase.settings.v1.Settings.defecation_reminder_after:type_name -> google.protobuf.Duration
	1, // 1: tgbase.settings.v1.Settings.checkin_interval:type_name -> google.protobuf.Duration
	1, // 2: tgbase.settings.v1.Settings.scan_interval:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_settings_proto_init() }
func file_settings_proto_init() {
	if File_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settings_proto_goTypes,
		DependencyIndexes: file_settings_proto_depIdxs,
		MessageInfos:      file_settings_proto_msgTypes,
	}.Build()
	File_settings_proto = out.File
	file_settings_proto_goTypes = nil
	file_settings_proto_depIdxs = nil
}
