// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: products.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FodmapLevel int32

const (
	FodmapLevel_FODMAP_UNSPECIFIED FodmapLevel = 0
	FodmapLevel_FODMAP_LOW         FodmapLevel = 1
	FodmapLevel_FODMAP_HIGH        FodmapLevel = 2
)

// Enum value maps for FodmapLevel.
var (
	FodmapLevel_name = map[int32]string{
		0: "FODMAP_UNSPECIFIED",
		1: "FODMAP_LOW",
		2: "FODMAP_HIGH",
	}
	FodmapLevel_value = map[string]int32{
		"FODMAP_UNSPECIFIED": 0,
		"FODMAP_LOW":         1,
		"FODMAP_HIGH":        2,
	}
)

func (x FodmapLevel) Enum() *FodmapLevel {
	p := new(FodmapLevel)
	*p = x
	return p
}

func (x FodmapLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FodmapLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_products_proto_enumTypes[0].Descriptor()
}

func (FodmapLevel) Type() protoreflect.EnumType {
	return &file_products_proto_enumTypes[0]
}

func (x FodmapLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FodmapLevel.Descriptor instead.
func (FodmapLevel) EnumDescriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{0}
}

type Measure int32

const (
	Measure_MEASURE_UNSPECIFIED Measure = 0
	Measure_MEASURE_PIECES      Measure = 1
	Measure_MEASURE_GRAMS       Measure = 2
	Measure_MEASURE_ML          Measure = 3
	Measure_MEASURE_SPOONS      Measure = 4
)

// Enum value maps for Measure.
var (
	Measure_name = map[int32]string{
		0: "MEASURE_UNSPECIFIED",
		1: "MEASURE_PIECES",
		2: "MEASURE_GRAMS",
		3: "MEASURE_ML",
		4: "MEASURE_SPOONS",
	}
	Measure_value = map[string]int32{
		"MEASURE_UNSPECIFIED": 0,
		"MEASURE_PIECES":      1,
		"MEASURE_GRAMS":       2,
		"MEASURE_ML":          3,
		"MEASURE_SPOONS":      4,
	}
)

func (x Measure) Enum() *Measure {
	p := new(Measure)
	*p = x
	return p
}

func (x Measure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Measure) Descriptor() protoreflect.EnumDescriptor {
	return file_products_proto_enumTypes[1].Descriptor()
}

func (Measure) Type() protoreflect.EnumType {
	return &file_products_proto_enumTypes[1]
}

func (x Measure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Measure.Descriptor instead.
func (Measure) EnumDescriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{1}
}

type Stage int32

const (
	Stage_STAGE_UNSPECIFIED Stage = 0
	Stage_STAGE_LOW         Stage = 1
	Stage_STAGE_MEDIUM      Stage = 2
	Stage_STAGE_HIGH        Stage = 3
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "STAGE_LOW",
		2: "STAGE_MEDIUM",
		3: "STAGE_HIGH",
	}
	Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED": 0,
		"STAGE_LOW":         1,
		"STAGE_MEDIUM":      2,
		"STAGE_HIGH":        3,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_products_proto_enumTypes[2].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_products_proto_enumTypes[2]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{2}
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fodmap        FodmapLevel            `protobuf:"varint,2,opt,name=fodmap,proto3,enum=tgbase.products.v1.FodmapLevel" json:"fodmap,omitempty"`
	Measure       Measure                `protobuf:"varint,3,opt,name=measure,proto3,enum=tgbase.products.v1.Measure" json:"measure,omitempty"`
	Stages        map[string]float64     `protobuf:"bytes,4,rep,name=stages,proto3" json:"stages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	NameLocalized map[string]string      `protobuf:"bytes,6,rep,name=name_localized,json=nameLocalized,proto3" json:"name_localized,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NoteLocalized map[string]string      `protobuf:"bytes,7,rep,name=note_localized,json=noteLocalized,proto3" json:"note_localized,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Category      string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	Emoji         string                 `protobuf:"bytes,9,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetFodmap() FodmapLevel {
	if x != nil {
		return x.Fodmap
	}
	return FodmapLevel_FODMAP_UNSPECIFIED
}

func (x *Product) GetMeasure() Measure {
	if x != nil {
		return x.Measure
	}
	return Measure_MEASURE_UNSPECIFIED
}

func (x *Product) GetStages() map[string]float64 {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *Product) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Product) GetNameLocalized() map[string]string {
	if x != nil {
		return x.NameLocalized
	}
	return nil
}

func (x *Product) GetNoteLocalized() map[string]string {
	if x != nil {
		return x.NoteLocalized
	}
	return nil
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

// Category is a runtime-mutable bucket products can be browsed by.
// Definitions live in the same backend value as the catalog (see Catalog
// below), so admins can add or rename categories without a redeploy.
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Emoji         string                 `protobuf:"bytes,2,opt,name=emoji,proto3" json:"emoji,omitempty"`
	NameLocalized map[string]string      `protobuf:"bytes,3,rep,name=name_localized,json=nameLocalized,proto3" json:"name_localized,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *Category) GetNameLocalized() map[string]string {
	if x != nil {
		return x.NameLocalized
	}
	return nil
}

type Catalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Categories    []*Category            `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_products_proto_rawDescGZIP(), []int{2}
}

func (x *Catalog) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *Catalog) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_products_proto protoreflect.FileDescriptor

const file_products_proto_rawDesc = "" +
	"\n" +
	"\x0eproducts.proto\x12\x12tgbase.products.v1\"\x81\x05\n" +
	"\aProduct\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x06fodmap\x18\x02 \x01(\x0e2\x1f.tgbase.products.v1.FodmapLevelR\x06fodmap\x125\n" +
	"\ameasure\x18\x03 \x01(\x0e2\x1b.tgbase.products.v1.MeasureR\ameasure\x12?\n" +
	"\x06stages\x18\x04 \x03(\v2'.tgbase.products.v1.Product.StagesEntryR\x06stages\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12U\n" +
	"\x0ename_localized\x18\x06 \x03(\v2..tgbase.products.v1.Product.NameLocalizedEntryR\rnameLocalized\x12U\n" +
	"\x0enote_localized\x18\a \x03(\v2..tgbase.products.v1.Product.NoteLocalizedEntryR\rnoteLocalized\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12\x14\n" +
	"\x05emoji\x18\t \x01(\tR\x05emoji\x1a9\n" +
	"\vStagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a@\n" +
	"\x12NameLocalizedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12NoteLocalizedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05emoji\x18\x02 \x01(\tR\x05emoji\x12V\n" +
	"\x0ename_localized\x18\x03 \x03(\v2/.tgbase.products.v1.Category.NameLocalizedEntryR\rnameLocalized\x1a@\n" +
	"\x12NameLocalizedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\aCatalog\x127\n" +
	"\bproducts\x18\x01 \x03(\v2\x1b.tgbase.products.v1.ProductR\bproducts\x12<\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x1c.tgbase.products.v1.CategoryR\n" +
	"categories*F\n" +
	"\vFodmapLevel\x12\x16\n" +
	"\x12FODMAP_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"FODMAP_LOW\x10\x01\x12\x0f\n" +
	"\vFODMAP_HIGH\x10\x02*m\n" +
	"\aMeasure\x12\x17\n" +
	"\x13MEASURE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eMEASURE_PIECES\x10\x01\x12\x11\n" +
	"\rMEASURE_GRAMS\x10\x02\x12\x0e\n" +
	"\n" +
	"MEASURE_ML\x10\x03\x12\x12\n" +
	"\x0eMEASURE_SPOONS\x10\x04*O\n" +
	"\x05Stage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTAGE_LOW\x10\x01\x12\x10\n" +
	"\fSTAGE_MEDIUM\x10\x02\x12\x0e\n" +
	"\n" +
	"STAGE_HIGH\x10\x03B5Z3github.com/padington/tgbase/internal/products/pb;pbb\x06proto3"

var (
	file_products_proto_rawDescOnce sync.Once
	file_products_proto_rawDescData []byte
)

func file_products_proto_rawDescGZIP() []byte {
	file_products_proto_rawDescOnce.Do(func() {
		file_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_proto_rawDesc), len(file_products_proto_rawDesc)))
	})
	return file_products_proto_rawDescData
}

var file_products_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_products_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_products_proto_goTypes = []any{
	(FodmapLevel)(0), // 0: tgbase.products.v1.FodmapLevel
	(Measure)(0),     // 1: tgbase.products.v1.Measure
	(Stage)(0),       // 2: tgbase.products.v1.Stage
	(*Product)(nil),  // 3: tgbase.products.v1.Product
	(*Category)(nil), // 4: tgbase.products.v1.Category
	(*Catalog)(nil),  // 5: tgbase.products.v1.Catalog
	nil,              // 6: tgbase.products.v1.Product.StagesEntry
	nil,              // 7: tgbase.products.v1.Product.NameLocalizedEntry
	nil,              // 8: tgbase.products.v1.Product.NoteLocalizedEntry
	nil,              // 9: tgbase.products.v1.Category.NameLocalizedEntry
}
var file_products_proto_depIdxs = []int32{
	0, // 0: tgbase.products.v1.Product.fodmap:type_name -> tgbase.products.v1.FodmapLevel
	1, // 1: tgbase.products.v1.Product.measure:type_name -> tgbase.products.v1.Measure
	6, // 2: tgbase.products.v1.Product.stages:type_name -> tgbase.products.v1.Product.StagesEntry
	7, // 3: tgbase.products.v1.Product.name_localized:type_name -> tgbase.products.v1.Product.NameLocalizedEntry
	8, // 4: tgbase.products.v1.Product.note_localized:type_name -> tgbase.products.v1.Product.NoteLocalizedEntry
	9, // 5: tgbase.products.v1.Category.name_localized:type_name -> tgbase.products.v1.Category.NameLocalizedEntry
	3, // 6: tgbase.products.v1.Catalog.products:type_name -> tgbase.products.v1.Product
	4, // 7: tgbase.products.v1.Catalog.categories:type_name -> tgbase.products.v1.Category
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_products_proto_init() }
func file_products_proto_init() {
	if File_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_proto_rawDesc), len(file_products_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_products_proto_goTypes,
		DependencyIndexes: file_products_proto_depIdxs,
		EnumInfos:         file_products_proto_enumTypes,
		MessageInfos:      file_products_proto_msgTypes,
	}.Build()
	File_products_proto = out.File
	file_products_proto_goTypes = nil
	file_products_proto_depIdxs = nil
}
