package journey

import (
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/padington/tgbase/internal/screening"
	"github.com/padington/tgbase/internal/state"
)

// Helpers shared by the pushup-track phases (pu_*.go). Like the three
// self-check tracks next door, every user-visible string comes from the
// content bundle (screening.PushupContent) and reaches the user through the
// "scr.text" pass-through i18n key — nothing user-visible is hardcoded here.
// Generic helpers (normText, labelIs, renderContent, scrText, testExitState,
// deleteReturnState, homeLabel) are shared with scr_common.go and mode.go.
//
// What makes this track different from its neighbours: it drives a PROGRAM,
// not a questionnaire. Every rep count on screen is generated by
// screening.Plan from ONE number (the base), the session lives across
// messages with a server-side rest timer, and the track writes a history.
// The helpers below are therefore mostly about the session lifecycle
// (start → sets → rest → effort → week close) rather than about scales.

// puOverdueAfter is the gap between the two — and only two — pings of one
// due cycle: the first at NextDueAt ("time to train"), the second this much
// later ("the session is still waiting"). After the second the program stays
// silent until a session moves NextDueAt again.
const puOverdueAfter = 4 * 24 * time.Hour

// puConsentSampleBase is the base the consent card's "≈ N minutes" line is
// computed from. The user has no base yet at that point and the alternative
// would be a hardcoded number inside a text — this keeps every number in the
// track derived from the generator.
const puConsentSampleBase = 15

// puSparkChars is the eight-step ramp of the progress screen's text
// sparkline (no image libraries in v1, by decision).
var puSparkChars = []rune("▁▂▃▄▅▆▇█")

// puSparkPoints is how many open sets the sparkline shows.
const puSparkPoints = 8

// isPushupState reports whether kind is one of the pu_* states. A deliberate
// enumeration, not a lookup over registered phases: the answer must not
// depend on wiring.
func isPushupState(kind state.StateKind) bool {
	switch kind {
	case state.StatePuConsent,
		state.StatePuGate,
		state.StatePuGoal,
		state.StatePuVariation,
		state.StatePuTest,
		state.StatePuMenu,
		state.StatePuSet,
		state.StatePuRest,
		state.StatePuEffort,
		state.StatePuWeekFork,
		state.StatePuRedCard,
		state.StatePuProgress,
		state.StatePuDeleteConfirm:
		return true
	}
	return false
}

// resumablePuState reports whether kind is a position inside a running
// session that a pause can meaningfully return to. Only these are ever
// recorded as PushupSession.ResumeState — the setup chain (consent, gate,
// goal, variation), the menu, the progress screen and the confirmations are
// re-entered through the menu instead.
func resumablePuState(kind state.StateKind) bool {
	return kind == state.StatePuSet ||
		kind == state.StatePuRest ||
		kind == state.StatePuEffort
}

// hasPuConsent reports whether the single track-wide consent was given. A
// stored program implies it — the program is created by the consent itself.
func hasPuConsent(u state.UserData) bool {
	return u.PuConsentAt != nil || u.Pushups != nil
}

// hasPuData reports whether anything of the track is stored — the /pushups_delete gate.
func hasPuData(u state.UserData) bool {
	return hasPuConsent(u) || u.PuTest != nil || u.PuSession != nil || len(u.PuHistory) > 0
}

// puSessionTTL is the content-driven lifetime of an unfinished session.
func puSessionTTL(c *screening.PushupContent) time.Duration {
	return time.Duration(c.Params.SessionTTLHours) * time.Hour
}

// puActiveSession returns the unfinished session when it is still resumable,
// nil when there is none or it has outlived the TTL. A stale session is
// closed (as a partial one) by puExpireSession on the next track entry.
func puActiveSession(c *screening.PushupContent, u state.UserData, now time.Time) *state.PushupSession {
	if u.PuSession == nil || u.PuSession.Stale(now, puSessionTTL(c)) {
		return nil
	}
	return u.PuSession
}

// puWorkoutSession returns the active session only when it is an ordinary
// workout — the resume row and the resume target of a max test differ (a
// test is one number, so it is simply re-offered rather than resumed).
func puWorkoutSession(c *screening.PushupContent, u state.UserData, now time.Time) *state.PushupSession {
	s := puActiveSession(c, u, now)
	if s == nil || s.Kind != state.PushupSessionWorkout {
		return nil
	}
	return s
}

// puEntryState is where the track is entered (the landing button and
// /pushups). The position is DERIVED from the stored program rather than
// remembered, exactly like the self-checks derive a question index from the
// recorded answers: consent → safety gate → goal → variation → first test →
// menu. An open max test outranks all of them.
func puEntryState(c *screening.PushupContent, u state.UserData, now time.Time) state.StateKind {
	if s := puActiveSession(c, u, now); s != nil && s.Kind != state.PushupSessionWorkout {
		return state.StatePuTest
	}
	p := u.Pushups
	switch {
	case p == nil || !hasPuConsent(u):
		return state.StatePuConsent
	case p.GateIdx < len(c.Gate.Questions):
		return state.StatePuGate
	case p.Goal == "":
		return state.StatePuGoal
	case p.Variation == "":
		return state.StatePuVariation
	case p.Base <= 0:
		return state.StatePuTest
	default:
		return state.StatePuMenu
	}
}

// puResumeTarget is where the landing's «Продолжить тренировку» button and
// the menu's resume row land: the recorded position of the open session,
// corrected for what has happened since — a rest whose timer has already
// expired continues at the next set, a session whose sets are all recorded
// continues at the self-report question.
func puResumeTarget(c *screening.PushupContent, u state.UserData, now time.Time) state.StateKind {
	s := puWorkoutSession(c, u, now)
	if s == nil {
		return puEntryState(c, u, now)
	}
	if len(s.Targets) > 0 && len(s.Actual) >= len(s.Targets) {
		return state.StatePuEffort
	}
	if s.ResumeState == state.StatePuRest && now.Before(s.RestUntil) {
		return state.StatePuRest
	}
	if resumablePuState(s.ResumeState) && s.ResumeState != state.StatePuRest {
		return s.ResumeState
	}
	return state.StatePuSet
}

// puResumeLabel renders the contextual resume row («подход 3/5»).
func puResumeLabel(c *screening.PushupContent, s *state.PushupSession) string {
	current, total := len(s.Actual)+1, len(s.Targets)
	if current > total {
		current = total
	}
	return renderContent(c.UI.ResumeButton, map[string]string{
		"current": strconv.Itoa(current),
		"total":   strconv.Itoa(total),
	})
}

// mutatePuProgram edits the program inside an Outcome.Mutate. state.Store
// hands out a struct copy that still shares pointers, so the program is
// CLONED before it is touched — the project-wide rule for every pointer
// field of UserData.
func mutatePuProgram(u *state.UserData, f func(*state.PushupProgram)) {
	if u.Pushups == nil {
		return
	}
	p := u.Pushups.Clone()
	f(p)
	u.Pushups = p
}

// mutatePuSession is the same for the transient session.
func mutatePuSession(u *state.UserData, f func(*state.PushupSession)) {
	if u.PuSession == nil {
		return
	}
	s := u.PuSession.Clone()
	f(s)
	u.PuSession = s
}

// ─────────────────────────────────────────────────────────────────────────
// Free-number input
// ─────────────────────────────────────────────────────────────────────────

var (
	puRangeRe  = regexp.MustCompile(`(\d{1,4})\s*[-–—]\s*(\d{1,4})`)
	puNumberRe = regexp.MustCompile(`\d{1,4}`)
)

// parsePuReps reads a rep count out of whatever the user typed. The keyboard
// covers most taps; this covers the rest: "12 повторов", "~15", "12-13" (the
// SMALLER of a range — never credit the optimistic end), a bare number.
// Zero is a valid answer, not an error: it is a missed set, which the track
// records and moves on from. Anything without a number, or a number outside
// 0..max, is a re-ask.
func parsePuReps(in string, max int) (int, bool) {
	s := strings.TrimSpace(in)
	if m := puRangeRe.FindStringSubmatch(s); m != nil {
		lo, err1 := strconv.Atoi(m[1])
		hi, err2 := strconv.Atoi(m[2])
		if err1 != nil || err2 != nil {
			return 0, false
		}
		if hi < lo {
			lo = hi
		}
		return lo, lo >= 0 && lo <= max
	}
	m := puNumberRe.FindString(s)
	if m == "" {
		return 0, false
	}
	v, err := strconv.Atoi(m)
	if err != nil || v < 0 || v > max {
		return 0, false
	}
	return v, true
}

// puRepsKeyboard is the suggestion row for a fixed set: the target with its
// neighbours. Free input still works — these only save a keystroke.
func puRepsKeyboard(target int) []string {
	return puNumberRow([]int{target - 1, target, target + 1, target + 2})
}

// puOpenKeyboard is the suggestion row for the open set: the floor and a few
// steps above it, because the open set is where a good day shows up.
func puOpenKeyboard(floor int) []string {
	return puNumberRow([]int{floor, floor + 1, floor + 2, floor + 5})
}

// puNumberRow renders a keyboard row from numbers, dropping negatives and
// duplicates (they appear when the target is tiny).
func puNumberRow(values []int) []string {
	seen := map[int]bool{}
	out := make([]string, 0, len(values))
	for _, v := range values {
		if v < 0 || seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, strconv.Itoa(v))
	}
	return out
}

// ─────────────────────────────────────────────────────────────────────────
// Rendering
// ─────────────────────────────────────────────────────────────────────────

// puSetsLine renders a plan as the user sees it — "7, 8, 6, 6, 9+", with the
// open set marked by its plus.
func puSetsLine(targets []int) string {
	if len(targets) == 0 {
		return ""
	}
	parts := make([]string, 0, len(targets))
	for i, n := range targets {
		s := strconv.Itoa(n)
		if i == len(targets)-1 {
			s += "+"
		}
		parts = append(parts, s)
	}
	return strings.Join(parts, ", ")
}

// puPlan generates the plan of the program's NEXT session. The day index is
// the position inside the week, so the three sessions of a week differ
// without any calendar being involved.
func puPlan(c *screening.PushupContent, p *state.PushupProgram) screening.PushupPlan {
	return c.Plan(screening.PlanInput{
		Base:         p.Base,
		DayIdx:       p.SessionInWeek,
		EffortAdj:    p.EffortAdj,
		Goal:         p.Goal,
		SessionsDone: p.SessionsDone,
		Deload:       p.Deload,
		RestBonusSec: p.RestBonusSec,
	})
}

// puPlanLine is the "Первая тренировка: 7, 8, 6, 6, 9+ — примерно 12 минут."
// line: what the next session looks like, in one line.
func puPlanLine(c *screening.PushupContent, p *state.PushupProgram) string {
	plan := puPlan(c, p)
	return renderContent(c.Test.PlanLine, map[string]string{
		"sets":    puSetsLine(plan.Targets),
		"minutes": strconv.Itoa(c.EstimateMinutes(plan)),
	})
}

// puVariationName is the rung's display name (its id as a fallback — an
// unknown id can only come from hand-edited state).
func puVariationName(c *screening.PushupContent, id string) string {
	if v := c.Variation(id); v != nil {
		return v.Name
	}
	return id
}

// puSum totals a slice of reps.
func puSum(values []int) int {
	total := 0
	for _, v := range values {
		total += v
	}
	return total
}

// puSparkline renders the last open sets as "9 ▁▂▂▃▄▄▅▇ 17" — the track's
// progress picture in one line of text. v1 has no image rendering by
// decision; the two numbers carry the scale the blocks cannot.
func puSparkline(history []state.PushupSessionLog, points int) string {
	values := make([]int, 0, points)
	for i := len(history) - 1; i >= 0 && len(values) < points; i-- {
		if history[i].OpenActual <= 0 {
			continue
		}
		values = append(values, history[i].OpenActual)
	}
	if len(values) == 0 {
		return ""
	}
	// Collected newest-first; the line reads oldest → newest.
	for i, j := 0, len(values)-1; i < j; i, j = i+1, j-1 {
		values[i], values[j] = values[j], values[i]
	}
	lo, hi := values[0], values[0]
	for _, v := range values {
		if v < lo {
			lo = v
		}
		if v > hi {
			hi = v
		}
	}
	var b strings.Builder
	for _, v := range values {
		idx := 0
		if hi > lo {
			idx = (v - lo) * (len(puSparkChars) - 1) / (hi - lo)
		} else {
			idx = len(puSparkChars) / 2
		}
		b.WriteRune(puSparkChars[idx])
	}
	return strconv.Itoa(lo) + " " + b.String() + " " + strconv.Itoa(hi)
}

// pushupReportLine renders the track's single /report line. Empty until the
// first test — there is nothing to report before the base exists.
func pushupReportLine(c *screening.PushupContent, u state.UserData) string {
	p := u.Pushups
	if c == nil || p == nil || p.Base <= 0 || u.PuTest == nil {
		return ""
	}
	return renderContent(c.UI.ReportLine, map[string]string{
		"base":      strconv.Itoa(p.Base),
		"level":     strconv.Itoa(c.Level(p.Base)),
		"variation": strings.ToLower(puVariationName(c, p.Variation)),
		"date":      u.PuTest.TakenAt.Format(reportDateLayout),
		"reps":      strconv.Itoa(u.PuTest.Reps),
		"sessions":  strconv.Itoa(p.SessionsDone),
		"volume":    strconv.Itoa(p.TotalReps),
	})
}

// ─────────────────────────────────────────────────────────────────────────
// Session lifecycle
// ─────────────────────────────────────────────────────────────────────────

// puBeginWorkout generates the session and enters the first set. Everything
// the session needs is frozen into it at this moment (targets, rest), so a
// base change mid-session cannot rewrite the numbers under the user.
func puBeginWorkout(c *screening.PushupContent, p *state.PushupProgram, now time.Time) Outcome {
	plan := puPlan(c, p)
	session := &state.PushupSession{
		Kind:        state.PushupSessionWorkout,
		DayIdx:      p.SessionInWeek,
		Targets:     append([]int(nil), plan.Targets...),
		OpenFloor:   plan.OpenFloor(),
		RestSec:     plan.RestSec,
		StartedAt:   now,
		ResumeState: state.StatePuSet,
	}
	return Outcome{
		NextState: state.StatePuSet,
		Mutate: func(u *state.UserData) {
			u.PuSession = session.Clone()
		},
	}
}

// puTestDue reports whether the next session must be a max test instead of a
// workout: the scheduled retest, one owed by an earlier regression, or a
// pause long enough that the old base is no longer a measurement.
func puTestDue(c *screening.PushupContent, p *state.PushupProgram, now time.Time) bool {
	if p.RetestPending || p.SessionsSinceTest >= c.Params.RetestEverySessions {
		return true
	}
	return puPauseDays(p, now) >= c.Params.PauseRetestDays
}

// puPauseDays is how many whole days have passed since the last session
// (0 when the program has none yet).
func puPauseDays(p *state.PushupProgram, now time.Time) int {
	if p.LastSessionAt.IsZero() {
		return 0
	}
	return int(now.Sub(p.LastSessionAt).Hours() / 24)
}

// puTrain decides what a "train now" tap does. It is the one place the
// track's safety rules live: a session cannot start twice in the recovery
// window (hard block), a due retest replaces the workout, and the weekly
// red-flag check-in runs before the first session of every week.
//
// force is the «Всё равно тренироваться» tap: it only skips the SOFT
// warning between min_hours_between and advised_hours_between, never the
// hard block below min_hours_between.
func puTrain(ctx Context, c *screening.PushupContent, force bool) Outcome {
	u, now := ctx.User, ctx.Now()
	p := u.Pushups
	if p == nil {
		return Outcome{NextState: state.StatePuConsent}
	}
	if s := puWorkoutSession(c, u, now); s != nil {
		// An open session is resumed, never silently replaced.
		return Outcome{NextState: puResumeTarget(c, u, now)}
	}
	if p.Base <= 0 {
		return Outcome{NextState: state.StatePuTest}
	}

	if !p.LastSessionAt.IsZero() {
		since := now.Sub(p.LastSessionAt)
		advised := time.Duration(c.Params.AdvisedHoursBetween) * time.Hour
		switch {
		case puWithinRecovery(c, p, now):
			// Hard block — the one rule force cannot buy through.
			return scrText(c.Session.RestDay)
		case since < advised && !force:
			oc := scrText(renderContent(c.Session.TooSoon, map[string]string{
				"hours":   strconv.Itoa(int(since.Hours())),
				"advised": strconv.Itoa(c.Params.AdvisedHoursBetween),
			}))
			oc.Keyboard = [][]string{{c.Session.TrainAnywayButton}, {homeLabel(ctx)}}
			return oc
		}
	}

	if puTestDue(c, p, now) {
		return Outcome{NextState: state.StatePuTest}
	}
	if p.SessionsDone > 0 && p.SessionInWeek == 0 {
		// Once a week, before the first session: the red-flag check-in.
		return Outcome{NextState: state.StatePuRedCard}
	}
	return puBeginWorkout(c, p, now)
}

// puWithinRecovery is the hard block: less than min_hours_between since the
// last session. It is a property of the PROGRAM, not of a button — every way
// of starting a session asks it, and nothing overrides it.
func puWithinRecovery(c *screening.PushupContent, p *state.PushupProgram, now time.Time) bool {
	if p.LastSessionAt.IsZero() {
		return false
	}
	return now.Sub(p.LastSessionAt) < time.Duration(c.Params.MinHoursBetween)*time.Hour
}

// puRetest decides what the menu's «Перетест» tap does. A max test IS a
// session of the week — it moves the base, counts as the day's work, closes
// the week and writes history — so it goes through the same hard recovery
// block as a workout. Without it the button was a way around the one rule
// the track sells as non-negotiable, and each tap also inflated the week
// counter and the streak.
//
// The SOFT 24–48 h warning is deliberately not re-asked here: reaching for
// «Перетест» on the menu is already the deliberate act that warning asks
// for, and its override button starts a workout, not a test.
func puRetest(ctx Context, c *screening.PushupContent) Outcome {
	u, now := ctx.User, ctx.Now()
	p := u.Pushups
	if p == nil {
		return Outcome{NextState: state.StatePuConsent}
	}
	if s := puWorkoutSession(c, u, now); s != nil {
		// An open session is resumed, never replaced by a test.
		return Outcome{NextState: puResumeTarget(c, u, now)}
	}
	if puWithinRecovery(c, p, now) {
		return scrText(c.Session.RestDay)
	}
	return Outcome{NextState: state.StatePuTest}
}

// puRecordReps writes one performed set and moves the session on: into the
// rest timer, or — after the last, open set — into the self-report question.
// Shared by the set phase and by the rest phase (a number sent during a rest
// means the user trained ahead of the timer, which must not be punished).
func puRecordReps(c *screening.PushupContent, u state.UserData, reps int, now time.Time) Outcome {
	s := u.PuSession
	if s == nil || len(s.Targets) == 0 {
		return Outcome{NextState: state.StatePuMenu}
	}
	idx := len(s.Actual)
	if idx >= len(s.Targets) {
		return Outcome{NextState: state.StatePuEffort}
	}
	last := idx == len(s.Targets)-1

	if !last {
		restUntil := now.Add(time.Duration(s.RestSec) * time.Second)
		// Silent on purpose: the "recorded N, rest M s" line belongs to the
		// rest phase's Setup, which fires right after this transition. That
		// keeps ONE message per set and makes the same line reappear —
		// with the REMAINING seconds — when a paused user comes back.
		oc := Outcome{NextState: state.StatePuRest}
		oc.Mutate = func(u *state.UserData) {
			mutatePuSession(u, func(s *state.PushupSession) {
				s.Actual = append(s.Actual, reps)
				s.Idx = len(s.Actual)
				s.RestUntil = restUntil
				s.ResumeState = state.StatePuRest
			})
		}
		return oc
	}

	// The open set closes the session: summarise, then ask the ONE
	// post-session question.
	actual := append(append([]int(nil), s.Actual...), reps)
	outcome := c.ClassifySession(s.Targets, actual)
	oc := scrText(puSummaryText(c, s, actual, outcome))
	oc.NextState = state.StatePuEffort
	oc.Mutate = func(u *state.UserData) {
		mutatePuSession(u, func(s *state.PushupSession) {
			s.Actual = append(s.Actual, reps)
			s.Idx = len(s.Actual)
			s.RestUntil = time.Time{}
			s.ResumeState = state.StatePuEffort
		})
	}
	return oc
}

// puSummaryText renders the two-number session summary. "Short" is a first
// class outcome: the session still counts, and the text says so.
func puSummaryText(c *screening.PushupContent, s *state.PushupSession, actual []int, outcome string) string {
	open := 0
	if len(actual) > 0 {
		open = actual[len(actual)-1]
	}
	args := map[string]string{
		"total": strconv.Itoa(puSum(actual)),
		"open":  strconv.Itoa(open),
		"extra": strconv.Itoa(open - s.OpenFloor),
	}
	switch outcome {
	case screening.PushupOutcomeOver:
		return renderContent(c.Session.SummaryOver, args)
	case screening.PushupOutcomePlan:
		return renderContent(c.Session.SummaryPlan, args)
	default:
		return renderContent(c.Session.SummaryShort, args)
	}
}

// puSessionLog builds the history entry of a finished session: numbers only,
// no free text — the ring lives inside the shared users.json.
func puSessionLog(c *screening.PushupContent, p *state.PushupProgram, s *state.PushupSession,
	effort string, now time.Time) state.PushupSessionLog {
	outcome := c.ClassifySession(s.Targets, s.Actual)
	open := 0
	if len(s.Actual) == len(s.Targets) && len(s.Actual) > 0 {
		open = s.Actual[len(s.Actual)-1]
	}
	return state.PushupSessionLog{
		Date:       now,
		DayIdx:     s.DayIdx,
		Sets:       append([]int(nil), s.Actual...),
		Planned:    puSum(s.Targets),
		Done:       puSum(s.Actual),
		OpenTarget: s.OpenFloor,
		OpenActual: open,
		Outcome:    outcome,
		Effort:     effort,
		Base:       p.Base,
	}
}

// puCloseSession is the shared bookkeeping of a finished session, applied to
// the program inside one Mutate: counters, the lifetime volume, the next due
// date and the week's outcome list. It does NOT close the week — that is
// puCloseWeek, which has a message to render.
func puCloseSession(c *screening.PushupContent, u *state.UserData, log state.PushupSessionLog, now time.Time) {
	mutatePuProgram(u, func(p *state.PushupProgram) {
		p.SessionsDone++
		p.SessionsSinceTest++
		p.TotalReps += log.Done
		p.LastSessionAt = now
		p.NextDueAt = now.Add(time.Duration(c.Params.AdvisedHoursBetween) * time.Hour)
		p.DuePingSent = false
		p.Deload = false // consumed by the session that just ran
		p.WeekOutcomes = append(p.WeekOutcomes, log.Outcome)
		p.SessionInWeek++
	})
	u.PuHistory = state.AppendPushupLog(u.PuHistory, log, c.Params.HistoryCap)
	u.PuSession = nil
}

// puWeekDue reports whether the week's last session has just been recorded.
func puWeekDue(c *screening.PushupContent, p *state.PushupProgram) bool {
	return p.SessionInWeek >= c.Params.SessionsPerWeek
}

// puCloseWeek applies the weekly rule to the program and returns the line
// that ANNOUNCES it. A repeated week is never silent: a base that quietly
// moves down reads as a bug, so the repeat text says what happened and why.
func puCloseWeek(c *screening.PushupContent, p *state.PushupProgram) string {
	old := p.Base
	wk := c.ProgressWeek(p.Base, p.WeekOutcomes)

	p.Base = wk.NewBase
	p.WeekIdx++
	p.SessionInWeek = 0
	p.WeekOutcomes = nil
	if wk.Repeat {
		p.RepeatCount++
	} else {
		p.RepeatCount = 0
	}
	if wk.StreakGrows {
		p.StreakWeeks++
	}

	args := map[string]string{
		"old":  strconv.Itoa(old),
		"new":  strconv.Itoa(wk.NewBase),
		"base": strconv.Itoa(wk.NewBase),
	}
	switch wk.Kind {
	case screening.PushupWeekStrong:
		return renderContent(c.Week.ClosedStrong, args)
	case screening.PushupWeekHold:
		return renderContent(c.Week.ClosedHold, args)
	case screening.PushupWeekRepeat:
		return renderContent(c.Week.Repeat, args)
	default:
		return renderContent(c.Week.ClosedSteady, args)
	}
}

// puExpired is what closing a stale session did: the line(s) to show and
// whether the week it closed was the third repeated one in a row.
type puExpired struct {
	Text string // "" when there was nothing to expire
	Fork bool   // the closed week hit repeat_fork_after
}

// puExpireSession closes an unfinished session that outlived the TTL: it is
// recorded by what was actually done (a partial session is a real session)
// and the automaton is freed.
//
// A session dying of old age can be the week's third one, so this is a
// second place the week can close — and the week's verdict is ALWAYS spoken
// out loud, on this path exactly as on the finished-session one. A base that
// drops in silence reads as a bug (it is the documented reason people call a
// program broken), and a third repeat in a row owes the user the fork
// instead of a fourth identical week.
func puExpireSession(c *screening.PushupContent, u *state.UserData, now time.Time) puExpired {
	s := u.PuSession
	if s == nil || !s.Stale(now, puSessionTTL(c)) {
		return puExpired{}
	}
	if s.Kind != state.PushupSessionWorkout || u.Pushups == nil || len(s.Actual) == 0 {
		// A dropped max test (or a session with no set recorded) leaves no
		// trace: there is nothing to count.
		u.PuSession = nil
		return puExpired{Text: c.Session.Expired}
	}
	log := puSessionLog(c, u.Pushups, s, "", s.StartedAt)
	puCloseSession(c, u, log, s.StartedAt)

	out := puExpired{Text: c.Session.Expired}
	if puWeekDue(c, u.Pushups) {
		var closing string
		mutatePuProgram(u, func(p *state.PushupProgram) { closing = puCloseWeek(c, p) })
		out.Text += "\n" + closing
		out.Fork = u.Pushups.RepeatCount >= c.Params.Progression.RepeatForkAfter
	}
	return out
}

// puWipeTrack clears every persisted trace of the pushup track.
func puWipeTrack(u *state.UserData) {
	u.PuConsentAt = nil
	u.Pushups = nil
	u.PuSession = nil
	u.PuTest = nil
	u.PuHistory = nil
}
